/* Countries of the world — every UN member state plus inhabited territories.
   Built from: ISO 3166 with UN M49 regions, Wikidata capitals, mledoze/countries
   land borders, and Wikipedia's curated heads-of-state list.
   Flag emoji are derived from each ISO alpha-2 code, so they cannot be wrong.
   Leaders checked 11 August 2026 — the only part of this that goes stale. */

export const COUNTRY_CARDS = [
["Capital of Afghanistan?","Kabul","Southern Asia"],
["Which country's capital is Kabul?","Afghanistan","Southern Asia"],
["🇦🇫  Which country is this?","Afghanistan","Southern Asia"],
["Where is Afghanistan?","Southern Asia. Borders China, Iran, Pakistan, Tajikistan, Turkmenistan and 1 more.","Southern Asia"],
["Capital of Åland Islands?","Mariehamn","Northern Europe"],
["🇦🇽  Which territory is this?","Åland Islands","Northern Europe"],
["Where is Åland Islands?","Northern Europe — an island territory of Finland.","Northern Europe"],
["Capital of Albania?","Tirana","Southern Europe"],
["Which country's capital is Tirana?","Albania","Southern Europe"],
["🇦🇱  Which country is this?","Albania","Southern Europe"],
["Where is Albania?","Southern Europe. Borders Greece, Kosovo, Montenegro, North Macedonia.","Southern Europe"],
["Capital of Algeria?","Algiers","Northern Africa"],
["Which country's capital is Algiers?","Algeria","Northern Africa"],
["🇩🇿  Which country is this?","Algeria","Northern Africa"],
["Where is Algeria?","Northern Africa. Borders Libya, Mali, Mauritania, Morocco, Niger and 2 more.","Northern Africa"],
["Capital of American Samoa?","Pago Pago","Polynesia"],
["🇦🇸  Which territory is this?","American Samoa","Polynesia"],
["Where is American Samoa?","Polynesia — an island territory of the United States.","Polynesia"],
["Capital of Andorra?","Andorra la Vella","Southern Europe"],
["Which country's capital is Andorra la Vella?","Andorra","Southern Europe"],
["🇦🇩  Which country is this?","Andorra","Southern Europe"],
["Where is Andorra?","Southern Europe. Borders France, Spain.","Southern Europe"],
["Capital of Angola?","Luanda","Middle Africa"],
["Which country's capital is Luanda?","Angola","Middle Africa"],
["🇦🇴  Which country is this?","Angola","Middle Africa"],
["Where is Angola?","Middle Africa. Borders DR Congo, Namibia, Republic of the Congo, Zambia.","Middle Africa"],
["Capital of Anguilla?","The Valley","Caribbean"],
["🇦🇮  Which territory is this?","Anguilla","Caribbean"],
["Where is Anguilla?","Caribbean — an island territory of the United Kingdom.","Caribbean"],
["Capital of Antigua and Barbuda?","Saint John's","Caribbean"],
["Which country's capital is Saint John's?","Antigua and Barbuda","Caribbean"],
["🇦🇬  Which country is this?","Antigua and Barbuda","Caribbean"],
["Where is Antigua and Barbuda?","Caribbean — an island nation, no land borders.","Caribbean"],
["Capital of Argentina?","Buenos Aires","South America"],
["Which country's capital is Buenos Aires?","Argentina","South America"],
["🇦🇷  Which country is this?","Argentina","South America"],
["Where is Argentina?","South America. Borders Bolivia, Brazil, Chile, Paraguay, Uruguay.","South America"],
["Capital of Armenia?","Yerevan","Western Asia"],
["Which country's capital is Yerevan?","Armenia","Western Asia"],
["🇦🇲  Which country is this?","Armenia","Western Asia"],
["Where is Armenia?","Western Asia. Borders Azerbaijan, Georgia, Iran, Türkiye.","Western Asia"],
["Capital of Aruba?","Oranjestad","Caribbean"],
["🇦🇼  Which territory is this?","Aruba","Caribbean"],
["Where is Aruba?","Caribbean — an island territory of Aruba.","Caribbean"],
["Capital of Australia?","Canberra","Australia and New Zealand"],
["Which country's capital is Canberra?","Australia","Australia and New Zealand"],
["🇦🇺  Which country is this?","Australia","Australia and New Zealand"],
["Where is Australia?","Australia and New Zealand — an island nation, no land borders.","Australia and New Zealand"],
["Capital of Austria?","Vienna","Western Europe"],
["Which country's capital is Vienna?","Austria","Western Europe"],
["🇦🇹  Which country is this?","Austria","Western Europe"],
["Where is Austria?","Western Europe. Borders Czechia, Germany, Hungary, Italy, Liechtenstein and 3 more.","Western Europe"],
["Capital of Azerbaijan?","Baku","Western Asia"],
["Which country's capital is Baku?","Azerbaijan","Western Asia"],
["🇦🇿  Which country is this?","Azerbaijan","Western Asia"],
["Where is Azerbaijan?","Western Asia. Borders Armenia, Georgia, Iran, Russia, Türkiye.","Western Asia"],
["Capital of Bahamas?","Nassau","Caribbean"],
["Which country's capital is Nassau?","Bahamas","Caribbean"],
["🇧🇸  Which country is this?","Bahamas","Caribbean"],
["Where is Bahamas?","Caribbean — an island nation, no land borders.","Caribbean"],
["Capital of Bahrain?","Manama","Western Asia"],
["Which country's capital is Manama?","Bahrain","Western Asia"],
["🇧🇭  Which country is this?","Bahrain","Western Asia"],
["Where is Bahrain?","Western Asia — an island nation, no land borders.","Western Asia"],
["Capital of Bangladesh?","Dhaka","Southern Asia"],
["Which country's capital is Dhaka?","Bangladesh","Southern Asia"],
["🇧🇩  Which country is this?","Bangladesh","Southern Asia"],
["Where is Bangladesh?","Southern Asia. Borders India, Myanmar.","Southern Asia"],
["Capital of Barbados?","Bridgetown","Caribbean"],
["Which country's capital is Bridgetown?","Barbados","Caribbean"],
["🇧🇧  Which country is this?","Barbados","Caribbean"],
["Where is Barbados?","Caribbean — an island nation, no land borders.","Caribbean"],
["Capital of Belarus?","Minsk","Eastern Europe"],
["Which country's capital is Minsk?","Belarus","Eastern Europe"],
["🇧🇾  Which country is this?","Belarus","Eastern Europe"],
["Where is Belarus?","Eastern Europe. Borders Latvia, Lithuania, Poland, Russia, Ukraine.","Eastern Europe"],
["Capital of Belgium?","Brussels","Western Europe"],
["Which country's capital is Brussels?","Belgium","Western Europe"],
["🇧🇪  Which country is this?","Belgium","Western Europe"],
["Where is Belgium?","Western Europe. Borders France, Germany, Luxembourg, Netherlands.","Western Europe"],
["Capital of Belize?","Belmopan","Central America"],
["Which country's capital is Belmopan?","Belize","Central America"],
["🇧🇿  Which country is this?","Belize","Central America"],
["Where is Belize?","Central America. Borders Guatemala, Mexico.","Central America"],
["Capital of Benin?","Porto-Novo (official) · Cotonou (seat of government)","Western Africa"],
["🇧🇯  Which country is this?","Benin","Western Africa"],
["Where is Benin?","Western Africa. Borders Burkina Faso, Niger, Nigeria, Togo.","Western Africa"],
["Capital of Bermuda?","Hamilton","Northern America"],
["🇧🇲  Which territory is this?","Bermuda","Northern America"],
["Where is Bermuda?","Northern America — an island territory of the United Kingdom.","Northern America"],
["Capital of Bhutan?","Thimphu","Southern Asia"],
["Which country's capital is Thimphu?","Bhutan","Southern Asia"],
["🇧🇹  Which country is this?","Bhutan","Southern Asia"],
["Where is Bhutan?","Southern Asia. Borders China, India.","Southern Asia"],
["Capital of Bolivia?","Sucre (constitutional) · La Paz (seat of government)","South America"],
["🇧🇴  Which country is this?","Bolivia","South America"],
["Where is Bolivia?","South America. Borders Argentina, Brazil, Chile, Paraguay, Peru.","South America"],
["Capital of Bonaire?","Kralendijk","Caribbean"],
["🇧🇶  Which territory is this?","Bonaire","Caribbean"],
["Where is Bonaire?","Caribbean — an island territory of the Netherlands.","Caribbean"],
["Capital of Bosnia and Herzegovina?","Sarajevo","Southern Europe"],
["Which country's capital is Sarajevo?","Bosnia and Herzegovina","Southern Europe"],
["🇧🇦  Which country is this?","Bosnia and Herzegovina","Southern Europe"],
["Where is Bosnia and Herzegovina?","Southern Europe. Borders Croatia, Montenegro, Serbia.","Southern Europe"],
["Capital of Botswana?","Gaborone","Southern Africa"],
["Which country's capital is Gaborone?","Botswana","Southern Africa"],
["🇧🇼  Which country is this?","Botswana","Southern Africa"],
["Where is Botswana?","Southern Africa. Borders Namibia, South Africa, Zambia, Zimbabwe.","Southern Africa"],
["Capital of Brazil?","Brasília","South America"],
["Which country's capital is Brasília?","Brazil","South America"],
["🇧🇷  Which country is this?","Brazil","South America"],
["Where is Brazil?","South America. Borders Argentina, Bolivia, Colombia, French Guiana, Guyana and 5 more.","South America"],
["Capital of Brunei?","Bandar Seri Begawan","South-eastern Asia"],
["Which country's capital is Bandar Seri Begawan?","Brunei","South-eastern Asia"],
["🇧🇳  Which country is this?","Brunei","South-eastern Asia"],
["Where is Brunei?","South-eastern Asia. Borders Malaysia.","South-eastern Asia"],
["Capital of Bulgaria?","Sofia","Eastern Europe"],
["Which country's capital is Sofia?","Bulgaria","Eastern Europe"],
["🇧🇬  Which country is this?","Bulgaria","Eastern Europe"],
["Where is Bulgaria?","Eastern Europe. Borders Greece, North Macedonia, Romania, Serbia, Türkiye.","Eastern Europe"],
["Capital of Burkina Faso?","Ouagadougou","Western Africa"],
["Which country's capital is Ouagadougou?","Burkina Faso","Western Africa"],
["🇧🇫  Which country is this?","Burkina Faso","Western Africa"],
["Where is Burkina Faso?","Western Africa. Borders Benin, Côte d'Ivoire, Ghana, Mali, Niger and 1 more.","Western Africa"],
["Capital of Burundi?","Gitega (political) · Bujumbura (economic)","Eastern Africa"],
["🇧🇮  Which country is this?","Burundi","Eastern Africa"],
["Where is Burundi?","Eastern Africa. Borders DR Congo, Rwanda, Tanzania.","Eastern Africa"],
["Capital of Cabo Verde?","Praia","Western Africa"],
["Which country's capital is Praia?","Cabo Verde","Western Africa"],
["🇨🇻  Which country is this?","Cabo Verde","Western Africa"],
["Where is Cabo Verde?","Western Africa — an island nation, no land borders.","Western Africa"],
["Capital of Cambodia?","Phnom Penh","South-eastern Asia"],
["Which country's capital is Phnom Penh?","Cambodia","South-eastern Asia"],
["🇰🇭  Which country is this?","Cambodia","South-eastern Asia"],
["Where is Cambodia?","South-eastern Asia. Borders Laos, Thailand, Vietnam.","South-eastern Asia"],
["Capital of Cameroon?","Yaoundé","Middle Africa"],
["Which country's capital is Yaoundé?","Cameroon","Middle Africa"],
["🇨🇲  Which country is this?","Cameroon","Middle Africa"],
["Where is Cameroon?","Middle Africa. Borders Central African Republic, Chad, Equatorial Guinea, Gabon, Nigeria and 1 more.","Middle Africa"],
["Capital of Canada?","Ottawa","Northern America"],
["Which country's capital is Ottawa?","Canada","Northern America"],
["🇨🇦  Which country is this?","Canada","Northern America"],
["Where is Canada?","Northern America. Borders United States.","Northern America"],
["Capital of Cayman Islands?","George Town","Caribbean"],
["🇰🇾  Which territory is this?","Cayman Islands","Caribbean"],
["Where is Cayman Islands?","Caribbean — an island territory of the United Kingdom.","Caribbean"],
["Capital of Central African Republic?","Bangui","Middle Africa"],
["Which country's capital is Bangui?","Central African Republic","Middle Africa"],
["🇨🇫  Which country is this?","Central African Republic","Middle Africa"],
["Where is Central African Republic?","Middle Africa. Borders Cameroon, Chad, DR Congo, Republic of the Congo, South Sudan and 1 more.","Middle Africa"],
["Capital of Chad?","N'Djamena","Middle Africa"],
["Which country's capital is N'Djamena?","Chad","Middle Africa"],
["🇹🇩  Which country is this?","Chad","Middle Africa"],
["Where is Chad?","Middle Africa. Borders Cameroon, Central African Republic, Libya, Niger, Nigeria and 1 more.","Middle Africa"],
["Capital of Chile?","Santiago","South America"],
["Which country's capital is Santiago?","Chile","South America"],
["🇨🇱  Which country is this?","Chile","South America"],
["Where is Chile?","South America. Borders Argentina, Bolivia, Peru.","South America"],
["Capital of China?","Beijing","Eastern Asia"],
["Which country's capital is Beijing?","China","Eastern Asia"],
["🇨🇳  Which country is this?","China","Eastern Asia"],
["Where is China?","Eastern Asia. Borders Afghanistan, Bhutan, Hong Kong, India, Kazakhstan and 11 more.","Eastern Asia"],
["Capital of Christmas Island?","Flying Fish Cove","Australia and New Zealand"],
["🇨🇽  Which territory is this?","Christmas Island","Australia and New Zealand"],
["Where is Christmas Island?","Australia and New Zealand — an island territory of Australia.","Australia and New Zealand"],
["Capital of Cocos Islands?","West Island","Australia and New Zealand"],
["🇨🇨  Which territory is this?","Cocos Islands","Australia and New Zealand"],
["Where is Cocos Islands?","Australia and New Zealand — an island territory of Australia.","Australia and New Zealand"],
["Capital of Colombia?","Bogotá","South America"],
["Which country's capital is Bogotá?","Colombia","South America"],
["🇨🇴  Which country is this?","Colombia","South America"],
["Where is Colombia?","South America. Borders Brazil, Ecuador, Panama, Peru, Venezuela.","South America"],
["Capital of Comoros?","Moroni","Eastern Africa"],
["Which country's capital is Moroni?","Comoros","Eastern Africa"],
["🇰🇲  Which country is this?","Comoros","Eastern Africa"],
["Where is Comoros?","Eastern Africa — an island nation, no land borders.","Eastern Africa"],
["Capital of Republic of the Congo?","Brazzaville","Middle Africa"],
["Which country's capital is Brazzaville?","Republic of the Congo","Middle Africa"],
["🇨🇬  Which country is this?","Republic of the Congo","Middle Africa"],
["Where is Republic of the Congo?","Middle Africa. Borders Angola, Cameroon, Central African Republic, DR Congo, Gabon.","Middle Africa"],
["Capital of DR Congo?","Kinshasa","Middle Africa"],
["Which country's capital is Kinshasa?","DR Congo","Middle Africa"],
["🇨🇩  Which country is this?","DR Congo","Middle Africa"],
["Where is DR Congo?","Middle Africa. Borders Angola, Burundi, Central African Republic, Republic of the Congo, Rwanda and 4 more.","Middle Africa"],
["Capital of Cook Islands?","Avarua","Polynesia"],
["🇨🇰  Which territory is this?","Cook Islands","Polynesia"],
["Where is Cook Islands?","Polynesia — an island territory of Cook Islands.","Polynesia"],
["Capital of Costa Rica?","San José","Central America"],
["Which country's capital is San José?","Costa Rica","Central America"],
["🇨🇷  Which country is this?","Costa Rica","Central America"],
["Where is Costa Rica?","Central America. Borders Nicaragua, Panama.","Central America"],
["Capital of Côte d'Ivoire?","Yamoussoukro (official) · Abidjan (seat of government)","Western Africa"],
["🇨🇮  Which country is this?","Côte d'Ivoire","Western Africa"],
["Where is Côte d'Ivoire?","Western Africa. Borders Burkina Faso, Ghana, Guinea, Liberia, Mali.","Western Africa"],
["Capital of Croatia?","Zagreb","Southern Europe"],
["Which country's capital is Zagreb?","Croatia","Southern Europe"],
["🇭🇷  Which country is this?","Croatia","Southern Europe"],
["Where is Croatia?","Southern Europe. Borders Bosnia and Herzegovina, Hungary, Montenegro, Serbia, Slovenia.","Southern Europe"],
["Capital of Cuba?","Havana","Caribbean"],
["Which country's capital is Havana?","Cuba","Caribbean"],
["🇨🇺  Which country is this?","Cuba","Caribbean"],
["Where is Cuba?","Caribbean — an island nation, no land borders.","Caribbean"],
["Capital of Curaçao?","Willemstad","Caribbean"],
["🇨🇼  Which territory is this?","Curaçao","Caribbean"],
["Where is Curaçao?","Caribbean — an island territory of the Netherlands.","Caribbean"],
["Capital of Cyprus?","Nicosia","Western Asia"],
["Which country's capital is Nicosia?","Cyprus","Western Asia"],
["🇨🇾  Which country is this?","Cyprus","Western Asia"],
["Where is Cyprus?","Western Asia — an island nation, no land borders.","Western Asia"],
["Capital of Czechia?","Prague","Eastern Europe"],
["Which country's capital is Prague?","Czechia","Eastern Europe"],
["🇨🇿  Which country is this?","Czechia","Eastern Europe"],
["Where is Czechia?","Eastern Europe. Borders Austria, Germany, Poland, Slovakia.","Eastern Europe"],
["Capital of Denmark?","Copenhagen","Northern Europe"],
["🇩🇰  Which territory is this?","Denmark","Northern Europe"],
["Where is Denmark?","Northern Europe — a territory of Denmark. Borders Germany.","Northern Europe"],
["Capital of Djibouti?","Djibouti","Eastern Africa"],
["Which country's capital is Djibouti?","Djibouti","Eastern Africa"],
["🇩🇯  Which country is this?","Djibouti","Eastern Africa"],
["Where is Djibouti?","Eastern Africa. Borders Eritrea, Ethiopia, Somalia.","Eastern Africa"],
["Capital of Dominica?","Roseau","Caribbean"],
["Which country's capital is Roseau?","Dominica","Caribbean"],
["🇩🇲  Which country is this?","Dominica","Caribbean"],
["Where is Dominica?","Caribbean — an island nation, no land borders.","Caribbean"],
["Capital of Dominican Republic?","Santo Domingo","Caribbean"],
["Which country's capital is Santo Domingo?","Dominican Republic","Caribbean"],
["🇩🇴  Which country is this?","Dominican Republic","Caribbean"],
["Where is Dominican Republic?","Caribbean. Borders Haiti.","Caribbean"],
["Capital of Ecuador?","Quito","South America"],
["Which country's capital is Quito?","Ecuador","South America"],
["🇪🇨  Which country is this?","Ecuador","South America"],
["Where is Ecuador?","South America. Borders Colombia, Peru.","South America"],
["Capital of Egypt?","Cairo","Northern Africa"],
["Which country's capital is Cairo?","Egypt","Northern Africa"],
["🇪🇬  Which country is this?","Egypt","Northern Africa"],
["Where is Egypt?","Northern Africa. Borders Israel, Libya, Palestine, Sudan.","Northern Africa"],
["Capital of El Salvador?","San Salvador","Central America"],
["Which country's capital is San Salvador?","El Salvador","Central America"],
["🇸🇻  Which country is this?","El Salvador","Central America"],
["Where is El Salvador?","Central America. Borders Guatemala, Honduras.","Central America"],
["Capital of Equatorial Guinea?","Ciudad de la Paz","Middle Africa"],
["Which country's capital is Ciudad de la Paz?","Equatorial Guinea","Middle Africa"],
["🇬🇶  Which country is this?","Equatorial Guinea","Middle Africa"],
["Where is Equatorial Guinea?","Middle Africa. Borders Cameroon, Gabon.","Middle Africa"],
["Capital of Eritrea?","Asmara","Eastern Africa"],
["Which country's capital is Asmara?","Eritrea","Eastern Africa"],
["🇪🇷  Which country is this?","Eritrea","Eastern Africa"],
["Where is Eritrea?","Eastern Africa. Borders Djibouti, Ethiopia, Sudan.","Eastern Africa"],
["Capital of Estonia?","Tallinn","Northern Europe"],
["Which country's capital is Tallinn?","Estonia","Northern Europe"],
["🇪🇪  Which country is this?","Estonia","Northern Europe"],
["Where is Estonia?","Northern Europe. Borders Latvia, Russia.","Northern Europe"],
["Capital of Eswatini?","Mbabane (administrative) · Lobamba (legislative)","Southern Africa"],
["🇸🇿  Which country is this?","Eswatini","Southern Africa"],
["Where is Eswatini?","Southern Africa. Borders Mozambique, South Africa.","Southern Africa"],
["Capital of Ethiopia?","Addis Ababa","Eastern Africa"],
["Which country's capital is Addis Ababa?","Ethiopia","Eastern Africa"],
["🇪🇹  Which country is this?","Ethiopia","Eastern Africa"],
["Where is Ethiopia?","Eastern Africa. Borders Djibouti, Eritrea, Kenya, Somalia, South Sudan and 1 more.","Eastern Africa"],
["Capital of Falkland Islands?","Stanley","South America"],
["🇫🇰  Which territory is this?","Falkland Islands","South America"],
["Where is Falkland Islands?","South America — an island territory of the United Kingdom.","South America"],
["Capital of Faroe Islands?","Tórshavn","Northern Europe"],
["🇫🇴  Which territory is this?","Faroe Islands","Northern Europe"],
["Where is Faroe Islands?","Northern Europe — an island territory of Denmark.","Northern Europe"],
["Capital of Fiji?","Suva","Melanesia"],
["Which country's capital is Suva?","Fiji","Melanesia"],
["🇫🇯  Which country is this?","Fiji","Melanesia"],
["Where is Fiji?","Melanesia — an island nation, no land borders.","Melanesia"],
["Capital of Finland?","Helsinki","Northern Europe"],
["Which country's capital is Helsinki?","Finland","Northern Europe"],
["🇫🇮  Which country is this?","Finland","Northern Europe"],
["Where is Finland?","Northern Europe. Borders Norway, Russia, Sweden.","Northern Europe"],
["Capital of France?","Paris","Western Europe"],
["Which country's capital is Paris?","France","Western Europe"],
["🇫🇷  Which country is this?","France","Western Europe"],
["Where is France?","Western Europe. Borders Andorra, Belgium, Germany, Italy, Luxembourg and 3 more.","Western Europe"],
["Capital of French Guiana?","Cayenne","South America"],
["🇬🇫  Which territory is this?","French Guiana","South America"],
["Where is French Guiana?","South America — a territory of France. Borders Brazil, Suriname.","South America"],
["Capital of French Polynesia?","Papeete","Polynesia"],
["🇵🇫  Which territory is this?","French Polynesia","Polynesia"],
["Where is French Polynesia?","Polynesia — an island territory of France.","Polynesia"],
["Capital of Gabon?","Libreville","Middle Africa"],
["Which country's capital is Libreville?","Gabon","Middle Africa"],
["🇬🇦  Which country is this?","Gabon","Middle Africa"],
["Where is Gabon?","Middle Africa. Borders Cameroon, Equatorial Guinea, Republic of the Congo.","Middle Africa"],
["Capital of Gambia?","Banjul","Western Africa"],
["Which country's capital is Banjul?","Gambia","Western Africa"],
["🇬🇲  Which country is this?","Gambia","Western Africa"],
["Where is Gambia?","Western Africa. Borders Senegal.","Western Africa"],
["Capital of Georgia?","Tbilisi","Western Asia"],
["Which country's capital is Tbilisi?","Georgia","Western Asia"],
["🇬🇪  Which country is this?","Georgia","Western Asia"],
["Where is Georgia?","Western Asia. Borders Armenia, Azerbaijan, Russia, Türkiye.","Western Asia"],
["Capital of Germany?","Berlin","Western Europe"],
["Which country's capital is Berlin?","Germany","Western Europe"],
["🇩🇪  Which country is this?","Germany","Western Europe"],
["Where is Germany?","Western Europe. Borders Austria, Belgium, Czechia, Denmark, France and 4 more.","Western Europe"],
["Capital of Ghana?","Accra","Western Africa"],
["Which country's capital is Accra?","Ghana","Western Africa"],
["🇬🇭  Which country is this?","Ghana","Western Africa"],
["Where is Ghana?","Western Africa. Borders Burkina Faso, Côte d'Ivoire, Togo.","Western Africa"],
["Capital of Gibraltar?","Gibraltar is itself the territory — no separate capital","Southern Europe"],
["🇬🇮  Which territory is this?","Gibraltar","Southern Europe"],
["Where is Gibraltar?","Southern Europe — a territory of the United Kingdom. Borders Spain.","Southern Europe"],
["Capital of Greece?","Athens","Southern Europe"],
["Which country's capital is Athens?","Greece","Southern Europe"],
["🇬🇷  Which country is this?","Greece","Southern Europe"],
["Where is Greece?","Southern Europe. Borders Albania, Bulgaria, North Macedonia, Türkiye.","Southern Europe"],
["Capital of Greenland?","Nuuk","Northern America"],
["🇬🇱  Which territory is this?","Greenland","Northern America"],
["Where is Greenland?","Northern America — an island territory of Denmark.","Northern America"],
["Capital of Grenada?","St. George's","Caribbean"],
["Which country's capital is St. George's?","Grenada","Caribbean"],
["🇬🇩  Which country is this?","Grenada","Caribbean"],
["Where is Grenada?","Caribbean — an island nation, no land borders.","Caribbean"],
["Capital of Guadeloupe?","Basse-Terre","Caribbean"],
["🇬🇵  Which territory is this?","Guadeloupe","Caribbean"],
["Where is Guadeloupe?","Caribbean — an island territory of France.","Caribbean"],
["Capital of Guam?","Hagåtña","Micronesia"],
["🇬🇺  Which territory is this?","Guam","Micronesia"],
["Where is Guam?","Micronesia — an island territory of the United States.","Micronesia"],
["Capital of Guatemala?","Guatemala City","Central America"],
["Which country's capital is Guatemala City?","Guatemala","Central America"],
["🇬🇹  Which country is this?","Guatemala","Central America"],
["Where is Guatemala?","Central America. Borders Belize, El Salvador, Honduras, Mexico.","Central America"],
["Capital of Guernsey?","Saint Peter Port","Northern Europe"],
["🇬🇬  Which territory is this?","Guernsey","Northern Europe"],
["Where is Guernsey?","Northern Europe — an island territory of the United Kingdom.","Northern Europe"],
["Capital of Guinea?","Conakry","Western Africa"],
["Which country's capital is Conakry?","Guinea","Western Africa"],
["🇬🇳  Which country is this?","Guinea","Western Africa"],
["Where is Guinea?","Western Africa. Borders Côte d'Ivoire, Guinea-Bissau, Liberia, Mali, Senegal and 1 more.","Western Africa"],
["Capital of Guinea-Bissau?","Bissau","Western Africa"],
["Which country's capital is Bissau?","Guinea-Bissau","Western Africa"],
["🇬🇼  Which country is this?","Guinea-Bissau","Western Africa"],
["Where is Guinea-Bissau?","Western Africa. Borders Guinea, Senegal.","Western Africa"],
["Capital of Guyana?","Georgetown","South America"],
["Which country's capital is Georgetown?","Guyana","South America"],
["🇬🇾  Which country is this?","Guyana","South America"],
["Where is Guyana?","South America. Borders Brazil, Suriname, Venezuela.","South America"],
["Capital of Haiti?","Port-au-Prince","Caribbean"],
["Which country's capital is Port-au-Prince?","Haiti","Caribbean"],
["🇭🇹  Which country is this?","Haiti","Caribbean"],
["Where is Haiti?","Caribbean. Borders Dominican Republic.","Caribbean"],
["Capital of Vatican City?","Vatican City is itself the city-state","Southern Europe"],
["Which country's capital is Vatican City is itself the city-state?","Vatican City","Southern Europe"],
["🇻🇦  Which country is this?","Vatican City","Southern Europe"],
["Where is Vatican City?","Southern Europe. Borders Italy.","Southern Europe"],
["Capital of Honduras?","Tegucigalpa","Central America"],
["Which country's capital is Tegucigalpa?","Honduras","Central America"],
["🇭🇳  Which country is this?","Honduras","Central America"],
["Where is Honduras?","Central America. Borders El Salvador, Guatemala, Nicaragua.","Central America"],
["Capital of Hong Kong?","Hong Kong is itself the city — no separate capital","Eastern Asia"],
["🇭🇰  Which territory is this?","Hong Kong","Eastern Asia"],
["Where is Hong Kong?","Eastern Asia — a territory of China. Borders China.","Eastern Asia"],
["Capital of Hungary?","Budapest","Eastern Europe"],
["Which country's capital is Budapest?","Hungary","Eastern Europe"],
["🇭🇺  Which country is this?","Hungary","Eastern Europe"],
["Where is Hungary?","Eastern Europe. Borders Austria, Croatia, Romania, Serbia, Slovakia and 2 more.","Eastern Europe"],
["Capital of Iceland?","Reykjavík","Northern Europe"],
["Which country's capital is Reykjavík?","Iceland","Northern Europe"],
["🇮🇸  Which country is this?","Iceland","Northern Europe"],
["Where is Iceland?","Northern Europe — an island nation, no land borders.","Northern Europe"],
["Capital of India?","New Delhi","Southern Asia"],
["Which country's capital is New Delhi?","India","Southern Asia"],
["🇮🇳  Which country is this?","India","Southern Asia"],
["Where is India?","Southern Asia. Borders Bangladesh, Bhutan, China, Myanmar, Nepal and 1 more.","Southern Asia"],
["Capital of Indonesia?","Jakarta (Nusantara is being built to replace it)","South-eastern Asia"],
["🇮🇩  Which country is this?","Indonesia","South-eastern Asia"],
["Where is Indonesia?","South-eastern Asia. Borders Malaysia, Papua New Guinea, Timor-Leste.","South-eastern Asia"],
["Capital of Iran?","Tehran","Southern Asia"],
["Which country's capital is Tehran?","Iran","Southern Asia"],
["🇮🇷  Which country is this?","Iran","Southern Asia"],
["Where is Iran?","Southern Asia. Borders Afghanistan, Armenia, Azerbaijan, Iraq, Pakistan and 2 more.","Southern Asia"],
["Capital of Iraq?","Baghdad","Western Asia"],
["Which country's capital is Baghdad?","Iraq","Western Asia"],
["🇮🇶  Which country is this?","Iraq","Western Asia"],
["Where is Iraq?","Western Asia. Borders Iran, Jordan, Kuwait, Saudi Arabia, Syria and 1 more.","Western Asia"],
["Capital of Ireland?","Dublin","Northern Europe"],
["Which country's capital is Dublin?","Ireland","Northern Europe"],
["🇮🇪  Which country is this?","Ireland","Northern Europe"],
["Where is Ireland?","Northern Europe. Borders United Kingdom.","Northern Europe"],
["Capital of Isle of Man?","Douglas","Northern Europe"],
["🇮🇲  Which territory is this?","Isle of Man","Northern Europe"],
["Where is Isle of Man?","Northern Europe — an island territory of Isle of Man.","Northern Europe"],
["Capital of Israel?","Jerusalem","Western Asia"],
["Which country's capital is Jerusalem?","Israel","Western Asia"],
["🇮🇱  Which country is this?","Israel","Western Asia"],
["Where is Israel?","Western Asia. Borders Egypt, Jordan, Lebanon, Palestine, Syria.","Western Asia"],
["Capital of Italy?","Rome","Southern Europe"],
["Which country's capital is Rome?","Italy","Southern Europe"],
["🇮🇹  Which country is this?","Italy","Southern Europe"],
["Where is Italy?","Southern Europe. Borders Austria, France, San Marino, Slovenia, Switzerland and 1 more.","Southern Europe"],
["Capital of Jamaica?","Kingston","Caribbean"],
["Which country's capital is Kingston?","Jamaica","Caribbean"],
["🇯🇲  Which country is this?","Jamaica","Caribbean"],
["Where is Jamaica?","Caribbean — an island nation, no land borders.","Caribbean"],
["Capital of Japan?","Tokyo","Eastern Asia"],
["Which country's capital is Tokyo?","Japan","Eastern Asia"],
["🇯🇵  Which country is this?","Japan","Eastern Asia"],
["Where is Japan?","Eastern Asia — an island nation, no land borders.","Eastern Asia"],
["Capital of Jersey?","Saint Helier","Northern Europe"],
["🇯🇪  Which territory is this?","Jersey","Northern Europe"],
["Where is Jersey?","Northern Europe — an island territory of the United Kingdom.","Northern Europe"],
["Capital of Jordan?","Amman","Western Asia"],
["Which country's capital is Amman?","Jordan","Western Asia"],
["🇯🇴  Which country is this?","Jordan","Western Asia"],
["Where is Jordan?","Western Asia. Borders Iraq, Israel, Palestine, Saudi Arabia, Syria.","Western Asia"],
["Capital of Kazakhstan?","Astana","Central Asia"],
["Which country's capital is Astana?","Kazakhstan","Central Asia"],
["🇰🇿  Which country is this?","Kazakhstan","Central Asia"],
["Where is Kazakhstan?","Central Asia. Borders China, Kyrgyzstan, Russia, Turkmenistan, Uzbekistan.","Central Asia"],
["Capital of Kenya?","Nairobi","Eastern Africa"],
["Which country's capital is Nairobi?","Kenya","Eastern Africa"],
["🇰🇪  Which country is this?","Kenya","Eastern Africa"],
["Where is Kenya?","Eastern Africa. Borders Ethiopia, Somalia, South Sudan, Tanzania, Uganda.","Eastern Africa"],
["Capital of Kiribati?","South Tarawa","Micronesia"],
["Which country's capital is South Tarawa?","Kiribati","Micronesia"],
["🇰🇮  Which country is this?","Kiribati","Micronesia"],
["Where is Kiribati?","Micronesia — an island nation, no land borders.","Micronesia"],
["Capital of North Korea?","Pyongyang","Eastern Asia"],
["Which country's capital is Pyongyang?","North Korea","Eastern Asia"],
["🇰🇵  Which country is this?","North Korea","Eastern Asia"],
["Where is North Korea?","Eastern Asia. Borders China, Russia, South Korea.","Eastern Asia"],
["Capital of South Korea?","Seoul","Eastern Asia"],
["Which country's capital is Seoul?","South Korea","Eastern Asia"],
["🇰🇷  Which country is this?","South Korea","Eastern Asia"],
["Where is South Korea?","Eastern Asia. Borders North Korea.","Eastern Asia"],
["Capital of Kuwait?","Kuwait City","Western Asia"],
["Which country's capital is Kuwait City?","Kuwait","Western Asia"],
["🇰🇼  Which country is this?","Kuwait","Western Asia"],
["Where is Kuwait?","Western Asia. Borders Iraq, Saudi Arabia.","Western Asia"],
["Capital of Kyrgyzstan?","Bishkek","Central Asia"],
["Which country's capital is Bishkek?","Kyrgyzstan","Central Asia"],
["🇰🇬  Which country is this?","Kyrgyzstan","Central Asia"],
["Where is Kyrgyzstan?","Central Asia. Borders China, Kazakhstan, Tajikistan, Uzbekistan.","Central Asia"],
["Capital of Laos?","Vientiane","South-eastern Asia"],
["Which country's capital is Vientiane?","Laos","South-eastern Asia"],
["🇱🇦  Which country is this?","Laos","South-eastern Asia"],
["Where is Laos?","South-eastern Asia. Borders Cambodia, China, Myanmar, Thailand, Vietnam.","South-eastern Asia"],
["Capital of Latvia?","Riga","Northern Europe"],
["Which country's capital is Riga?","Latvia","Northern Europe"],
["🇱🇻  Which country is this?","Latvia","Northern Europe"],
["Where is Latvia?","Northern Europe. Borders Belarus, Estonia, Lithuania, Russia.","Northern Europe"],
["Capital of Lebanon?","Beirut","Western Asia"],
["Which country's capital is Beirut?","Lebanon","Western Asia"],
["🇱🇧  Which country is this?","Lebanon","Western Asia"],
["Where is Lebanon?","Western Asia. Borders Israel, Syria.","Western Asia"],
["Capital of Lesotho?","Maseru","Southern Africa"],
["Which country's capital is Maseru?","Lesotho","Southern Africa"],
["🇱🇸  Which country is this?","Lesotho","Southern Africa"],
["Where is Lesotho?","Southern Africa. Borders South Africa.","Southern Africa"],
["Capital of Liberia?","Monrovia","Western Africa"],
["Which country's capital is Monrovia?","Liberia","Western Africa"],
["🇱🇷  Which country is this?","Liberia","Western Africa"],
["Where is Liberia?","Western Africa. Borders Côte d'Ivoire, Guinea, Sierra Leone.","Western Africa"],
["Capital of Libya?","Tripoli","Northern Africa"],
["Which country's capital is Tripoli?","Libya","Northern Africa"],
["🇱🇾  Which country is this?","Libya","Northern Africa"],
["Where is Libya?","Northern Africa. Borders Algeria, Chad, Egypt, Niger, Sudan and 1 more.","Northern Africa"],
["Capital of Liechtenstein?","Vaduz","Western Europe"],
["Which country's capital is Vaduz?","Liechtenstein","Western Europe"],
["🇱🇮  Which country is this?","Liechtenstein","Western Europe"],
["Where is Liechtenstein?","Western Europe. Borders Austria, Switzerland.","Western Europe"],
["Capital of Lithuania?","Vilnius","Northern Europe"],
["Which country's capital is Vilnius?","Lithuania","Northern Europe"],
["🇱🇹  Which country is this?","Lithuania","Northern Europe"],
["Where is Lithuania?","Northern Europe. Borders Belarus, Latvia, Poland, Russia.","Northern Europe"],
["Capital of Luxembourg?","Luxembourg","Western Europe"],
["Which country's capital is Luxembourg?","Luxembourg","Western Europe"],
["🇱🇺  Which country is this?","Luxembourg","Western Europe"],
["Where is Luxembourg?","Western Europe. Borders Belgium, France, Germany.","Western Europe"],
["Capital of Macau?","Macau is itself the city — no separate capital","Eastern Asia"],
["🇲🇴  Which territory is this?","Macau","Eastern Asia"],
["Where is Macau?","Eastern Asia — a territory of China. Borders China.","Eastern Asia"],
["Capital of Madagascar?","Antananarivo","Eastern Africa"],
["Which country's capital is Antananarivo?","Madagascar","Eastern Africa"],
["🇲🇬  Which country is this?","Madagascar","Eastern Africa"],
["Where is Madagascar?","Eastern Africa — an island nation, no land borders.","Eastern Africa"],
["Capital of Malawi?","Lilongwe","Eastern Africa"],
["Which country's capital is Lilongwe?","Malawi","Eastern Africa"],
["🇲🇼  Which country is this?","Malawi","Eastern Africa"],
["Where is Malawi?","Eastern Africa. Borders Mozambique, Tanzania, Zambia.","Eastern Africa"],
["Capital of Malaysia?","Kuala Lumpur","South-eastern Asia"],
["Which country's capital is Kuala Lumpur?","Malaysia","South-eastern Asia"],
["🇲🇾  Which country is this?","Malaysia","South-eastern Asia"],
["Where is Malaysia?","South-eastern Asia. Borders Brunei, Indonesia, Thailand.","South-eastern Asia"],
["Capital of Maldives?","Malé","Southern Asia"],
["Which country's capital is Malé?","Maldives","Southern Asia"],
["🇲🇻  Which country is this?","Maldives","Southern Asia"],
["Where is Maldives?","Southern Asia — an island nation, no land borders.","Southern Asia"],
["Capital of Mali?","Bamako","Western Africa"],
["Which country's capital is Bamako?","Mali","Western Africa"],
["🇲🇱  Which country is this?","Mali","Western Africa"],
["Where is Mali?","Western Africa. Borders Algeria, Burkina Faso, Côte d'Ivoire, Guinea, Mauritania and 2 more.","Western Africa"],
["Capital of Malta?","Valletta","Southern Europe"],
["Which country's capital is Valletta?","Malta","Southern Europe"],
["🇲🇹  Which country is this?","Malta","Southern Europe"],
["Where is Malta?","Southern Europe — an island nation, no land borders.","Southern Europe"],
["Capital of Marshall Islands?","Majuro","Micronesia"],
["Which country's capital is Majuro?","Marshall Islands","Micronesia"],
["🇲🇭  Which country is this?","Marshall Islands","Micronesia"],
["Where is Marshall Islands?","Micronesia — an island nation, no land borders.","Micronesia"],
["Capital of Martinique?","Fort-de-France","Caribbean"],
["🇲🇶  Which territory is this?","Martinique","Caribbean"],
["Where is Martinique?","Caribbean — an island territory of France.","Caribbean"],
["Capital of Mauritania?","Nouakchott","Western Africa"],
["Which country's capital is Nouakchott?","Mauritania","Western Africa"],
["🇲🇷  Which country is this?","Mauritania","Western Africa"],
["Where is Mauritania?","Western Africa. Borders Algeria, Mali, Senegal, Western Sahara.","Western Africa"],
["Capital of Mauritius?","Port Louis","Eastern Africa"],
["Which country's capital is Port Louis?","Mauritius","Eastern Africa"],
["🇲🇺  Which country is this?","Mauritius","Eastern Africa"],
["Where is Mauritius?","Eastern Africa — an island nation, no land borders.","Eastern Africa"],
["Capital of Mayotte?","Dzaoudzi · Mamoudzou","Eastern Africa"],
["🇾🇹  Which territory is this?","Mayotte","Eastern Africa"],
["Where is Mayotte?","Eastern Africa — an island territory of France.","Eastern Africa"],
["Capital of Mexico?","Mexico City","Central America"],
["Which country's capital is Mexico City?","Mexico","Central America"],
["🇲🇽  Which country is this?","Mexico","Central America"],
["Where is Mexico?","Central America. Borders Belize, Guatemala, United States.","Central America"],
["Capital of Micronesia?","Palikir","Micronesia"],
["Which country's capital is Palikir?","Micronesia","Micronesia"],
["🇫🇲  Which country is this?","Micronesia","Micronesia"],
["Where is Micronesia?","Micronesia — an island nation, no land borders.","Micronesia"],
["Capital of Moldova?","Chișinău","Eastern Europe"],
["Which country's capital is Chișinău?","Moldova","Eastern Europe"],
["🇲🇩  Which country is this?","Moldova","Eastern Europe"],
["Where is Moldova?","Eastern Europe. Borders Romania, Ukraine.","Eastern Europe"],
["Capital of Monaco?","Monaco is a city-state — the city is the country","Western Europe"],
["🇲🇨  Which country is this?","Monaco","Western Europe"],
["Where is Monaco?","Western Europe. Borders France.","Western Europe"],
["Capital of Mongolia?","Ulaanbaatar","Eastern Asia"],
["Which country's capital is Ulaanbaatar?","Mongolia","Eastern Asia"],
["🇲🇳  Which country is this?","Mongolia","Eastern Asia"],
["Where is Mongolia?","Eastern Asia. Borders China, Russia.","Eastern Asia"],
["Capital of Montenegro?","Podgorica","Southern Europe"],
["Which country's capital is Podgorica?","Montenegro","Southern Europe"],
["🇲🇪  Which country is this?","Montenegro","Southern Europe"],
["Where is Montenegro?","Southern Europe. Borders Albania, Bosnia and Herzegovina, Croatia, Kosovo, Serbia.","Southern Europe"],
["Capital of Montserrat?","Brades · Plymouth","Caribbean"],
["🇲🇸  Which territory is this?","Montserrat","Caribbean"],
["Where is Montserrat?","Caribbean — an island territory of the United Kingdom.","Caribbean"],
["Capital of Morocco?","Rabat","Northern Africa"],
["Which country's capital is Rabat?","Morocco","Northern Africa"],
["🇲🇦  Which country is this?","Morocco","Northern Africa"],
["Where is Morocco?","Northern Africa. Borders Algeria, Spain, Western Sahara.","Northern Africa"],
["Capital of Mozambique?","Maputo","Eastern Africa"],
["Which country's capital is Maputo?","Mozambique","Eastern Africa"],
["🇲🇿  Which country is this?","Mozambique","Eastern Africa"],
["Where is Mozambique?","Eastern Africa. Borders Eswatini, Malawi, South Africa, Tanzania, Zambia and 1 more.","Eastern Africa"],
["Capital of Myanmar?","Naypyidaw","South-eastern Asia"],
["Which country's capital is Naypyidaw?","Myanmar","South-eastern Asia"],
["🇲🇲  Which country is this?","Myanmar","South-eastern Asia"],
["Where is Myanmar?","South-eastern Asia. Borders Bangladesh, China, India, Laos, Thailand.","South-eastern Asia"],
["Capital of Namibia?","Windhoek","Southern Africa"],
["Which country's capital is Windhoek?","Namibia","Southern Africa"],
["🇳🇦  Which country is this?","Namibia","Southern Africa"],
["Where is Namibia?","Southern Africa. Borders Angola, Botswana, South Africa, Zambia.","Southern Africa"],
["Capital of Nauru?","Yaren (no official capital)","Micronesia"],
["🇳🇷  Which country is this?","Nauru","Micronesia"],
["Where is Nauru?","Micronesia — an island nation, no land borders.","Micronesia"],
["Capital of Nepal?","Kathmandu","Southern Asia"],
["Which country's capital is Kathmandu?","Nepal","Southern Asia"],
["🇳🇵  Which country is this?","Nepal","Southern Asia"],
["Where is Nepal?","Southern Asia. Borders China, India.","Southern Asia"],
["Capital of Netherlands?","Amsterdam (capital) · The Hague (seat of government)","Western Europe"],
["🇳🇱  Which country is this?","Netherlands","Western Europe"],
["Where is Netherlands?","Western Europe. Borders Belgium, Germany.","Western Europe"],
["Capital of New Caledonia?","Nouméa","Melanesia"],
["🇳🇨  Which territory is this?","New Caledonia","Melanesia"],
["Where is New Caledonia?","Melanesia — an island territory of France.","Melanesia"],
["Capital of New Zealand?","Wellington","Australia and New Zealand"],
["Which country's capital is Wellington?","New Zealand","Australia and New Zealand"],
["🇳🇿  Which country is this?","New Zealand","Australia and New Zealand"],
["Where is New Zealand?","Australia and New Zealand — an island nation, no land borders.","Australia and New Zealand"],
["Capital of Nicaragua?","Managua","Central America"],
["Which country's capital is Managua?","Nicaragua","Central America"],
["🇳🇮  Which country is this?","Nicaragua","Central America"],
["Where is Nicaragua?","Central America. Borders Costa Rica, Honduras.","Central America"],
["Capital of Niger?","Niamey","Western Africa"],
["Which country's capital is Niamey?","Niger","Western Africa"],
["🇳🇪  Which country is this?","Niger","Western Africa"],
["Where is Niger?","Western Africa. Borders Algeria, Benin, Burkina Faso, Chad, Libya and 2 more.","Western Africa"],
["Capital of Nigeria?","Abuja","Western Africa"],
["Which country's capital is Abuja?","Nigeria","Western Africa"],
["🇳🇬  Which country is this?","Nigeria","Western Africa"],
["Where is Nigeria?","Western Africa. Borders Benin, Cameroon, Chad, Niger.","Western Africa"],
["Capital of Niue?","Alofi","Polynesia"],
["🇳🇺  Which territory is this?","Niue","Polynesia"],
["Where is Niue?","Polynesia — an island territory of Niue.","Polynesia"],
["Capital of Norfolk Island?","Kingston","Australia and New Zealand"],
["🇳🇫  Which territory is this?","Norfolk Island","Australia and New Zealand"],
["Where is Norfolk Island?","Australia and New Zealand — an island territory of Australia.","Australia and New Zealand"],
["Capital of North Macedonia?","Skopje","Southern Europe"],
["Which country's capital is Skopje?","North Macedonia","Southern Europe"],
["🇲🇰  Which country is this?","North Macedonia","Southern Europe"],
["Where is North Macedonia?","Southern Europe. Borders Albania, Bulgaria, Greece, Kosovo, Serbia.","Southern Europe"],
["Capital of Northern Mariana Islands?","Saipan","Micronesia"],
["🇲🇵  Which territory is this?","Northern Mariana Islands","Micronesia"],
["Where is Northern Mariana Islands?","Micronesia — an island territory of the United States.","Micronesia"],
["Capital of Norway?","Oslo","Northern Europe"],
["Which country's capital is Oslo?","Norway","Northern Europe"],
["🇳🇴  Which country is this?","Norway","Northern Europe"],
["Where is Norway?","Northern Europe. Borders Finland, Russia, Sweden.","Northern Europe"],
["Capital of Oman?","Muscat","Western Asia"],
["Which country's capital is Muscat?","Oman","Western Asia"],
["🇴🇲  Which country is this?","Oman","Western Asia"],
["Where is Oman?","Western Asia. Borders Saudi Arabia, United Arab Emirates, Yemen.","Western Asia"],
["Capital of Pakistan?","Islamabad","Southern Asia"],
["Which country's capital is Islamabad?","Pakistan","Southern Asia"],
["🇵🇰  Which country is this?","Pakistan","Southern Asia"],
["Where is Pakistan?","Southern Asia. Borders Afghanistan, China, India, Iran.","Southern Asia"],
["Capital of Palau?","Ngerulmud","Micronesia"],
["Which country's capital is Ngerulmud?","Palau","Micronesia"],
["🇵🇼  Which country is this?","Palau","Micronesia"],
["Where is Palau?","Micronesia — an island nation, no land borders.","Micronesia"],
["Capital of Palestine?","Ramallah (administrative) · East Jerusalem (claimed)","Western Asia"],
["🇵🇸  Which country is this?","Palestine","Western Asia"],
["Where is Palestine?","Western Asia. Borders Egypt, Israel, Jordan. Recognised by most UN members; territory is under partial occupation.","Western Asia"],
["Capital of Panama?","Panama City","Central America"],
["Which country's capital is Panama City?","Panama","Central America"],
["🇵🇦  Which country is this?","Panama","Central America"],
["Where is Panama?","Central America. Borders Colombia, Costa Rica.","Central America"],
["Capital of Papua New Guinea?","Port Moresby","Melanesia"],
["Which country's capital is Port Moresby?","Papua New Guinea","Melanesia"],
["🇵🇬  Which country is this?","Papua New Guinea","Melanesia"],
["Where is Papua New Guinea?","Melanesia. Borders Indonesia.","Melanesia"],
["Capital of Paraguay?","Asunción","South America"],
["Which country's capital is Asunción?","Paraguay","South America"],
["🇵🇾  Which country is this?","Paraguay","South America"],
["Where is Paraguay?","South America. Borders Argentina, Bolivia, Brazil.","South America"],
["Capital of Peru?","Lima","South America"],
["Which country's capital is Lima?","Peru","South America"],
["🇵🇪  Which country is this?","Peru","South America"],
["Where is Peru?","South America. Borders Bolivia, Brazil, Chile, Colombia, Ecuador.","South America"],
["Capital of Philippines?","Manila","South-eastern Asia"],
["Which country's capital is Manila?","Philippines","South-eastern Asia"],
["🇵🇭  Which country is this?","Philippines","South-eastern Asia"],
["Where is Philippines?","South-eastern Asia — an island nation, no land borders.","South-eastern Asia"],
["Capital of Pitcairn?","Adamstown","Polynesia"],
["🇵🇳  Which territory is this?","Pitcairn","Polynesia"],
["Where is Pitcairn?","Polynesia — an island territory of the United Kingdom.","Polynesia"],
["Capital of Poland?","Warsaw","Eastern Europe"],
["Which country's capital is Warsaw?","Poland","Eastern Europe"],
["🇵🇱  Which country is this?","Poland","Eastern Europe"],
["Where is Poland?","Eastern Europe. Borders Belarus, Czechia, Germany, Lithuania, Russia and 2 more.","Eastern Europe"],
["Capital of Portugal?","Lisbon","Southern Europe"],
["Which country's capital is Lisbon?","Portugal","Southern Europe"],
["🇵🇹  Which country is this?","Portugal","Southern Europe"],
["Where is Portugal?","Southern Europe. Borders Spain.","Southern Europe"],
["Capital of Puerto Rico?","San Juan","Caribbean"],
["🇵🇷  Which territory is this?","Puerto Rico","Caribbean"],
["Where is Puerto Rico?","Caribbean — an island territory of the United States.","Caribbean"],
["Capital of Qatar?","Doha","Western Asia"],
["Which country's capital is Doha?","Qatar","Western Asia"],
["🇶🇦  Which country is this?","Qatar","Western Asia"],
["Where is Qatar?","Western Asia. Borders Saudi Arabia.","Western Asia"],
["Capital of Réunion?","Saint-Denis","Eastern Africa"],
["🇷🇪  Which territory is this?","Réunion","Eastern Africa"],
["Where is Réunion?","Eastern Africa — an island territory of France.","Eastern Africa"],
["Capital of Romania?","Bucharest","Eastern Europe"],
["Which country's capital is Bucharest?","Romania","Eastern Europe"],
["🇷🇴  Which country is this?","Romania","Eastern Europe"],
["Where is Romania?","Eastern Europe. Borders Bulgaria, Hungary, Moldova, Serbia, Ukraine.","Eastern Europe"],
["Capital of Russia?","Moscow","Eastern Europe"],
["Which country's capital is Moscow?","Russia","Eastern Europe"],
["🇷🇺  Which country is this?","Russia","Eastern Europe"],
["Where is Russia?","Eastern Europe. Borders Azerbaijan, Belarus, China, Estonia, Finland and 9 more.","Eastern Europe"],
["Capital of Rwanda?","Kigali","Eastern Africa"],
["Which country's capital is Kigali?","Rwanda","Eastern Africa"],
["🇷🇼  Which country is this?","Rwanda","Eastern Africa"],
["Where is Rwanda?","Eastern Africa. Borders Burundi, DR Congo, Tanzania, Uganda.","Eastern Africa"],
["Capital of Saint Barthélemy?","Gustavia","Caribbean"],
["🇧🇱  Which territory is this?","Saint Barthélemy","Caribbean"],
["Where is Saint Barthélemy?","Caribbean — an island territory of France.","Caribbean"],
["Capital of Saint Helena?","Jamestown","Western Africa"],
["🇸🇭  Which territory is this?","Saint Helena","Western Africa"],
["Where is Saint Helena?","Western Africa — an island territory of the United Kingdom.","Western Africa"],
["Capital of Saint Kitts and Nevis?","Basseterre","Caribbean"],
["Which country's capital is Basseterre?","Saint Kitts and Nevis","Caribbean"],
["🇰🇳  Which country is this?","Saint Kitts and Nevis","Caribbean"],
["Where is Saint Kitts and Nevis?","Caribbean — an island nation, no land borders.","Caribbean"],
["Capital of Saint Lucia?","Castries","Caribbean"],
["Which country's capital is Castries?","Saint Lucia","Caribbean"],
["🇱🇨  Which country is this?","Saint Lucia","Caribbean"],
["Where is Saint Lucia?","Caribbean — an island nation, no land borders.","Caribbean"],
["Capital of Saint Martin?","Marigot","Caribbean"],
["🇲🇫  Which territory is this?","Saint Martin","Caribbean"],
["Where is Saint Martin?","Caribbean — a territory of France. Borders Sint Maarten.","Caribbean"],
["Capital of Saint Pierre and Miquelon?","Saint-Pierre","Northern America"],
["🇵🇲  Which territory is this?","Saint Pierre and Miquelon","Northern America"],
["Where is Saint Pierre and Miquelon?","Northern America — an island territory of France.","Northern America"],
["Capital of Saint Vincent and the Grenadines?","Kingstown","Caribbean"],
["Which country's capital is Kingstown?","Saint Vincent and the Grenadines","Caribbean"],
["🇻🇨  Which country is this?","Saint Vincent and the Grenadines","Caribbean"],
["Where is Saint Vincent and the Grenadines?","Caribbean — an island nation, no land borders.","Caribbean"],
["Capital of Samoa?","Apia","Polynesia"],
["Which country's capital is Apia?","Samoa","Polynesia"],
["🇼🇸  Which country is this?","Samoa","Polynesia"],
["Where is Samoa?","Polynesia — an island nation, no land borders.","Polynesia"],
["Capital of San Marino?","San Marino","Southern Europe"],
["Which country's capital is San Marino?","San Marino","Southern Europe"],
["🇸🇲  Which country is this?","San Marino","Southern Europe"],
["Where is San Marino?","Southern Europe. Borders Italy.","Southern Europe"],
["Capital of Sao Tome and Principe?","São Tomé","Middle Africa"],
["Which country's capital is São Tomé?","Sao Tome and Principe","Middle Africa"],
["🇸🇹  Which country is this?","Sao Tome and Principe","Middle Africa"],
["Where is Sao Tome and Principe?","Middle Africa — an island nation, no land borders.","Middle Africa"],
["Capital of Saudi Arabia?","Riyadh","Western Asia"],
["Which country's capital is Riyadh?","Saudi Arabia","Western Asia"],
["🇸🇦  Which country is this?","Saudi Arabia","Western Asia"],
["Where is Saudi Arabia?","Western Asia. Borders Iraq, Jordan, Kuwait, Oman, Qatar and 2 more.","Western Asia"],
["Capital of Senegal?","Dakar","Western Africa"],
["Which country's capital is Dakar?","Senegal","Western Africa"],
["🇸🇳  Which country is this?","Senegal","Western Africa"],
["Where is Senegal?","Western Africa. Borders Gambia, Guinea, Guinea-Bissau, Mali, Mauritania.","Western Africa"],
["Capital of Serbia?","Belgrade","Southern Europe"],
["Which country's capital is Belgrade?","Serbia","Southern Europe"],
["🇷🇸  Which country is this?","Serbia","Southern Europe"],
["Where is Serbia?","Southern Europe. Borders Bosnia and Herzegovina, Bulgaria, Croatia, Hungary, Kosovo and 3 more.","Southern Europe"],
["Capital of Seychelles?","Victoria","Eastern Africa"],
["Which country's capital is Victoria?","Seychelles","Eastern Africa"],
["🇸🇨  Which country is this?","Seychelles","Eastern Africa"],
["Where is Seychelles?","Eastern Africa — an island nation, no land borders.","Eastern Africa"],
["Capital of Sierra Leone?","Freetown","Western Africa"],
["Which country's capital is Freetown?","Sierra Leone","Western Africa"],
["🇸🇱  Which country is this?","Sierra Leone","Western Africa"],
["Where is Sierra Leone?","Western Africa. Borders Guinea, Liberia.","Western Africa"],
["Capital of Singapore?","Singapore is a city-state — the city is the country","South-eastern Asia"],
["🇸🇬  Which country is this?","Singapore","South-eastern Asia"],
["Where is Singapore?","South-eastern Asia — an island nation, no land borders.","South-eastern Asia"],
["Capital of Sint Maarten?","Philipsburg","Caribbean"],
["🇸🇽  Which territory is this?","Sint Maarten","Caribbean"],
["Where is Sint Maarten?","Caribbean — a territory of the Netherlands. Borders Saint Martin.","Caribbean"],
["Capital of Slovakia?","Bratislava","Eastern Europe"],
["Which country's capital is Bratislava?","Slovakia","Eastern Europe"],
["🇸🇰  Which country is this?","Slovakia","Eastern Europe"],
["Where is Slovakia?","Eastern Europe. Borders Austria, Czechia, Hungary, Poland, Ukraine.","Eastern Europe"],
["Capital of Slovenia?","Ljubljana","Southern Europe"],
["Which country's capital is Ljubljana?","Slovenia","Southern Europe"],
["🇸🇮  Which country is this?","Slovenia","Southern Europe"],
["Where is Slovenia?","Southern Europe. Borders Austria, Croatia, Hungary, Italy.","Southern Europe"],
["Capital of Solomon Islands?","Honiara","Melanesia"],
["Which country's capital is Honiara?","Solomon Islands","Melanesia"],
["🇸🇧  Which country is this?","Solomon Islands","Melanesia"],
["Where is Solomon Islands?","Melanesia — an island nation, no land borders.","Melanesia"],
["Capital of Somalia?","Mogadishu","Eastern Africa"],
["Which country's capital is Mogadishu?","Somalia","Eastern Africa"],
["🇸🇴  Which country is this?","Somalia","Eastern Africa"],
["Where is Somalia?","Eastern Africa. Borders Djibouti, Ethiopia, Kenya.","Eastern Africa"],
["Capital of South Africa?","Pretoria (executive) · Cape Town (legislative) · Bloemfontein (judicial)","Southern Africa"],
["🇿🇦  Which country is this?","South Africa","Southern Africa"],
["Where is South Africa?","Southern Africa. Borders Botswana, Eswatini, Lesotho, Mozambique, Namibia and 1 more.","Southern Africa"],
["Capital of South Sudan?","Juba","Eastern Africa"],
["Which country's capital is Juba?","South Sudan","Eastern Africa"],
["🇸🇸  Which country is this?","South Sudan","Eastern Africa"],
["Where is South Sudan?","Eastern Africa. Borders Central African Republic, DR Congo, Ethiopia, Kenya, Sudan and 1 more.","Eastern Africa"],
["Capital of Spain?","Madrid","Southern Europe"],
["Which country's capital is Madrid?","Spain","Southern Europe"],
["🇪🇸  Which country is this?","Spain","Southern Europe"],
["Where is Spain?","Southern Europe. Borders Andorra, France, Gibraltar, Morocco, Portugal.","Southern Europe"],
["Capital of Sri Lanka?","Sri Jayawardenepura Kotte (official) · Colombo (commercial)","Southern Asia"],
["🇱🇰  Which country is this?","Sri Lanka","Southern Asia"],
["Where is Sri Lanka?","Southern Asia. Borders India.","Southern Asia"],
["Capital of Sudan?","Khartoum","Northern Africa"],
["Which country's capital is Khartoum?","Sudan","Northern Africa"],
["🇸🇩  Which country is this?","Sudan","Northern Africa"],
["Where is Sudan?","Northern Africa. Borders Central African Republic, Chad, Egypt, Eritrea, Ethiopia and 2 more.","Northern Africa"],
["Capital of Suriname?","Paramaribo","South America"],
["Which country's capital is Paramaribo?","Suriname","South America"],
["🇸🇷  Which country is this?","Suriname","South America"],
["Where is Suriname?","South America. Borders Brazil, French Guiana, Guyana.","South America"],
["Capital of Svalbard and Jan Mayen?","Longyearbyen","Northern Europe"],
["🇸🇯  Which territory is this?","Svalbard and Jan Mayen","Northern Europe"],
["Where is Svalbard and Jan Mayen?","Northern Europe — an island territory of Norway.","Northern Europe"],
["Capital of Sweden?","Stockholm","Northern Europe"],
["Which country's capital is Stockholm?","Sweden","Northern Europe"],
["🇸🇪  Which country is this?","Sweden","Northern Europe"],
["Where is Sweden?","Northern Europe. Borders Finland, Norway.","Northern Europe"],
["Capital of Switzerland?","Bern (federal city — Switzerland names no formal capital)","Western Europe"],
["🇨🇭  Which country is this?","Switzerland","Western Europe"],
["Where is Switzerland?","Western Europe. Borders Austria, France, Germany, Italy, Liechtenstein.","Western Europe"],
["Capital of Syria?","Damascus","Western Asia"],
["Which country's capital is Damascus?","Syria","Western Asia"],
["🇸🇾  Which country is this?","Syria","Western Asia"],
["Where is Syria?","Western Asia. Borders Iraq, Israel, Jordan, Lebanon, Türkiye.","Western Asia"],
["Capital of Taiwan?","Taipei","Eastern Asia"],
["Which country's capital is Taipei?","Taiwan","Eastern Asia"],
["🇹🇼  Which country is this?","Taiwan","Eastern Asia"],
["Where is Taiwan?","Eastern Asia — an island nation, no land borders. Governed separately from mainland China, which claims it.","Eastern Asia"],
["Capital of Tajikistan?","Dushanbe","Central Asia"],
["Which country's capital is Dushanbe?","Tajikistan","Central Asia"],
["🇹🇯  Which country is this?","Tajikistan","Central Asia"],
["Where is Tajikistan?","Central Asia. Borders Afghanistan, China, Kyrgyzstan, Uzbekistan.","Central Asia"],
["Capital of Tanzania?","Dodoma (official) · Dar es Salaam (largest city)","Eastern Africa"],
["🇹🇿  Which country is this?","Tanzania","Eastern Africa"],
["Where is Tanzania?","Eastern Africa. Borders Burundi, DR Congo, Kenya, Malawi, Mozambique and 3 more.","Eastern Africa"],
["Capital of Thailand?","Bangkok","South-eastern Asia"],
["Which country's capital is Bangkok?","Thailand","South-eastern Asia"],
["🇹🇭  Which country is this?","Thailand","South-eastern Asia"],
["Where is Thailand?","South-eastern Asia. Borders Cambodia, Laos, Malaysia, Myanmar.","South-eastern Asia"],
["Capital of Timor-Leste?","Dili","South-eastern Asia"],
["Which country's capital is Dili?","Timor-Leste","South-eastern Asia"],
["🇹🇱  Which country is this?","Timor-Leste","South-eastern Asia"],
["Where is Timor-Leste?","South-eastern Asia. Borders Indonesia.","South-eastern Asia"],
["Capital of Togo?","Lomé","Western Africa"],
["Which country's capital is Lomé?","Togo","Western Africa"],
["🇹🇬  Which country is this?","Togo","Western Africa"],
["Where is Togo?","Western Africa. Borders Benin, Burkina Faso, Ghana.","Western Africa"],
["Capital of Tokelau?","No capital — the three atolls take turns","Polynesia"],
["🇹🇰  Which territory is this?","Tokelau","Polynesia"],
["Where is Tokelau?","Polynesia — an island territory of New Zealand.","Polynesia"],
["Capital of Tonga?","Nukuʻalofa","Polynesia"],
["Which country's capital is Nukuʻalofa?","Tonga","Polynesia"],
["🇹🇴  Which country is this?","Tonga","Polynesia"],
["Where is Tonga?","Polynesia — an island nation, no land borders.","Polynesia"],
["Capital of Trinidad and Tobago?","Port of Spain","Caribbean"],
["Which country's capital is Port of Spain?","Trinidad and Tobago","Caribbean"],
["🇹🇹  Which country is this?","Trinidad and Tobago","Caribbean"],
["Where is Trinidad and Tobago?","Caribbean — an island nation, no land borders.","Caribbean"],
["Capital of Tunisia?","Tunis","Northern Africa"],
["Which country's capital is Tunis?","Tunisia","Northern Africa"],
["🇹🇳  Which country is this?","Tunisia","Northern Africa"],
["Where is Tunisia?","Northern Africa. Borders Algeria, Libya.","Northern Africa"],
["Capital of Türkiye?","Ankara","Western Asia"],
["Which country's capital is Ankara?","Türkiye","Western Asia"],
["🇹🇷  Which country is this?","Türkiye","Western Asia"],
["Where is Türkiye?","Western Asia. Borders Armenia, Azerbaijan, Bulgaria, Georgia, Greece and 3 more.","Western Asia"],
["Capital of Turkmenistan?","Ashgabat","Central Asia"],
["Which country's capital is Ashgabat?","Turkmenistan","Central Asia"],
["🇹🇲  Which country is this?","Turkmenistan","Central Asia"],
["Where is Turkmenistan?","Central Asia. Borders Afghanistan, Iran, Kazakhstan, Uzbekistan.","Central Asia"],
["Capital of Turks and Caicos Islands?","Cockburn Town","Caribbean"],
["🇹🇨  Which territory is this?","Turks and Caicos Islands","Caribbean"],
["Where is Turks and Caicos Islands?","Caribbean — an island territory of the United Kingdom.","Caribbean"],
["Capital of Tuvalu?","Funafuti","Polynesia"],
["Which country's capital is Funafuti?","Tuvalu","Polynesia"],
["🇹🇻  Which country is this?","Tuvalu","Polynesia"],
["Where is Tuvalu?","Polynesia — an island nation, no land borders.","Polynesia"],
["Capital of Uganda?","Kampala","Eastern Africa"],
["Which country's capital is Kampala?","Uganda","Eastern Africa"],
["🇺🇬  Which country is this?","Uganda","Eastern Africa"],
["Where is Uganda?","Eastern Africa. Borders DR Congo, Kenya, Rwanda, South Sudan, Tanzania.","Eastern Africa"],
["Capital of Ukraine?","Kyiv","Eastern Europe"],
["Which country's capital is Kyiv?","Ukraine","Eastern Europe"],
["🇺🇦  Which country is this?","Ukraine","Eastern Europe"],
["Where is Ukraine?","Eastern Europe. Borders Belarus, Hungary, Moldova, Poland, Romania and 2 more.","Eastern Europe"],
["Capital of United Arab Emirates?","Abu Dhabi","Western Asia"],
["Which country's capital is Abu Dhabi?","United Arab Emirates","Western Asia"],
["🇦🇪  Which country is this?","United Arab Emirates","Western Asia"],
["Where is United Arab Emirates?","Western Asia. Borders Oman, Saudi Arabia.","Western Asia"],
["Capital of United Kingdom?","London","Northern Europe"],
["Which country's capital is London?","United Kingdom","Northern Europe"],
["🇬🇧  Which country is this?","United Kingdom","Northern Europe"],
["Where is United Kingdom?","Northern Europe. Borders Ireland.","Northern Europe"],
["Capital of United States?","Washington, D.C.","Northern America"],
["Which country's capital is Washington, D.C.?","United States","Northern America"],
["🇺🇸  Which country is this?","United States","Northern America"],
["Where is United States?","Northern America. Borders Canada, Mexico.","Northern America"],
["Capital of Uruguay?","Montevideo","South America"],
["Which country's capital is Montevideo?","Uruguay","South America"],
["🇺🇾  Which country is this?","Uruguay","South America"],
["Where is Uruguay?","South America. Borders Argentina, Brazil.","South America"],
["Capital of Uzbekistan?","Tashkent","Central Asia"],
["Which country's capital is Tashkent?","Uzbekistan","Central Asia"],
["🇺🇿  Which country is this?","Uzbekistan","Central Asia"],
["Where is Uzbekistan?","Central Asia. Borders Afghanistan, Kazakhstan, Kyrgyzstan, Tajikistan, Turkmenistan.","Central Asia"],
["Capital of Vanuatu?","Port Vila","Melanesia"],
["Which country's capital is Port Vila?","Vanuatu","Melanesia"],
["🇻🇺  Which country is this?","Vanuatu","Melanesia"],
["Where is Vanuatu?","Melanesia — an island nation, no land borders.","Melanesia"],
["Capital of Venezuela?","Caracas","South America"],
["Which country's capital is Caracas?","Venezuela","South America"],
["🇻🇪  Which country is this?","Venezuela","South America"],
["Where is Venezuela?","South America. Borders Brazil, Colombia, Guyana.","South America"],
["Capital of Vietnam?","Hanoi","South-eastern Asia"],
["Which country's capital is Hanoi?","Vietnam","South-eastern Asia"],
["🇻🇳  Which country is this?","Vietnam","South-eastern Asia"],
["Where is Vietnam?","South-eastern Asia. Borders Cambodia, China, Laos.","South-eastern Asia"],
["Capital of British Virgin Islands?","Road Town","Caribbean"],
["🇻🇬  Which territory is this?","British Virgin Islands","Caribbean"],
["Where is British Virgin Islands?","Caribbean — an island territory of the United Kingdom.","Caribbean"],
["Capital of U.S. Virgin Islands?","Charlotte Amalie","Caribbean"],
["🇻🇮  Which territory is this?","U.S. Virgin Islands","Caribbean"],
["Where is U.S. Virgin Islands?","Caribbean — an island territory of the United States.","Caribbean"],
["Capital of Wallis and Futuna?","Mata-Utu","Polynesia"],
["🇼🇫  Which territory is this?","Wallis and Futuna","Polynesia"],
["Where is Wallis and Futuna?","Polynesia — an island territory of France.","Polynesia"],
["Capital of Western Sahara?","Laayoune (claimed by Morocco) · Tifariti (Sahrawi Republic)","Northern Africa"],
["🇪🇭  Which country is this?","Western Sahara","Northern Africa"],
["Where is Western Sahara?","Northern Africa. Borders Algeria, Mauritania, Morocco. Disputed — most of it is controlled by Morocco, claimed by the Sahrawi Republic.","Northern Africa"],
["Capital of Yemen?","Sanaa (de jure) · Aden (seat of government)","Western Asia"],
["🇾🇪  Which country is this?","Yemen","Western Asia"],
["Where is Yemen?","Western Asia. Borders Oman, Saudi Arabia.","Western Asia"],
["Capital of Zambia?","Lusaka","Eastern Africa"],
["Which country's capital is Lusaka?","Zambia","Eastern Africa"],
["🇿🇲  Which country is this?","Zambia","Eastern Africa"],
["Where is Zambia?","Eastern Africa. Borders Angola, Botswana, DR Congo, Malawi, Mozambique and 3 more.","Eastern Africa"],
["Capital of Zimbabwe?","Harare","Eastern Africa"],
["Which country's capital is Harare?","Zimbabwe","Eastern Africa"],
["🇿🇼  Which country is this?","Zimbabwe","Eastern Africa"],
["Where is Zimbabwe?","Eastern Africa. Borders Botswana, Mozambique, South Africa, Zambia.","Eastern Africa"],
["Capital of Kosovo?","Pristina","Southern Europe"],
["Which country's capital is Pristina?","Kosovo","Southern Europe"],
["🇽🇰  Which country is this?","Kosovo","Southern Europe"],
["Where is Kosovo?","Southern Europe. Borders Albania, Montenegro, North Macedonia, Serbia. Declared independence in 2008; recognition is partial.","Southern Europe"],
["Which countries make up Northern Africa?","Algeria, Egypt, Libya, Morocco, Sudan, Tunisia, Western Sahara","Northern Africa"],
["Which countries make up Central America?","Belize, Costa Rica, El Salvador, Guatemala, Honduras, Mexico, Nicaragua, Panama","Central America"],
["Which countries make up Southern Africa?","Botswana, Eswatini, Lesotho, Namibia, South Africa","Southern Africa"],
["Which countries make up Eastern Asia?","China, Japan, Mongolia, North Korea, South Korea, Taiwan","Eastern Asia"],
["Which countries make up Melanesia?","Fiji, Papua New Guinea, Solomon Islands, Vanuatu","Melanesia"],
["Which countries make up Central Asia?","Kazakhstan, Kyrgyzstan, Tajikistan, Turkmenistan, Uzbekistan","Central Asia"],
["Which countries make up Micronesia?","Kiribati, Marshall Islands, Micronesia, Nauru, Palau","Micronesia"],
["Which countries make up Polynesia?","Samoa, Tonga, Tuvalu","Polynesia"]
].map(([front, back, category]) => ({ front, back, category }));

/* Heads of state and government as they stood on 11 August 2026. Governments change;
   this deck is meant to be deleted and rebuilt rather than trusted for years. */
export const LEADER_STAMP = "11 August 2026";
export const LEADER_CARDS = [
["Head of state of Afghanistan?","Supreme Leader – Hibatullah Akhundzada","Southern Asia"],
["Head of government of Afghanistan?","Prime Minister – Hasan Akhund","Southern Asia"],
["Head of state of Albania?","President – Bajram Begaj","Southern Europe"],
["Head of government of Albania?","Prime Minister – Edi Rama","Southern Europe"],
["Head of state of Algeria?","President – Abdelmadjid Tebboune","Northern Africa"],
["Head of government of Algeria?","Prime Minister – Sifi Ghrieb","Northern Africa"],
["Head of state of Andorra?","Episcopal Co-prince – Josep-Lluís Serrano PentinatCo-prince's Representative – Eduard IbáñezFrench Co-prince – Emmanuel MacronCo-prince's Representative – Georges-François Leclerc","Southern Europe"],
["Head of government of Andorra?","Prime Minister – Xavier Espot Zamora","Southern Europe"],
["Who leads Angola?","President – João Lourenço","Middle Africa"],
["Head of state of Antigua and Barbuda?","King – Charles IIIGovernor-General – Sir Rodney Williams","Caribbean"],
["Head of government of Antigua and Barbuda?","Prime Minister – Gaston Browne","Caribbean"],
["Who leads Argentina?","President – Javier Milei","South America"],
["Head of state of Armenia?","President – Vahagn Khachaturyan","Western Asia"],
["Head of government of Armenia?","Prime Minister – Nikol Pashinyan","Western Asia"],
["Head of state of Australia?","King – Charles IIIGovernor-General – Sam Mostyn","Australia and New Zealand"],
["Head of government of Australia?","Prime Minister – Anthony Albanese","Australia and New Zealand"],
["Head of state of Austria?","President – Alexander Van der Bellen","Western Europe"],
["Head of government of Austria?","Chancellor – Christian Stocker","Western Europe"],
["Head of state of Azerbaijan?","President – Ilham Aliyev","Western Asia"],
["Head of government of Azerbaijan?","Prime Minister – Ali Asadov","Western Asia"],
["Head of state of Bahamas?","King – Charles IIIGovernor-General – Dame Cynthia A. Pratt","Caribbean"],
["Head of government of Bahamas?","Prime Minister – Philip Davis","Caribbean"],
["Head of state of Bahrain?","King – Sheikh Hamad bin Isa Al Khalifa","Western Asia"],
["Head of government of Bahrain?","Prime Minister – Prince Salman bin Hamad Al Khalifa","Western Asia"],
["Head of state of Bangladesh?","Acting President – Hafiz Uddin Ahmad","Southern Asia"],
["Head of government of Bangladesh?","Prime Minister – Tarique Rahman","Southern Asia"],
["Head of state of Barbados?","President – Jeffrey Bostic","Caribbean"],
["Head of government of Barbados?","Prime Minister – Mia Mottley","Caribbean"],
["Who leads Belarus?","Chairman of the All-Belarusian People's Assembly – Alexander Lukashenko","Eastern Europe"],
["Head of state of Belgium?","King – Philippe","Western Europe"],
["Head of government of Belgium?","Prime Minister – Bart De Wever","Western Europe"],
["Head of state of Belize?","King – Charles IIIGovernor-General – Dame Froyla Tzalam","Central America"],
["Head of government of Belize?","Prime Minister – Johnny Briceño","Central America"],
["Who leads Benin?","President – Romuald Wadagni","Western Africa"],
["Head of state of Bhutan?","King – Jigme Khesar Namgyel Wangchuck","Southern Asia"],
["Head of government of Bhutan?","Prime Minister – Tshering Tobgay","Southern Asia"],
["Who leads Bolivia?","President – Rodrigo Paz","South America"],
["Who leads Botswana?","President – Duma Boko","Southern Africa"],
["Who leads Brazil?","President – Luiz Inácio Lula da Silva","South America"],
["Head of state of Brunei?","Sultan – Hassanal Bolkiah","South-eastern Asia"],
["Head of government of Brunei?","Prime Minister – Hassanal Bolkiah","South-eastern Asia"],
["Head of state of Bulgaria?","President – Iliana Iotova","Eastern Europe"],
["Head of government of Bulgaria?","Prime Minister – Rumen Radev","Eastern Europe"],
["Who leads Burkina Faso?","President of the Patriotic Movement for Safeguard and Restoration – Ibrahim Traoré","Western Africa"],
["Head of state of Burundi?","President – Évariste Ndayishimiye","Eastern Africa"],
["Head of government of Burundi?","Prime Minister – Nestor Ntahontuye","Eastern Africa"],
["Who leads Cambodia?","President of the People's Party – Hun Sen","South-eastern Asia"],
["Head of state of Cameroon?","President – Paul Biya","Middle Africa"],
["Head of government of Cameroon?","Prime Minister – Joseph Ngute","Middle Africa"],
["Head of state of Canada?","King – Charles IIIGovernor General – Louise Arbour","Northern America"],
["Head of government of Canada?","Prime Minister – Mark Carney","Northern America"],
["Head of state of Cabo Verde?","President – José Maria Neves","Western Africa"],
["Head of government of Cabo Verde?","Prime Minister – Francisco Carvalho","Western Africa"],
["Head of state of Central African Republic?","President – Faustin-Archange Touadéra","Middle Africa"],
["Head of government of Central African Republic?","Prime Minister – Félix Moloua","Middle Africa"],
["Head of state of Chad?","President – Mahamat Déby","Middle Africa"],
["Head of government of Chad?","Prime Minister – Allamaye Halina","Middle Africa"],
["Who leads Chile?","President – José Antonio Kast","South America"],
["Who leads China?","General Secretary of the Communist Party – Xi Jinping","Eastern Asia"],
["Who leads Colombia?","President – Abelardo de la Espriella","South America"],
["Who leads Comoros?","President – Azali Assoumani","Eastern Africa"],
["Head of state of DR Congo?","President – Félix Tshisekedi","Middle Africa"],
["Head of government of DR Congo?","Prime Minister – Judith Suminwa","Middle Africa"],
["Head of state of Republic of the Congo?","President – Denis Sassou Nguesso","Middle Africa"],
["Head of government of Republic of the Congo?","Prime Minister – Anatole Collinet Makosso","Middle Africa"],
["Who leads Costa Rica?","President – Laura Fernández","Central America"],
["Head of state of Croatia?","President – Zoran Milanović","Southern Europe"],
["Head of government of Croatia?","Prime Minister – Andrej Plenković","Southern Europe"],
["Who leads Cuba?","First Secretary of the Communist Party – Miguel Díaz-Canel","Caribbean"],
["Who leads Cyprus?","President – Nikos Christodoulides","Western Asia"],
["Head of state of Czechia?","President – Petr Pavel","Eastern Europe"],
["Head of government of Czechia?","Prime Minister – Andrej Babiš","Eastern Europe"],
["Head of state of Denmark?","King – Frederik X","Northern Europe"],
["Head of government of Denmark?","Prime Minister – Mette Frederiksen","Northern Europe"],
["Who leads Djibouti?","President – Ismaïl Omar Guelleh","Eastern Africa"],
["Head of state of Dominica?","President – Sylvanie Burton","Caribbean"],
["Head of government of Dominica?","Prime Minister – Roosevelt Skerrit","Caribbean"],
["Who leads Dominican Republic?","President – Luis Abinader","Caribbean"],
["Who leads Ecuador?","President – Daniel Noboa","South America"],
["Head of state of Egypt?","President – Abdel Fattah el-Sisi","Northern Africa"],
["Head of government of Egypt?","Prime Minister – Mostafa Madbouly","Northern Africa"],
["Who leads El Salvador?","President – Nayib Bukele","Central America"],
["Head of state of Equatorial Guinea?","President – Teodoro Obiang Nguema Mbasogo","Middle Africa"],
["Head of government of Equatorial Guinea?","Prime Minister – Manuel Osa Nsue Nsua","Middle Africa"],
["Who leads Eritrea?","President – Isaias Afwerki","Eastern Africa"],
["Head of state of Estonia?","President – Alar Karis","Northern Europe"],
["Head of government of Estonia?","Prime Minister – Kristen Michal","Northern Europe"],
["Head of state of Eswatini?","Ngwenyama – Mswati III","Southern Africa"],
["Head of government of Eswatini?","Prime Minister – Russell Dlamini","Southern Africa"],
["Head of state of Ethiopia?","President – Taye Atske Selassie","Eastern Africa"],
["Head of government of Ethiopia?","Prime Minister – Abiy Ahmed","Eastern Africa"],
["Head of state of Fiji?","President – Ratu Naiqama Lalabalavu","Melanesia"],
["Head of government of Fiji?","Prime Minister – Sitiveni Rabuka","Melanesia"],
["Head of state of Finland?","President – Alexander Stubb","Northern Europe"],
["Head of government of Finland?","Prime Minister – Petteri Orpo","Northern Europe"],
["Head of state of France?","President – Emmanuel Macron","Western Europe"],
["Head of government of France?","Prime Minister – Sébastien Lecornu","Western Europe"],
["Who leads Gabon?","President – Brice Oligui Nguema","Middle Africa"],
["Who leads Gambia?","President – Adama Barrow","Western Africa"],
["Who leads Georgia?","Honorary Chairman of Georgian Dream – Bidzina Ivanishvili","Western Asia"],
["Head of state of Germany?","President – Frank-Walter Steinmeier","Western Europe"],
["Head of government of Germany?","Chancellor – Friedrich Merz","Western Europe"],
["Who leads Ghana?","President – John Mahama","Western Africa"],
["Head of state of Greece?","President – Konstantinos Tasoulas","Southern Europe"],
["Head of government of Greece?","Prime Minister – Kyriakos Mitsotakis","Southern Europe"],
["Head of state of Grenada?","King – Charles IIIGovernor-General – Dame Cécile La Grenade","Caribbean"],
["Head of government of Grenada?","Prime Minister – Dickon Mitchell","Caribbean"],
["Who leads Guatemala?","President – Bernardo Arévalo","Central America"],
["Head of state of Guinea?","President – Mamady Doumbouya","Western Africa"],
["Head of government of Guinea?","Prime Minister – Bah Oury","Western Africa"],
["Who leads Guinea-Bissau?","Chief of the High Command – Horta Na Man","Western Africa"],
["Who leads Guyana?","President – Irfaan Ali","South America"],
["Head of state of Haiti?","President – Vacant","Caribbean"],
["Head of government of Haiti?","Acting Prime Minister – Alix Didier Fils-Aimé","Caribbean"],
["Who leads Honduras?","President – Nasry Asfura","Central America"],
["Head of state of Hungary?","Acting President – Ágnes Forsthoffer","Eastern Europe"],
["Head of government of Hungary?","rowspan=\"2\" Prime Minister – Péter Magyar","Eastern Europe"],
["Head of state of Iceland?","President – Halla Tómasdóttir","Northern Europe"],
["Head of government of Iceland?","Prime Minister – Kristrún Frostadóttir","Northern Europe"],
["Head of state of India?","President – Droupadi Murmu","Southern Asia"],
["Head of government of India?","Prime Minister – Narendra Modi","Southern Asia"],
["Who leads Indonesia?","President – Prabowo Subianto","South-eastern Asia"],
["Who leads Iran?","Supreme Leader – Mojtaba Khamenei","Southern Asia"],
["Head of state of Iraq?","President – Nizar Amidi","Western Asia"],
["Head of government of Iraq?","Prime Minister – Ali al-Zaidi","Western Asia"],
["Head of state of Ireland?","President – Catherine Connolly","Northern Europe"],
["Head of government of Ireland?","Taoiseach – Micheál Martin","Northern Europe"],
["Head of state of Israel?","President – Isaac Herzog","Western Asia"],
["Head of government of Israel?","Prime Minister – Benjamin Netanyahu","Western Asia"],
["Head of state of Italy?","President – Sergio Mattarella","Southern Europe"],
["Head of government of Italy?","Prime Minister – Giorgia Meloni","Southern Europe"],
["Head of state of Côte d'Ivoire?","President – Alassane Ouattara","Western Africa"],
["Head of government of Côte d'Ivoire?","Prime Minister – Robert Beugré Mambé","Western Africa"],
["Head of state of Jamaica?","King – Charles IIIGovernor-General – Sir Patrick Allen","Caribbean"],
["Head of government of Jamaica?","Prime Minister – Andrew Holness","Caribbean"],
["Head of state of Japan?","Emperor – Naruhito","Eastern Asia"],
["Head of government of Japan?","Prime Minister – Sanae Takaichi","Eastern Asia"],
["Head of state of Jordan?","King – Abdullah II","Western Asia"],
["Head of government of Jordan?","Prime Minister – Jafar Hassan","Western Asia"],
["Head of state of Kazakhstan?","President – Kassym-Jomart Tokayev","Central Asia"],
["Head of government of Kazakhstan?","Prime Minister – Oljas Bektenov","Central Asia"],
["Who leads Kenya?","President – William Ruto","Eastern Africa"],
["Who leads Kiribati?","President – Taneti Maamau","Micronesia"],
["Head of state of Kuwait?","Emir – Sheikh Mishal Al-Ahmad Al-Jaber Al-Sabah","Western Asia"],
["Head of government of Kuwait?","Prime Minister – Ahmad Al-Abdullah Al-Sabah","Western Asia"],
["Who leads Kyrgyzstan?","President – Sadyr Japarov","Central Asia"],
["Who leads Laos?","General Secretary of the People's Revolutionary Party – Thongloun Sisoulith","South-eastern Asia"],
["Head of state of Latvia?","President – Edgars Rinkēvičs","Northern Europe"],
["Head of government of Latvia?","Prime Minister – Andris Kulbergs","Northern Europe"],
["Head of state of Lebanon?","President – Joseph Aoun","Western Asia"],
["Head of government of Lebanon?","Prime Minister – Nawaf Salam","Western Asia"],
["Head of state of Lesotho?","King – Letsie III","Southern Africa"],
["Head of government of Lesotho?","Prime Minister – Sam Matekane","Southern Africa"],
["Who leads Liberia?","President – Joseph Boakai","Western Africa"],
["Head of state of Libya?","Chairman of the Presidential Council – Mohamed al-Menfi","Northern Africa"],
["Head of government of Libya?","Prime Minister – Abdul Hamid Dbeibeh","Northern Africa"],
["Head of state of Liechtenstein?","Prince Regnant – Hans-Adam II","Western Europe"],
["Head of government of Liechtenstein?","Prime Minister – Brigitte Haas","Western Europe"],
["Head of state of Lithuania?","President – Gitanas Nausėda","Northern Europe"],
["Head of government of Lithuania?","Prime Minister – Mindaugas Sinkevičius","Northern Europe"],
["Head of state of Luxembourg?","Grand Duke – Guillaume V","Western Europe"],
["Head of government of Luxembourg?","Prime Minister – Luc Frieden","Western Europe"],
["Who leads Madagascar?","President of the Council of the Presidency for the Re-Foundation of the Republic – Michael Randrianirina","Eastern Africa"],
["Who leads Malawi?","President – Peter Mutharika","Eastern Africa"],
["Head of state of Malaysia?","King – Sultan Ibrahim Iskandar","South-eastern Asia"],
["Head of government of Malaysia?","Prime Minister – Anwar Ibrahim","South-eastern Asia"],
["Who leads Maldives?","President – Mohamed Muizzu","Southern Asia"],
["Who leads Mali?","President – Assimi Goïta","Western Africa"],
["Head of state of Malta?","President – Myriam Spiteri Debono","Southern Europe"],
["Head of government of Malta?","Prime Minister – Robert Abela","Southern Europe"],
["Who leads Marshall Islands?","President – Hilda Heine","Micronesia"],
["Head of state of Mauritania?","President – Mohamed Ould Ghazouani","Western Africa"],
["Head of government of Mauritania?","Prime Minister – Mokhtar Ould Djay","Western Africa"],
["Head of state of Mauritius?","President – Dharam Gokhool","Eastern Africa"],
["Head of government of Mauritius?","Prime Minister – Navin Ramgoolam","Eastern Africa"],
["Who leads Mexico?","President – Claudia Sheinbaum","Central America"],
["Who leads Micronesia?","President – Wesley Simina","Micronesia"],
["Head of state of Moldova?","President – Maia Sandu","Eastern Europe"],
["Head of government of Moldova?","Prime Minister – Vasile Tofan","Eastern Europe"],
["Head of state of Monaco?","Sovereign Prince – Albert II","Western Europe"],
["Head of government of Monaco?","Minister of State – Christophe Mirmand","Western Europe"],
["Head of state of Mongolia?","President – Ukhnaagiin Khürelsükh","Eastern Asia"],
["Head of government of Mongolia?","Prime Minister – Nyam-Osoryn Uchral","Eastern Asia"],
["Head of state of Montenegro?","President – Jakov Milatović","Southern Europe"],
["Head of government of Montenegro?","Prime Minister – Milojko Spajić","Southern Europe"],
["Head of state of Morocco?","King – Mohammed VI","Northern Africa"],
["Head of government of Morocco?","Prime Minister – Aziz Akhannouch","Northern Africa"],
["Who leads Mozambique?","President – Daniel Chapo","Eastern Africa"],
["Who leads Myanmar?","President – Min Aung Hlaing","South-eastern Asia"],
["Who leads Namibia?","President – Netumbo Nandi-Ndaitwah","Southern Africa"],
["Who leads Nauru?","President – David Adeang","Micronesia"],
["Head of state of Nepal?","President – Ram Chandra Paudel","Southern Asia"],
["Head of government of Nepal?","Prime Minister – Balen Shah","Southern Asia"],
["Head of state of Netherlands?","King – Willem-Alexander","Western Europe"],
["Head of government of Netherlands?","Prime Minister – Rob Jetten","Western Europe"],
["Head of state of New Zealand?","King – Charles IIIGovernor-General – Dame Cindy Kiro","Australia and New Zealand"],
["Head of government of New Zealand?","Prime Minister – Christopher Luxon","Australia and New Zealand"],
["Who leads Nicaragua?","Co-Presidents – Daniel Ortega and Rosario Murillo","Central America"],
["Who leads Niger?","President of the National Council for the Safeguard of the Homeland – Abdourahamane Tchiani","Western Africa"],
["Who leads Nigeria?","President – Bola Tinubu","Western Africa"],
["Who leads North Korea?","General Secretary of the Workers' Party – Kim Jong Un","Eastern Asia"],
["Head of state of North Macedonia?","President – Gordana Siljanovska-Davkova","Southern Europe"],
["Head of government of North Macedonia?","Prime Minister – Hristijan Mickoski","Southern Europe"],
["Head of state of Norway?","King – Harald V","Northern Europe"],
["Head of government of Norway?","Prime Minister – Jonas Gahr Støre","Northern Europe"],
["Head of state of Oman?","Sultan – Haitham bin Tariq","Western Asia"],
["Head of government of Oman?","Prime Minister – Haitham bin Tariq","Western Asia"],
["Head of state of Pakistan?","President – Asif Ali Zardari","Southern Asia"],
["Head of government of Pakistan?","Prime Minister – Shehbaz Sharif","Southern Asia"],
["Who leads Palau?","President – Surangel Whipps Jr.","Micronesia"],
["Head of state of Palestine?","President – Mahmoud Abbas","Western Asia"],
["Head of government of Palestine?","Prime Minister – Mohammad Mustafa","Western Asia"],
["Who leads Panama?","President – José Raúl Mulino","Central America"],
["Head of state of Papua New Guinea?","King – Charles IIIGovernor-General – Sir Bob Dadae","Melanesia"],
["Head of government of Papua New Guinea?","Prime Minister – James Marape","Melanesia"],
["Who leads Paraguay?","President – Santiago Peña","South America"],
["Who leads Peru?","President – Keiko Fujimori","South America"],
["Who leads Philippines?","President – Bongbong Marcos","South-eastern Asia"],
["Head of state of Poland?","President – Karol Nawrocki","Eastern Europe"],
["Head of government of Poland?","Prime Minister – Donald Tusk","Eastern Europe"],
["Head of state of Portugal?","President – António José Seguro","Southern Europe"],
["Head of government of Portugal?","Prime Minister – Luís Montenegro","Southern Europe"],
["Head of state of Qatar?","Emir – Sheikh Tamim bin Hamad Al Thani","Western Asia"],
["Head of government of Qatar?","Prime Minister – Sheikh Mohammed bin Abdulrahman bin Jassim Al Thani","Western Asia"],
["Head of state of Romania?","President – Nicușor Dan","Eastern Europe"],
["Head of government of Romania?","Caretaker Prime Minister – Ilie Bolojan","Eastern Europe"],
["Head of state of Russia?","President – Vladimir Putin","Eastern Europe"],
["Head of government of Russia?","Prime Minister – Mikhail Mishustin","Eastern Europe"],
["Head of state of Rwanda?","President – Paul Kagame","Eastern Africa"],
["Head of government of Rwanda?","Prime Minister – Justin Nsengiyumva","Eastern Africa"],
["Head of state of Saint Kitts and Nevis?","King – Charles IIIGovernor-General – Dame Marcella Liburd","Caribbean"],
["Head of government of Saint Kitts and Nevis?","Prime Minister – Terrance Drew","Caribbean"],
["Head of state of Saint Lucia?","King – Charles IIIActing Governor-General – Felix Finisterre","Caribbean"],
["Head of government of Saint Lucia?","Prime Minister – Philip J. Pierre","Caribbean"],
["Head of state of Saint Vincent and the Grenadines?","King – Charles IIIGovernor-General – Sir Stanley John","Caribbean"],
["Head of government of Saint Vincent and the Grenadines?","Prime Minister – Godwin Friday","Caribbean"],
["Head of state of Samoa?","O le Ao o le Malo – Afioga Tuimalealiʻifano Vaʻaletoʻa Sualauvi II","Polynesia"],
["Head of government of Samoa?","Prime Minister – Laʻauli Leuatea Schmidt","Polynesia"],
["Head of state of San Marino?","Captains Regent – Alice Mina and Vladimiro Selva","Southern Europe"],
["Head of government of San Marino?","Secretary for Foreign and Political Affairs – Luca Beccari","Southern Europe"],
["Head of state of Sao Tome and Principe?","President – Carlos Vila Nova","Middle Africa"],
["Head of government of Sao Tome and Principe?","Prime Minister – Américo Ramos","Middle Africa"],
["Who leads Saudi Arabia?","Crown Prince – Mohammed bin Salman","Western Asia"],
["Head of state of Senegal?","President – Bassirou Diomaye Faye","Western Africa"],
["Head of government of Senegal?","Prime Minister – Ahmadou Al Aminou Lo","Western Africa"],
["Head of state of Serbia?","President – Aleksandar Vučić","Southern Europe"],
["Head of government of Serbia?","Prime Minister – Đuro Macut","Southern Europe"],
["Who leads Seychelles?","President – Patrick Herminie","Eastern Africa"],
["Who leads Sierra Leone?","President – Julius Maada Bio","Western Africa"],
["Head of state of Singapore?","President – Tharman Shanmugaratnam","South-eastern Asia"],
["Head of government of Singapore?","Prime Minister – Lawrence Wong","South-eastern Asia"],
["Head of state of Slovakia?","President – Peter Pellegrini","Eastern Europe"],
["Head of government of Slovakia?","Prime Minister – Robert Fico","Eastern Europe"],
["Head of state of Slovenia?","President – Nataša Pirc Musar","Southern Europe"],
["Head of government of Slovenia?","Prime Minister – Janez Janša","Southern Europe"],
["Head of state of Solomon Islands?","King – Charles IIIGovernor-General – Sir David Tiva Kapu","Melanesia"],
["Head of government of Solomon Islands?","Prime Minister – Matthew Wale","Melanesia"],
["Head of state of Somalia?","President – Hassan Sheikh Mohamud","Eastern Africa"],
["Head of government of Somalia?","Prime Minister – Hamza Abdi Barre","Eastern Africa"],
["Who leads South Africa?","President – Cyril Ramaphosa","Southern Africa"],
["Who leads South Korea?","President – Lee Jae Myung","Eastern Asia"],
["Who leads South Sudan?","President – Salva Kiir","Eastern Africa"],
["Head of state of Spain?","King – Felipe VI","Southern Europe"],
["Head of government of Spain?","Prime Minister – Pedro Sánchez","Southern Europe"],
["Who leads Sri Lanka?","President – Anura Kumara Dissanayake","Southern Asia"],
["Who leads Suriname?","President – Jennifer Geerlings-Simons","South America"],
["Head of state of Sweden?","King – Carl XVI Gustaf","Northern Europe"],
["Head of government of Sweden?","Prime Minister – Ulf Kristersson","Northern Europe"],
["Who leads Switzerland?","Federal Council","Western Europe"],
["Who leads Syria?","President – Ahmed al-Sharaa","Western Asia"],
["Head of state of Tajikistan?","President – Emomali Rahmon","Central Asia"],
["Head of government of Tajikistan?","Prime Minister – Qohir Rasulzoda","Central Asia"],
["Who leads Tanzania?","President – Samia Suluhu Hassan","Eastern Africa"],
["Head of state of Thailand?","King – Maha Vajiralongkorn","South-eastern Asia"],
["Head of government of Thailand?","Prime Minister – Anutin Charnvirakul","South-eastern Asia"],
["Head of state of Timor-Leste?","President – José Ramos-Horta","South-eastern Asia"],
["Head of government of Timor-Leste?","Prime Minister – Xanana Gusmão","South-eastern Asia"],
["Head of state of Togo?","President – Jean-Lucien Savi de Tové","Western Africa"],
["Head of government of Togo?","Prime Minister – Faure Gnassingbé","Western Africa"],
["Head of state of Tonga?","King – Tupou VI","Polynesia"],
["Head of government of Tonga?","Prime Minister – Fatafehi Fakafānua","Polynesia"],
["Head of state of Trinidad and Tobago?","President – Christine Kangaloo","Caribbean"],
["Head of government of Trinidad and Tobago?","Prime Minister – Kamla Persad-Bissessar","Caribbean"],
["Head of state of Tunisia?","President – Kais Saied","Northern Africa"],
["Head of government of Tunisia?","Prime Minister – Sara Zaafarani","Northern Africa"],
["Who leads Türkiye?","President – Recep Tayyip Erdoğan","Western Asia"],
["Who leads Turkmenistan?","Chairman of the People's Council – Gurbanguly Berdimuhamedow","Central Asia"],
["Head of state of Tuvalu?","King – Charles IIIGovernor-General – Sir Tofiga Vaevalu Falani","Polynesia"],
["Head of government of Tuvalu?","Prime Minister – Feleti Teo","Polynesia"],
["Who leads Uganda?","President – Yoweri Museveni","Eastern Africa"],
["Head of state of Ukraine?","President – Volodymyr Zelenskyy","Eastern Europe"],
["Head of government of Ukraine?","Prime Minister – Serhii Koretskyi","Eastern Europe"],
["Head of state of United Arab Emirates?","President – Sheikh Mohamed bin Zayed Al Nahyan","Western Asia"],
["Head of government of United Arab Emirates?","Prime Minister – Sheikh Mohammed bin Rashid Al Maktoum","Western Asia"],
["Head of state of United Kingdom?","King – Charles III","Northern Europe"],
["Head of government of United Kingdom?","Prime Minister – Andy Burnham","Northern Europe"],
["Who leads United States?","President – Donald Trump","Northern America"],
["Who leads Uruguay?","President – Yamandú Orsi","South America"],
["Head of state of Uzbekistan?","President – Shavkat Mirziyoyev","Central Asia"],
["Head of government of Uzbekistan?","Prime Minister – Abdulla Aripov","Central Asia"],
["Head of state of Vanuatu?","President – Nikenike Vurobaravu","Melanesia"],
["Head of government of Vanuatu?","Prime Minister – Jotham Napat","Melanesia"],
["Head of state of Vatican City?","Pope – Leo XIV","Southern Europe"],
["Head of government of Vatican City?","President of the Governorate – Sister Raffaella Petrini","Southern Europe"],
["Who leads Venezuela?","President – Nicolás Maduro","South America"],
["Who leads Vietnam?","General Secretary of the Communist Party – Tô Lâm","South-eastern Asia"],
["Head of state of Yemen?","President of the Presidential Leadership Council – Rashad al-Alimi","Western Asia"],
["Head of government of Yemen?","Prime Minister – Shaya al-Zindani","Western Asia"],
["Who leads Zambia?","President – Hakainde Hichilema","Eastern Africa"],
["Who leads Zimbabwe?","President – Emmerson Mnangagwa","Eastern Africa"]
].map(([front, back, category]) => ({ front, back, category }));
