/* ══════════════════════════════════════════════════════════════
   Business — built in the order it actually has to be learned.

   Words first. You cannot reason about a P&L while you are still
   translating it. Then how money moves, because every business
   decision is made inside those forces. Then reading a business,
   which needs both. Only then finding one, building one, funding one.

   Writing rule: the first sentence answers it in under 15 words.
   A second sentence only if it earns its place.
   ══════════════════════════════════════════════════════════════ */

export const PHASES = [
  { id: 'p0', name: 'The Language of Business',  short: 'Language',   blurb: 'The words, the acronyms, the line items. Everything else assumes these.' },
  { id: 'p1', name: 'How Markets Work',          short: 'Markets',    blurb: 'Scarcity, prices, incentives — the forces every decision happens inside.' },
  { id: 'p2', name: 'The Whole Economy',         short: 'Economy',    blurb: 'Money, growth, rates, cycles. The weather your business flies in.' },
  { id: 'p3', name: 'Reading a Business',        short: 'Reading',    blurb: 'Turning the statements into judgement. Needs the language and the economics.' },
  { id: 'p4', name: 'Finding Something Real',    short: 'Validation', blurb: 'A problem people pay for, proven before you build.' },
  { id: 'p5', name: 'Building the Business',     short: 'Building',   blurb: 'Model, price, moat, channel, operations.' },
  { id: 'p6', name: 'Funding and Scaling',       short: 'Scaling',    blurb: 'Valuation, terms, ownership, and repeating what works.' },
];

export const PRINCIPLES = [
  /* ═══════════ Phase 0 · The Language of Business ═══════════ */
  {
    id: 'balance-sheet-lines', phase: 'p0', title: 'Reading a balance sheet', builds: [],
    idea: 'A photograph of what a business owns and owes, on one day.',
    cards: [
      ['Balance sheet', 'What the business owns and owes at one moment.'],
      ['Assets', 'What the business owns or is owed.'],
      ['Liabilities', 'What the business owes someone else.'],
      ["Shareholders' equity", 'Assets minus liabilities. What is left for owners.'],
      ['Current assets', 'Cash, or anything becoming cash within a year.'],
      ['Fixed (non-current) assets', 'Things kept longer than a year — buildings, equipment, patents.'],
      ['Accounts receivable (AR)', 'Money customers owe you for work already done.'],
      ['Accounts payable (AP)', 'Money you owe suppliers for goods already received.'],
      ['Inventory', 'Goods bought or made and not yet sold.'],
      ['Goodwill', 'The premium paid above fair value when buying a company.'],
      ['Accrued liabilities', 'Costs incurred but not yet paid — wages, interest, tax.'],
      ['Deferred revenue', 'Cash taken for work not yet delivered. A liability, not income.'],
      ['Retained earnings', 'Profit kept in the business instead of paid out.'],
      ['Working capital', 'Current assets minus current liabilities.'],
      ['Book value', 'What the balance sheet says it is worth: assets minus liabilities.'],
      ['Depreciation vs amortisation', 'Depreciation spreads the cost of physical things; amortisation does it for intangibles.'],
      ['Why a balance sheet always balances', 'Every entry is recorded twice. Assets = liabilities + equity by construction.'],
    ],
  },
  {
    id: 'income-statement-lines', phase: 'p0', title: 'Reading an income statement', builds: ['balance-sheet-lines'],
    idea: 'A film of what was earned and spent over a period.',
    cards: [
      ['Income statement (P&L)', 'What was earned and spent over a period, ending in profit or loss.'],
      ['Revenue (top line)', 'Everything billed, before any cost.'],
      ['COGS', 'Cost of goods sold — the direct cost of what you sold.'],
      ['Gross profit', 'Revenue minus COGS.'],
      ['SG&A', 'Selling, general and administrative — the overhead of running the place.'],
      ['R&D', 'Research and development — building what you sell next.'],
      ['Operating income (EBIT)', 'Profit from operations, before interest and tax.'],
      ['EBITDA', 'Earnings before interest, tax, depreciation and amortisation.'],
      ['Net income (bottom line)', 'What is left after every cost, including interest and tax.'],
      ['Gross margin', 'Gross profit ÷ revenue.'],
      ['Operating margin', 'Operating income ÷ revenue.'],
      ['Net margin', 'Net income ÷ revenue.'],
      ['EPS', 'Earnings per share — net income ÷ shares outstanding.'],
      ['Non-recurring item', 'A gain or cost that will not repeat. Strip it out before judging.'],
      ['Top line vs bottom line', 'Top line is revenue. Bottom line is net income.'],
      ['Why EBITDA is both popular and suspect', 'It compares operations across firms, and ignores the real cost of debt and equipment.'],
    ],
  },
  {
    id: 'cash-flow-lines', phase: 'p0', title: 'Reading a cash flow statement', builds: ['income-statement-lines'],
    idea: 'Where the money actually moved. Profit is an opinion; this is the receipt.',
    cards: [
      ['Cash flow statement', 'Actual cash in and out over a period, in three buckets.'],
      ['The three sections', 'Operating, investing, financing.'],
      ['Cash flow from operations', 'Cash generated by the core business.'],
      ['Cash flow from investing', 'Cash spent on or received from long-term assets.'],
      ['Cash flow from financing', 'Cash from raising or repaying capital, and dividends.'],
      ['CapEx', 'Capital expenditure — money spent on long-lived assets.'],
      ['OpEx', 'Operating expenditure — the day-to-day cost of running things.'],
      ['Free cash flow', 'Operating cash flow minus capital expenditure.'],
      ['Why net income and operating cash flow differ', 'Non-cash charges, and timing: receivables, payables, inventory.'],
      ['Liquidity', 'How easily something becomes cash without losing value.'],
      ['Solvency', 'Whether the business can meet its obligations long term.'],
      ['Insolvent', 'Unable to pay debts as they fall due, or owing more than you own.'],
    ],
  },
  {
    id: 'accounting-principles', phase: 'p0', title: 'How accounting decides what to record', builds: ['cash-flow-lines'],
    idea: 'A handful of conventions explain almost every number you will argue about.',
    cards: [
      ['GAAP', 'The US rulebook for financial reporting.'],
      ['IFRS', 'The reporting rulebook most of the rest of the world uses.'],
      ['Double-entry bookkeeping', 'Every transaction recorded twice — where value came from, where it went.'],
      ['Debit and credit, plainly', 'Two sides of one entry. Debits raise assets and expenses; credits raise liabilities, equity and income.'],
      ['Accrual accounting', 'Record revenue when earned and costs when incurred, whenever cash moves.'],
      ['Cash accounting', 'Record only when money actually moves.'],
      ['The matching principle', 'Put a cost in the same period as the revenue it produced.'],
      ['Revenue recognition', 'Revenue counts when the work is delivered, not when cash lands.'],
      ['Conservatism', 'When in doubt, book losses early and gains late.'],
      ['Going concern', 'The accounts assume the business still exists next year.'],
      ['Materiality', 'An error too small to change a decision can be ignored.'],
      ['Fiscal year', "A company's own 12-month reporting cycle. It need not match the calendar."],
      ['YoY', 'Year over year — this period against the same period last year.'],
      ['Audit', 'An independent check that the statements fairly represent reality.'],
      ['Write-off vs write-down', 'A write-off removes the value entirely; a write-down reduces it.'],
    ],
  },
  {
    id: 'business-acronyms', phase: 'p0', title: 'The acronyms you hear weekly', builds: ['accounting-principles'],
    idea: 'None are hard. Not knowing them is what slows the room down.',
    cards: [
      ['ROI', 'Return on investment — gain ÷ amount invested.'],
      ['ROE', "Return on equity — net income ÷ shareholders' equity."],
      ['ROA', 'Return on assets — net income ÷ total assets.'],
      ['ROIC', 'Return on invested capital — profit against all capital in the business.'],
      ['P/E ratio', 'Price ÷ earnings per share. What the market pays for a dollar of profit.'],
      ['KPI', 'Key performance indicator — the few numbers you manage by.'],
      ['ARR / MRR', 'Annual and monthly recurring revenue.'],
      ['CAC', 'Customer acquisition cost.'],
      ['LTV', 'Lifetime value of a customer, in gross margin.'],
      ['AOV', 'Average order value.'],
      ['NPS', 'Net promoter score — loyalty, from "would you recommend us?".'],
      ['TAM / SAM / SOM', 'Total market, the slice you can serve, the slice you can win.'],
      ['B2B / B2C', 'Selling to businesses, or to consumers.'],
      ['SaaS', 'Software sold as a subscription.'],
      ['MVP', 'Minimum viable product — the smallest build that tests the idea.'],
      ['CAGR', 'Compound annual growth rate — the smoothed yearly rate between two points.'],
      ['NPV', 'Net present value — future cash discounted to today, minus the cost.'],
      ['IRR', 'Internal rate of return — the discount rate where NPV is zero.'],
      ['WACC', "Weighted average cost of capital — the blended cost of a firm's debt and equity."],
      ['COGS vs OpEx', 'COGS is the cost of what you sold. OpEx is the cost of running the place.'],
    ],
  },
  {
    id: 'who-owns-what', phase: 'p0', title: 'Entities, roles and ownership', builds: ['business-acronyms'],
    idea: 'Who is liable, who decides, and who gets paid.',
    cards: [
      ['LLC', 'Limited liability company — owners are not personally liable for its debts.'],
      ['C-corp', 'Taxed separately from its owners. The standard for taking outside investment.'],
      ['S-corp', "Profits pass to owners' personal returns, avoiding double taxation."],
      ['Sole proprietorship', 'One person, no legal separation. The owner carries the liability.'],
      ['Limited liability, plainly', 'The most you can lose is what you put in.'],
      ['Equity', 'Ownership — a share of what is left after debts.'],
      ['Common vs preferred stock', 'Preferred is paid first and carries special rights. Common is what founders and staff hold.'],
      ['Dilution', 'Your ownership percentage shrinking as new shares are issued.'],
      ['Cap table', 'The record of who owns what.'],
      ['Vesting', 'Earning equity over time rather than all at once.'],
      ['Board of directors', 'Elected by shareholders to oversee the company and hire or fire the CEO.'],
      ['GP and LP', 'In a fund, the general partner runs it; limited partners supply the money.'],
      ['Shareholder vs stakeholder', 'A shareholder owns part of it. A stakeholder is anyone affected by it.'],
      ['Fiduciary duty', "A legal obligation to put someone else's interest before your own."],
      ['Due diligence', 'Verifying the claims before you commit.'],
    ],
  },

  /* ═══════════ Phase 1 · How Markets Work ═══════════ */
  {
    id: 'scarcity', phase: 'p1', title: 'Scarcity forces choice', builds: ['who-owns-what'],
    idea: 'Everything runs out. So every yes is a no to something else.',
    cards: [
      ['Opportunity cost', 'What you gave up to get it — the next-best thing you passed on.'],
      ['Why "free" is rarely free', 'It still costs your time, attention, and whatever you would have done instead.'],
      ['Sunk cost', 'Money or time already spent that you cannot get back.'],
      ['Why a sunk cost cannot change a decision', 'It is identical under every option ahead of you.'],
      ['Trade-off', 'Giving up one good thing to get another when you cannot have both.'],
      ['Scarcity, in one line', 'Unlimited wants, limited means. Every economic idea starts here.'],
      ['Economics, defined', 'The study of how people choose under scarcity.'],
    ],
  },
  {
    id: 'margin', phase: 'p1', title: 'Decisions happen at the margin', builds: ['scarcity'],
    idea: 'Real choices are almost never all-or-nothing. Ask about the next one.',
    cards: [
      ['Thinking at the margin', 'Judging the next unit: is the extra benefit worth the extra cost?'],
      ['Marginal cost', 'The cost of making one more.'],
      ['Marginal revenue', 'The revenue from selling one more.'],
      ['Why averages mislead', 'They include costs that will not change either way.'],
      ['Diminishing returns', 'Each extra unit of an input adds less than the one before.'],
      ['When to stop doing more', 'When marginal cost meets marginal benefit.'],
      ['Fixed vs variable cost', 'Fixed stays the same as volume changes. Variable grows with each unit.'],
      ['Sunk vs fixed cost', 'Fixed costs recur and can be changed over time. Sunk costs are already gone.'],
    ],
  },
  {
    id: 'supply-demand', phase: 'p1', title: 'Supply and demand find a price', builds: ['margin'],
    idea: 'Buyers want more when it is cheap. Sellers want to sell more when it is dear. Price is where they meet.',
    cards: [
      ['Law of demand', 'Price up, quantity bought down.'],
      ['Law of supply', 'Price up, quantity produced up.'],
      ['Market equilibrium', 'The price where amount for sale equals amount wanted.'],
      ['Shortage', 'People want more than is for sale, because the price is too low.'],
      ['Surplus', 'More is for sale than people want, because the price is too high.'],
      ['Demand shifting vs moving along the curve', 'Price moves you along it. Income, taste or substitutes shift the whole curve.'],
      ['Substitute good', 'Something buyers switch to when yours costs more.'],
      ['Complement good', 'Something bought alongside yours. Cheaper printers sell more ink.'],
      ['Normal vs inferior good', 'Normal goods sell more as income rises. Inferior goods sell less.'],
    ],
  },
  {
    id: 'elasticity', phase: 'p1', title: 'Elasticity: how much behaviour moves', builds: ['supply-demand'],
    idea: 'The single number that decides whether raising price makes you richer or poorer.',
    cards: [
      ['Elasticity of demand', 'How much quantity changes when price changes.'],
      ['Elastic demand', 'Buyers are price-sensitive. A small price rise loses a lot of volume.'],
      ['Inelastic demand', 'Buyers barely react. You can raise price and keep the volume.'],
      ['What makes demand inelastic', 'No good substitutes, urgency, or a small share of the budget.'],
      ['Elasticity and revenue', 'If demand is inelastic, raising price raises revenue. If elastic, it lowers it.'],
      ['Income elasticity', 'How much demand moves when incomes move.'],
      ['Why elasticity is the pricing question', 'It decides whether you win on price or on volume.'],
    ],
  },
  {
    id: 'prices', phase: 'p1', title: 'Prices are information', builds: ['elasticity'],
    idea: 'A price is a message about scarcity and desire. Jam the message and behaviour goes wrong.',
    cards: [
      ['What a rising price tells people', 'It is scarcer or more wanted. Buyers use less, producers make more.'],
      ['Price ceiling', 'A legal maximum price. Below market, it causes shortages and queues.'],
      ['Price floor', 'A legal minimum. Above market, it causes surpluses — including unemployed workers.'],
      ['Why incentives beat intentions', 'People respond to the payoff in front of them, not the goal on the poster.'],
      ['Why a long queue is a business failure', 'It is unpriced demand — given away in waiting time.'],
      ['Consumer surplus', 'The gap between what a buyer would have paid and what they did pay.'],
      ['Producer surplus', 'The gap between the price received and the lowest price a seller would accept.'],
      ['Deadweight loss', 'Value destroyed when a tax, cap or restriction stops trades that both sides wanted.'],
    ],
  },
  {
    id: 'competition', phase: 'p1', title: 'Market structure decides profit', builds: ['prices'],
    idea: 'How many sellers there are sets how much money is left on the table.',
    cards: [
      ['Perfect competition', 'Many sellers, identical product. Nobody sets price; profits go to near zero.'],
      ['Monopoly', 'One seller. It sets price, and output is lower than a market would produce.'],
      ['Oligopoly', 'A few large sellers, each watching the others.'],
      ['Monopolistic competition', 'Many sellers with differentiated products — restaurants, clothing brands.'],
      ['Why commodity markets have thin margins', 'Identical products mean the only lever is price.'],
      ['Barrier to entry', 'Anything that stops new competitors arriving — cost, licence, network, brand.'],
      ['Price taker vs price maker', 'A taker accepts the market price. A maker sets its own.'],
      ['What differentiation buys you', 'Pricing power. The less substitutable you are, the more you keep.'],
    ],
  },
  {
    id: 'behavior', phase: 'p1', title: 'People are predictably irrational', builds: ['prices'],
    idea: 'Real buyers are not calculators. The predictable ways they bend are worth knowing.',
    cards: [
      ['Loss aversion', 'Losing $100 hurts about twice as much as gaining $100 feels good.'],
      ['Anchoring', 'The first number heard drags judgement toward it.'],
      ['Framing', 'The same fact feels different depending on wording. "90% survive" beats "10% die".'],
      ['Endowment effect', 'You value something more once it is yours.'],
      ['Social proof', 'People copy others when unsure. Reviews sell.'],
      ['Sunk cost fallacy', 'Continuing because of what you already spent.'],
      ['Friction', 'Any extra step. People quit at small obstacles more than logic predicts.'],
      ['Present bias', 'Overweighting what happens now against what happens later.'],
    ],
  },
  {
    id: 'time-value', phase: 'p1', title: 'Money has a time value', builds: ['scarcity'],
    idea: 'A dollar today beats a dollar later, because today’s dollar can go to work.',
    cards: [
      ['Why a dollar today is worth more', 'You can use it meanwhile — and later money carries risk.'],
      ['Interest rate', 'The price of using money for a while.'],
      ['Compounding', 'Earning returns on your past returns.'],
      ['Discounting', 'Compounding backwards — what future money is worth today.'],
      ['Present value', 'What money arriving later is worth right now.'],
      ['Rule of 72', 'Divide 72 by the growth rate for years to double. At 8%, about 9 years.'],
      ['Why higher rates slow an economy', 'Borrowing costs more and saving pays more, so people buy and build less.'],
      ['Real vs nominal rate', 'Real is the nominal rate minus inflation. Only real returns buy more.'],
    ],
  },

  /* ═══════════ Phase 2 · The Whole Economy ═══════════ */
  {
    id: 'money-inflation', phase: 'p2', title: 'Money and inflation', builds: ['prices', 'time-value'],
    idea: 'Money is a claim on real stuff. More claims, same stuff, each claim buys less.',
    cards: [
      ['The three jobs of money', 'A way to pay, a way to store value, a way to keep score.'],
      ['Inflation', 'Prices rising across the board, so money buys less.'],
      ['Nominal vs real', 'Nominal is the number on the page. Real is after inflation.'],
      ['A 4% raise during 6% inflation', 'A 2% pay cut.'],
      ['Demand-pull vs cost-push inflation', 'Too much spending chasing too few goods, or inputs getting pricier.'],
      ['Who wins from unexpected inflation', 'Borrowers. They repay with money worth less.'],
      ['Deflation, and why it is feared', 'Falling prices. People delay buying, revenue falls, debts get heavier.'],
      ['Money supply', 'The total money in circulation. Central banks influence it.'],
      ['Velocity of money', 'How often a dollar changes hands. More velocity acts like more money.'],
      ['Purchasing power', 'What a unit of money actually buys.'],
    ],
  },
  {
    id: 'output', phase: 'p2', title: 'Output and growth', builds: ['money-inflation'],
    idea: 'A country lives on what it produces. Growth comes from producing more per hour.',
    cards: [
      ['GDP', 'The value of everything finished an economy produces in a period.'],
      ['Why only finished goods count', 'Counting the flour and the bread counts the same value twice.'],
      ['Real vs nominal GDP', 'Real strips out price changes, so it shows whether output actually grew.'],
      ['Productivity', 'Output per hour worked.'],
      ['Why productivity beats hours', 'More hours raises output once. More output per hour raises it forever.'],
      ['Drivers of long-run growth', 'Investment, technology, skills, and rules that let people keep the gains.'],
      ['What GDP misses', 'Unpaid work, who got the money, environmental damage, quality gains.'],
      ['GDP per capita', 'Output divided by population — the number that tracks living standards.'],
    ],
  },
  {
    id: 'cycles', phase: 'p2', title: 'Business cycles', builds: ['output'],
    idea: 'Economies do not grow in a straight line. They boom, overheat, shrink, recover.',
    cards: [
      ['The four phases', 'Expansion, peak, contraction, trough.'],
      ['Recession, rule of thumb', 'Two consecutive quarters of shrinking real GDP.'],
      ['Growth and unemployment', 'Opposite directions. Growing economies hire; shrinking ones cut.'],
      ['Leading indicator', 'Something that turns before the economy does — new orders, permits, the yield curve.'],
      ['Lagging indicator', 'Something that confirms afterwards — unemployment, profits.'],
      ['Why a recession is a decent time to start', 'Talent and space are cheap, incumbents retreat.'],
      ['Soft landing', 'Slowing an economy enough to cool inflation without causing a recession.'],
    ],
  },
  {
    id: 'interest-rates', phase: 'p2', title: 'Interest rates move everything', builds: ['cycles', 'time-value'],
    idea: 'One number reprices every asset, every loan, and every plan.',
    cards: [
      ['The policy rate', 'The short-term rate a central bank sets, which drags other rates with it.'],
      ['Why rates change asset prices', 'Higher rates discount future cash harder, so assets are worth less today.'],
      ['The yield curve', 'Interest rates plotted against how long the money is lent for.'],
      ['An inverted yield curve', 'Short rates above long ones. Historically a recession signal.'],
      ['Risk-free rate', 'What you earn with no credit risk — usually short government debt. Every other return is judged against it.'],
      ['Risk premium', 'The extra return demanded for taking on risk.'],
      ['How rates reach a startup', 'Safe assets pay more, so investors demand more, so valuations fall.'],
      ['Bond price and interest rate', 'They move in opposite directions.'],
    ],
  },
  {
    id: 'policy', phase: 'p2', title: 'Monetary vs fiscal policy', builds: ['interest-rates'],
    idea: 'Two levers, two different hands. One sets the price of money, the other spends and taxes.',
    cards: [
      ['Monetary policy, and who runs it', 'Setting rates and money supply. The Fed, in the US.'],
      ['Fiscal policy, and who runs it', 'Government spending and taxes. Congress, not the Fed.'],
      ["The Fed's dual mandate", 'Stable prices and maximum employment. The two often pull opposite ways.'],
      ['How raising rates fights inflation', 'Borrowing gets expensive, so spending falls and prices cool.'],
      ['Quantitative easing', 'A central bank buying bonds to push long rates down.'],
      ['Why policy works slowly', 'It takes a year or more to reach hiring and spending.'],
      ['Crowding out', 'Government borrowing raising rates and squeezing private investment.'],
    ],
  },
  {
    id: 'trade', phase: 'p2', title: 'Trade and exchange rates', builds: ['output'],
    idea: 'Countries trade for the same reason people do: both sides end up better off.',
    cards: [
      ['Comparative advantage', 'Do what you give up least to do, and trade for the rest.'],
      ['Absolute vs comparative advantage', 'Absolute is being better at it. Comparative is giving up less to do it. Trade follows comparative.'],
      ['Exchange rate', 'The price of one currency in another.'],
      ['A strong dollar and US exporters', 'It hurts them — their goods cost foreigners more.'],
      ['Tariff, and who pays it', 'A tax on imports. Domestic buyers pay through higher prices.'],
      ['Trade deficit', 'Importing more than you export. A fact, not automatically a problem.'],
      ['Why currencies move', 'Interest rates, inflation, and demand to invest in that country.'],
    ],
  },
  {
    id: 'capital-markets', phase: 'p2', title: 'How capital markets work', builds: ['interest-rates'],
    idea: 'Where savings meet ideas. Understand this and fundraising stops being mysterious.',
    cards: [
      ['A stock', 'A share of ownership in a company.'],
      ['A bond', 'A loan to a company or government, repaid with interest.'],
      ['Stock vs bond, in one line', 'A bond is owed to you. A stock makes you an owner.'],
      ['Primary vs secondary market', 'Primary is the company selling new shares. Secondary is investors trading with each other.'],
      ['Market capitalisation', 'Share price × shares outstanding. What the market says the equity is worth.'],
      ['Liquidity in a market', 'How easily you can buy or sell without moving the price.'],
      ['Diversification', 'Spreading bets so one failure cannot ruin you.'],
      ['Why higher returns demand higher risk', 'Investors must be paid to accept uncertainty, or they buy the safe thing instead.'],
      ['Index fund', 'A fund that simply holds the whole market, cheaply.'],
    ],
  },

  /* ═══════════ Phase 3 · Reading a Business ═══════════ */
  {
    id: 'statements', phase: 'p3', title: 'The three statements together', builds: ['cash-flow-lines', 'competition'],
    idea: 'Each one alone lies a little. Read together, they cannot.',
    cards: [
      ['How the statements link', 'Net income flows into retained earnings, and drives the top of the cash flow statement.'],
      ['Which statement shows if you can pay salaries', 'The cash flow statement, plus cash on the balance sheet.'],
      ['A profitable company with no cash', 'Customers pay late, or inventory ate it. Profit is a timing opinion; cash is a fact.'],
      ['A company with cash but no profit', 'It raised money or sold something. Cash can arrive without being earned.'],
      ['Capitalising vs expensing a cost', 'Capitalising moves it to the balance sheet and spreads it, raising this year’s profit.'],
      ['The first three things to check', 'Is revenue growing, is gross margin holding, is operating cash flow positive.'],
      ['Why growth can look like failure on paper', 'Growth spending hits the P&L now; the revenue it buys arrives later.'],
    ],
  },
  {
    id: 'ratios', phase: 'p3', title: 'Ratios that actually tell you something', builds: ['statements'],
    idea: 'A ratio turns a number into a judgement by giving it something to stand against.',
    cards: [
      ['Current ratio', 'Current assets ÷ current liabilities. Can it cover the next year.'],
      ['Quick ratio', 'Like the current ratio but excluding inventory — the harsher test.'],
      ['Debt-to-equity', 'Total debt ÷ equity. How much of the business is borrowed.'],
      ['Interest coverage', 'Operating income ÷ interest expense. How comfortably it services debt.'],
      ['Inventory turnover', 'How many times stock is sold and replaced in a year.'],
      ['Days sales outstanding', 'Average days to collect after a sale.'],
      ['Return on equity', "Net income ÷ shareholders' equity. What owners earn on their stake."],
      ['Why a ratio needs a comparison', 'Alone it means nothing. Compare to last year, or to rivals.'],
    ],
  },
  {
    id: 'margins', phase: 'p3', title: 'Margins and cost structure', builds: ['statements', 'margin'],
    idea: 'Not what you charge. What is left after delivering it.',
    cards: [
      ['Contribution margin', 'Price minus variable cost. What each sale contributes to fixed costs.'],
      ['Breakeven point', 'Fixed costs ÷ contribution margin per unit.'],
      ['Operating leverage', 'How much of your cost is fixed. High fixed cost swings profit hard both ways.'],
      ['Why software margins attract investors', 'The next copy costs almost nothing, so extra revenue is almost all profit.'],
      ['Gross margin vs contribution margin', 'Gross margin uses accounting COGS. Contribution margin uses only truly variable costs.'],
      ['Economies of scale', 'Cost per unit falling as volume rises.'],
      ['What a falling gross margin usually means', 'Discounting, or delivery costs rising faster than price.'],
    ],
  },
  {
    id: 'unit-economics', phase: 'p3', title: 'Unit economics', builds: ['margins'],
    idea: 'Shrink the business to one customer. If one loses money, a million lose more.',
    cards: [
      ['Unit economics', 'The money made and spent on a single customer or order.'],
      ['How is CAC calculated?', 'Sales and marketing spend ÷ new customers won.'],
      ['How is LTV calculated?', 'Gross margin per period × how long a customer stays.'],
      ['A healthy LTV:CAC ratio', 'About 3:1. Under 1:1 you lose money on every customer.'],
      ['CAC payback', 'Months of gross profit to earn back the cost of winning a customer.'],
      ['Why LTV must use margin, not revenue', 'The part spent delivering was never yours to keep.'],
      ['Churn', 'The rate customers leave.'],
      ['How churn caps LTV', 'Lifetime is roughly 1 ÷ churn. At 5% monthly, 20 months is your ceiling.'],
      ['Contribution margin per customer', 'What one customer adds after the costs that vary with serving them.'],
    ],
  },
  {
    id: 'cash', phase: 'p3', title: 'Cash flow and runway', builds: ['statements'],
    idea: 'Companies rarely die of being unprofitable. They die of running out of cash on a Tuesday.',
    cards: [
      ['Burn rate', 'How much cash you lose per month.'],
      ['Runway', 'Cash ÷ monthly burn. Months until empty.'],
      ['Working capital, in practice', 'The cash tied up in operating day to day.'],
      ['How growth causes a cash crisis', 'You pay for stock and staff first; customers pay later.'],
      ['Cash conversion cycle', 'Days from paying for inventory to collecting from the customer.'],
      ['Three ways to extend runway without layoffs', 'Collect faster, pay slower, charge annually upfront.'],
      ['Default alive', 'At current growth and burn, you reach profit before the money runs out.'],
    ],
  },
  {
    id: 'capital', phase: 'p3', title: 'Debt, equity and the cost of capital', builds: ['cash', 'capital-markets'],
    idea: 'Money has a price. Which kind you take decides who gets paid and who decides.',
    cards: [
      ['Debt vs equity', 'Debt is borrowed and repaid with interest. Equity is sold and never repaid.'],
      ['Which is cheaper, and why', 'Debt. Lenders take less risk and are paid first, so they accept less.'],
      ['Cost of capital', 'The return you must earn to justify the money used.'],
      ['Financial leverage', 'Using borrowed money to amplify returns — and losses.'],
      ['When debt fits', 'When cash flow is predictable enough to service it.'],
      ['When debt is dangerous', 'When revenue is lumpy. Interest is due whether or not the month went well.'],
      ['Covenant', 'A condition in a loan. Breaking one can make the whole loan due.'],
      ['Bootstrapping, in cost-of-capital terms', 'The most expensive capital in time, the cheapest in ownership.'],
    ],
  },
  {
    id: 'kpis', phase: 'p3', title: 'Reading the numbers in practice', builds: ['unit-economics', 'ratios'],
    idea: 'A dashboard full of numbers is not insight. A few ratios over time is.',
    cards: [
      ['What makes a metric actionable', 'Someone can change it with a decision this week.'],
      ['Vanity metric', 'One that only goes up and changes no decision — total signups, cumulative downloads.'],
      ['Cohort', 'A group defined by when they started.'],
      ['Why a cohort chart beats a totals chart', 'Totals hide churn. Cohorts show whether people stay.'],
      ['Leading vs lagging metric', 'Leading moves before the outcome. Lagging confirms it after.'],
      ['The danger of averages', 'They hide the distribution. 5% of users can be 80% of revenue.'],
      ['Three numbers a small business should know weekly', 'Cash in the bank, gross margin, sales booked.'],
    ],
  },
  /* ═══════════ Phase 4 · Finding Something Real ═══════════ */
  {
    id: 'pain', phase: 'p4', title: 'Find a monetizable pain', builds: ['unit-economics'],
    idea: 'Start with a problem people already pay for or suffer through.',
    cards: [
      ['Why start with the problem', 'A solution is only good relative to a problem someone actually has.'],
      ['Painkiller or vitamin', 'A painkiller fixes something that hurts now. A vitamin waits forever.'],
      ['What makes a pain monetizable', 'Someone with a budget already spends on it, and you can find them.'],
      ['Workaround, and why it matters', 'A hack people built themselves. It proves the pain and shows what to replace.'],
      ['What kills most startups', 'Building something nobody needs.'],
      ['Sizing a market bottom-up', 'Count the people with the problem, multiply by what they already spend.'],
      ['Why top-down market sizing misleads', 'A percentage of a huge number is a wish, not a plan.'],
    ],
  },
  {
    id: 'discovery', phase: 'p4', title: 'Customer discovery', builds: ['pain', 'behavior'],
    idea: 'You cannot learn what people need by asking if they like your idea.',
    cards: [
      ['The rule of The Mom Test', 'Ask about their life, not your idea.'],
      ['Three questions that give useless answers', '"Would you buy this?" "Is this a good idea?" "What would you pay?"'],
      ['A better version of "Would you use this?"', '"Tell me about the last time you had this problem. What did you do?"'],
      ['Early adopter', 'Someone whose pain is bad enough that they already tried to fix it.'],
      ['Why target early adopters first', 'They tolerate a rough product and tell you the truth.'],
      ['Customer segment', 'A group with the same problem you can reach the same way.'],
      ['How many interviews before trusting a pattern', '10 to 20 in one segment. Stop when they stop surprising you.'],
    ],
  },
  {
    id: 'demand', phase: 'p4', title: 'Test demand, not opinions', builds: ['discovery'],
    idea: 'Enthusiasm is free. Make the test cost them something real.',
    cards: [
      ['Strong signal vs weak signal', 'What it cost them. Money and time are strong. Compliments are free.'],
      ['Falsifiable hypothesis', 'A prediction specific enough to fail — metric, number, deadline, written first.'],
      ['Smoke test', 'Selling it before you build it, and counting who clicks buy.'],
      ['Concierge MVP', 'Doing it by hand for a few customers before automating.'],
      ['The strongest proof of demand', 'Someone paying before the product exists.'],
      ['Confirmation bias, and the defence', 'Only noticing evidence you are right. Write down what would kill the idea first.'],
      ['Why surveys are weak evidence', 'They measure what people say when saying it costs nothing.'],
    ],
  },
  {
    id: 'pmf', phase: 'p4', title: 'Product-market fit', builds: ['demand', 'unit-economics'],
    idea: 'Fit is not a feeling. It shows up as people staying and pulling.',
    cards: [
      ['Product-market fit', 'A good market with a product that satisfies it. Demand pulls harder than you push.'],
      ['The best number for fit', 'Retention. Does the cohort curve flatten instead of falling to zero.'],
      ['The 40% test', 'Ask how users would feel if it vanished. Over 40% "very disappointed" suggests fit.'],
      ['Three signs you do not have fit', 'Usage needs nudging, deals need heroics, churn eats new sales.'],
      ['Why scaling before fit is dangerous', 'You multiply a broken model and burn the cash needed to fix it.'],
      ['Pivot', 'Changing approach while keeping what you learned.'],
      ['Nail it then scale it', 'Prove one repeatable, profitable way to win a customer. Only then pour money on it.'],
    ],
  },

  /* ═══════════ Phase 5 · Building the Business ═══════════ */
  {
    id: 'revenue-model', phase: 'p5', title: 'How you make money', builds: ['pmf', 'margins'],
    idea: 'The revenue model decides your cash timing, your customers, and your rivals.',
    cards: [
      ['Business model', 'How you create value, deliver it, and keep some as cash.'],
      ['Five revenue models', 'Subscription, per-sale, marketplace take rate, usage-based, advertising.'],
      ['Why recurring revenue is worth more', "Last year's customers still pay, so it stacks and is predictable."],
      ['The chicken-and-egg problem', 'A marketplace needs each side to attract the other. Subsidise one first.'],
      ['Take rate', 'The cut a marketplace keeps on each transaction.'],
      ['What freemium needs to work', 'Nearly free to serve free users, and a clear reason to upgrade.'],
      ['Gross margin by model', 'Software is high, marketplaces are high on the take, hardware and services are low.'],
    ],
  },
  {
    id: 'pricing', phase: 'p5', title: 'Pricing and value capture', builds: ['revenue-model', 'elasticity'],
    idea: 'Price to the value they get, not the cost you paid. It is the fastest lever you own.',
    cards: [
      ['Value-based pricing', 'Charging based on what it is worth to the customer.'],
      ['What is wrong with cost-plus pricing', 'It caps you at your own costs and ignores what people would pay.'],
      ['Willingness to pay', 'The most a customer would hand over rather than go without.'],
      ['Why price is the strongest profit lever', 'A 1% price rise costs nothing extra. A 1% volume rise does.'],
      ['Why have pricing tiers', 'Different customers value it differently. Tiers let each pay nearer their number.'],
      ['Price discrimination, legitimately', 'Charging segments differently — student rates, enterprise tiers, usage bands.'],
      ['Nobody objects to your price. What does that mean?', 'You are too cheap.'],
    ],
  },
  {
    id: 'moats', phase: 'p5', title: 'Moats and defensibility', builds: ['revenue-model', 'competition'],
    idea: 'Profit attracts copycats. You keep only what they cannot copy.',
    cards: [
      ['Moat', 'Something that stops competitors taking your profits.'],
      ['Network effects', 'Every new user makes it better for the others.'],
      ['Switching costs', 'The time, money and hassle of leaving you.'],
      ['Economies of scale as a moat', 'Bigger volume, lower unit cost. The leader can price where others cannot survive.'],
      ['Counter-positioning', 'Doing it a way the incumbent cannot copy without wrecking its own business.'],
      ['Why great technology is rarely a moat', 'Code is copyable and engineers are hireable.'],
      ['When a brand is a moat', 'When the name alone makes people trust it enough to skip comparing.'],
    ],
  },
  {
    id: 'frameworks', phase: 'p5', title: 'Frameworks for sizing up a market', builds: ['moats'],
    idea: 'Borrowed lenses. Each asks a question you would otherwise forget.',
    cards: [
      ["Porter's five forces", 'Rivalry, new entrants, substitutes, supplier power, buyer power.'],
      ['The most underrated force', 'Buyer power. A few big customers quietly set your price.'],
      ['Jobs to be done', 'People "hire" a product to get a job done. Ask what yours is hired for.'],
      ['The classic jobs-to-be-done example', 'Nobody wants a drill. They want a hole. Actually, they want the shelf up.'],
      ['Value chain', 'Every step from raw input to customer. Useful for finding where profit sits.'],
      ['Positioning', 'The one thing you want to own in a customer’s head.'],
      ['Strategy, in one line', 'Choosing which customer, what value, how delivered — and saying no to the rest.'],
    ],
  },
  {
    id: 'gtm', phase: 'p5', title: 'Go-to-market', builds: ['pricing', 'unit-economics'],
    idea: 'Distribution is not what happens after you build. Price decides what selling you can afford.',
    cards: [
      ['Go-to-market strategy', 'The repeatable way a specific customer finds you, decides, and buys.'],
      ['Why price must match the sales motion', 'A salesperson costs more than a small contract can repay.'],
      ['Channel-market fit', 'Reaching customers where they already are, the way they already buy.'],
      ['Why measure CAC per channel', 'A blended number hides that one prints money and another burns it.'],
      ['Funnel vs loop', 'A funnel pours people in with spend. A loop turns each customer into the next.'],
      ['Beachhead strategy', 'Win one narrow segment completely, then use it to take the next.'],
      ['Why channels stop working as you grow', 'You use up the cheap audience and the price of attention rises.'],
    ],
  },
  {
    id: 'selling', phase: 'p5', title: 'Selling and negotiating', builds: ['gtm'],
    idea: 'Selling is diagnosis before prescription. Negotiating is knowing your alternative.',
    cards: [
      ['The most common sales mistake', 'Talking. Pitching before understanding what the buyer is fixing.'],
      ['Qualified lead', 'Someone with the problem, the budget, the authority, and a reason to act now.'],
      ['BANT', 'Budget, Authority, Need, Timeline.'],
      ['Sales pipeline', 'Deals grouped by stage with probabilities. It forecasts revenue and shows where deals die.'],
      ['A full pipeline that never closes', 'No urgency. Find the cost of waiting or disqualify.'],
      ['BATNA', 'Best alternative to a negotiated agreement — what you do if this dies.'],
      ['Why BATNA is the whole game', 'Power comes from being able to leave, not from arguing well.'],
      ['Positions vs interests', 'Positions are what each side demands. Interests are why. Different interests can both be met.'],
      ['"Your price is too high" — first move', 'Ask what they are comparing it to.'],
    ],
  },
  {
    id: 'operations', phase: 'p5', title: 'Operations and delivery', builds: ['margins'],
    idea: 'Strategy is what you promise. Operations is whether you can keep promising it.',
    cards: [
      ['Bottleneck', 'The slowest step. It sets the pace of the whole system.'],
      ['Why improving a non-bottleneck is wasted', 'Output is capped by the bottleneck. Everything else just queues.'],
      ['Throughput', 'Finished units per unit of time.'],
      ['Inventory, in cash terms', 'Money already spent, sitting on a shelf.'],
      ['Just-in-time, and its risk', 'Minimal stock, restocked on demand. Frees cash, breaks under disruption.'],
      ['Why catching a defect early is cheaper', 'At the source it costs one step. After delivery it costs the rework and the customer.'],
      ['Why 100% capacity utilisation is a warning', 'No slack, so any hiccup becomes a delay everywhere.'],
    ],
  },
  {
    id: 'uncertainty', phase: 'p5', title: 'Deciding under uncertainty', builds: ['behavior', 'margin'],
    idea: 'You never have enough information. Judge the bet, not the outcome.',
    cards: [
      ['Expected value', 'Each outcome times its probability, added up.'],
      ['Resulting', 'Judging a decision by how it turned out. Good decisions lose sometimes.'],
      ['Base rate', 'How often something happens across all similar cases. Start there.'],
      ['Asymmetric bet', 'Small capped downside, large uncapped upside. Worth taking at low odds.'],
      ['One-way door decision', 'One you cannot reverse. Slow down for those, move fast on the rest.'],
      ['Survivorship bias', 'You only hear from the winners. The same strategy may have killed a hundred others.'],
      ['Why expected value is not enough alone', 'A bet you cannot survive losing is a bad bet at any odds.'],
    ],
  },

  /* ═══════════ Phase 6 · Funding and Scaling ═══════════ */
  {
    id: 'valuation', phase: 'p6', title: 'Valuation basics', builds: ['time-value', 'unit-economics', 'capital-markets'],
    idea: 'A company is worth the cash it will throw off, adjusted for time and risk.',
    cards: [
      ['Pre-money vs post-money', 'Pre-money is the value before the investment. Post is pre plus the money.'],
      ['Raise $2M at an $8M pre-money — what do investors own?', '20%. $2M of a $10M post-money.'],
      ['Is dilution bad?', 'Not by itself. A smaller slice of a much bigger pie is the point.'],
      ['Valuation multiple', 'Pricing a company as a multiple of revenue, ARR or profit.'],
      ['Discounted cash flow', 'Project future cash, discount it back to today.'],
      ['Why early valuations ignore DCF', 'There is no cash to discount. Price comes from team, market and competition among investors.'],
    ],
  },
  {
    id: 'venture', phase: 'p6', title: 'How venture capital works', builds: ['valuation'],
    idea: 'A fund has its own math. Understand it and every question in the room makes sense.',
    cards: [
      ["Where a VC's money comes from", 'Limited partners — pensions, endowments, family offices.'],
      ['The power law', 'A tiny handful of investments pay for everything else.'],
      ['Why VCs ask "how big can this get?"', 'A 2x winner cannot cover the ones that go to zero.'],
      ['2 and 20', 'About 2% a year in management fees, plus 20% of profits.'],
      ['When venture capital is the wrong fit', 'A steadily profitable business that will never be huge.'],
      ['What changes between seed and Series A', 'Seed buys the team and idea. Series A buys evidence it repeats.'],
      ['Dry powder', 'Committed capital a fund has not yet invested.'],
    ],
  },
  {
    id: 'terms', phase: 'p6', title: 'Term sheets', builds: ['venture'],
    idea: 'Valuation is the headline. Control and preference are the story.',
    cards: [
      ['SAFE', 'Money now that turns into shares at the next priced round.'],
      ['Valuation cap', 'The highest valuation at which a SAFE converts.'],
      ['Liquidation preference', 'Who gets paid first in a sale. 1x non-participating is the founder-friendly normal.'],
      ['Participating preferred', 'Investor takes their money back AND shares the rest. Push back.'],
      ['Pro rata', 'The right to keep investing later to hold their percentage.'],
      ['Option pool shuffle', 'Carving the employee pool out of the pre-money, so founders eat the dilution.'],
      ['Two terms that matter more than valuation', 'Board seats and veto rights.'],
      ['Is a signed term sheet a done deal?', 'No. It is non-binding except exclusivity; diligence still has to clear.'],
    ],
  },
  {
    id: 'captable', phase: 'p6', title: 'Cap tables and dilution math', builds: ['terms'],
    idea: 'Ownership is arithmetic. Do it before the meeting.',
    cards: [
      ['What belongs on a cap table?', 'Every share, option and convertible — and who holds it.'],
      ['You own 100%. Seed takes 20%, Series A takes 25%. What is left?', '60%. 100% × 0.80 × 0.75.'],
      ['Why dilution multiplies rather than adds', 'Each round takes a share of what remains. Two 20% rounds leave 64%.'],
      ['Fully diluted ownership', 'Your percentage if every option and convertible converted today.'],
      ['$5M invested at $20M post is what ownership?', '25%.'],
      ['1x non-participating on $5M, company sells for $16M', '$5M — the greater of the preference or 25% of $16M.'],
      ['Same deal, participating preferred', '$7.75M — $5M back, then 25% of the remaining $11M.'],
      ['How founders make nothing on a decent exit', 'Preferences pay investors first. If the stack exceeds the price, common gets what is left.'],
    ],
  },
  {
    id: 'scale', phase: 'p6', title: 'Scaling operations', builds: ['gtm', 'cash', 'pmf'],
    idea: 'Scaling is repetition. Only repeat something you already proved.',
    cards: [
      ['What must be true before scaling', 'A repeatable, profitable way to win customers, and retention that holds.'],
      ['Growth vs scale', 'Growth adds revenue by adding as much cost. Scale adds revenue faster than cost.'],
      ['What breaks first when a company grows', 'Communication. What worked at 10 people fails around 40.'],
      ['Why hiring is the riskiest cost', 'It is the hardest to undo. Burn rises immediately, output slowly.'],
      ['Growth ceiling', 'When more spend stops producing more growth.'],
      ['Why churn hurts more as you grow', 'It is a percentage of a bigger base. Eventually departures cancel new sales.'],
    ],
  },
  {
    id: 'people', phase: 'p6', title: 'Hiring and equity compensation', builds: ['scale'],
    idea: 'Your first twenty hires are the company. Equity pays for people you cannot afford.',
    cards: [
      ['The standard vesting schedule', 'Four years, with a one-year cliff.'],
      ['Cliff', 'The minimum time before any equity vests. Leave before it and you get nothing.'],
      ['Strike price', 'The price an option lets you buy a share at.'],
      ['10,000 options at $1 strike, company sells at $6', '$50,000 before tax.'],
      ['Why "1% of the company" means nothing alone', 'Without valuation, dilution to come, and strike price, a percentage has no dollar meaning.'],
      ['The cost of a bad hire', 'Their salary, the work they broke, the replacement, and the good people who left.'],
      ['Why hire slowly and fire quickly', 'Hiring mistakes compound through the culture.'],
    ],
  },
  {
    id: 'org', phase: 'p6', title: 'Building the organisation', builds: ['people'],
    idea: 'Past a certain size the company is the product — a machine that decides without you.',
    cards: [
      ['Delegation, really', 'Handing over the decision, not just the task.'],
      ['Span of control', 'How many people report to one manager. Past about seven, quality drops.'],
      ['The first sign you need process', 'The same mistake happening twice in different corners.'],
      ['Culture, in practical terms', 'What gets rewarded and what gets tolerated. Not the poster.'],
      ['Why hire for the stage you are in', 'Big-company operators often need structure that does not exist yet.'],
      ['RACI', 'Responsible, Accountable, Consulted, Informed. It kills "I thought you had it".'],
      ['Why founder time becomes the bottleneck', 'Everything routes through the person who knows everything.'],
    ],
  },
  {
    id: 'exits', phase: 'p6', title: 'Exits and acquisitions', builds: ['valuation', 'captable'],
    idea: 'Companies are bought, not sold. Understand why a buyer buys.',
    cards: [
      ['The realistic exits', 'Acquisition, IPO, buyout, or paying the owners forever. Most are acquisitions.'],
      ['Why acquirers buy', 'Revenue, technology, a team, customers, or removing a threat. The reason sets the price.'],
      ['Acqui-hire', 'Buying a company mainly for its people.'],
      ['Strategic vs financial buyer', 'A strategic buyer pays for fit. A financial buyer pays off the numbers.'],
      ['Earn-out', 'Part of the price paid later if targets are hit.'],
      ['Why "keeping our options open" weakens a sale', 'Buyers pay more when they fear losing to another buyer.'],
      ['IPO, in one line', 'Selling shares to the public. A financing event, not a finish line.'],
    ],
  },
];

export const APPLIED = {
  /* ── Phase 1 ── */
  scarcity: [
    ['You spend a Saturday on a client job for $400. You would have earned $250 doing something else. What did the day really net you?', '$150. The alternative you gave up is part of the cost.'],
    ['You have already spent $30k on a product nobody wants. Finishing costs $10k more. What matters?', 'Only the $10k against what finishing is worth. The $30k is gone either way.'],
    ['Two projects, both good, one team. What is the real cost of picking the first?', 'Everything the second would have earned. That is the number to beat, not zero.'],
    ['A "free" partnership costs 10 hours a week. When is it too expensive?', 'When those hours would earn more elsewhere. Free of cash is not free of capacity.'],
    ['A subscription you forgot about costs $40/month. What is the annual cost of not cancelling?', '$480, plus whatever that money would have earned. Small recurring leaks compound.'],
    ['Why do businesses keep failing product lines alive?', 'Sunk cost and identity. The money spent and the story told both argue against admitting it.'],
  ],
  margin: [
    ['A hotel room costs $180/night to build and $15/night to clean. A guest offers $60 for tonight. Take it?', 'Yes. The build cost is sunk; $60 beats the $15 marginal cost, so it adds $45 tonight.'],
    ['When would you refuse that $60 room anyway?', 'If discounting trains regulars to wait for cheap rooms. The marginal sale can cost you the full-price ones.'],
    ['Your average cost per unit is $8 and marginal cost is $3. What price floor matters for one extra order?', '$3. Averages include costs that will not change with the order.'],
    ['You add a second delivery van. Revenue rises 20%, costs rise 35%. What does that tell you?', 'You are past the useful margin — the next unit costs more than it brings in.'],
    ['A salesperson costs $6k/month and brings in $9k of gross profit. Hire a second?', 'Only if the second finds similar customers. Marginal, not average — the easy accounts are already taken.'],
    ['Why is "we will make it up in volume" usually wrong?', 'If contribution margin is negative, every extra unit loses money. Volume multiplies the loss.'],
  ],
  'supply-demand': [
    ['A competitor exits and your prices rise. What moved?', 'Supply fell. Same demand, fewer sellers, higher equilibrium price.'],
    ['Your prices rise and you sell just as much. What does that tell you?', 'Demand is inelastic — you had pricing power you were not using.'],
    ['Demand for your product jumps every December. Is that a shift in demand or a move along the curve?', 'A shift. Price did not change; the season did.'],
    ['Concert tickets sell out in minutes and resell for triple. What does that say about the original price?', 'It was below equilibrium. The shortage and the resale market are the price signal you ignored.'],
    ['You raise price 10% and volume falls 25%. Was it worth it?', 'No. Revenue fell — demand was elastic. Check margin before concluding, but the direction is bad.'],
    ['Name two things that make your customers less price-sensitive.', 'No good substitute, and the purchase being small relative to what it protects or earns them.'],
  ],
  prices: [
    ['Rent control keeps rents below market. Predict three effects.', 'A shortage of units, less new building, and landlords under-maintaining what exists.'],
    ['A minimum wage above the market rate for a role. Predict the effect.', 'Fewer of those jobs, more automation, or more hours cut. The wage floor is a price floor.'],
    ['Your supplier raises prices 20% and says it is temporary. What does that signal?', 'Their input is scarce or demand rose. Temporary or not, it tells you to look for substitutes now.'],
    ['A company pays bonuses for closed deals only. What behaviour follows?', 'Deals get closed and customers get over-promised. You get what you pay for, including the part you did not want.'],
    ['Free shipping over $50 — what is that price signal doing?', 'Moving the anchor. It reframes the shipping cost as a reward for spending more.'],
    ['Why is a long queue a business failure, not a success sign?', 'It is unpriced demand. You are giving away in waiting time what you could capture in price or capacity.'],
  ],
  behavior: [
    ['Why does a $99 price beat $100 by more than a dollar?', 'The left digit anchors. Buyers read it as "ninety-something," not "one hundred."'],
    ['You offer three tiers and want most people on the middle one. How do you design the top tier?', 'Expensive enough to make the middle look reasonable. The top tier is a reference point as much as a product.'],
    ['A free trial requires a card up front. Which two biases is that using?', 'The endowment effect once they are using it, and friction — cancelling takes an action most will not take.'],
    ['Your checkout adds a fee on the final screen. Why does it cost you more sales than the same amount added earlier?', 'It breaks the anchor and reads as a loss. Loss aversion hits harder than the number justifies.'],
    ['Why does "8,000 businesses use this" outperform a list of features?', 'Social proof. Under uncertainty, people copy the crowd rather than evaluate.'],
    ['A sign-up form goes from six fields to three. What usually happens?', 'Conversion rises more than the three fields seem to justify. Small friction has outsized effects.'],
    ['Why is a small, certain discount often more persuasive than a large lottery-style prize?', 'Certainty is valued above expected value. People overweight small probabilities and still prefer the sure thing.'],
  ],
  'time-value': [
    ['$1,000 growing 10% a year for three years. What is it worth?', '$1,331. Each year compounds on the last, not on the original.'],
    ['At 6% annual growth, roughly how long to double?', '12 years. 72 ÷ 6.'],
    ['You can take $10,000 today or $11,000 in two years. Money earns 8%. Which?', 'Today. $10,000 at 8% for two years is $11,664.'],
    ['Why does a customer paying annually up front change your business, not just your cash?', 'You get a year of cash to spend on growth, and they are far less likely to churn mid-year.'],
    ['Why do savers get hurt when rates sit below inflation?', 'Their money grows in nominal terms and shrinks in real terms. The interest does not cover the price rise.'],
    ['You lend a friend $5,000 interest-free for five years. Inflation is 3%. What did that cost you?', 'Roughly $700 of purchasing power, plus everything the money could have earned.'],
  ],

  /* ── Phase 2 ── */
  'money-inflation': [
    ['Inflation is 4% and your investments returned 7%. What is your real return?', 'About 3%. The nominal return minus inflation.'],
    ['Your supplier holds prices flat during 5% inflation. What are they really doing?', 'Cutting their real price by 5% — and probably absorbing a margin hit they will claw back later.'],
    ['You signed a five-year fixed-rate loan and inflation runs hot. Good or bad for you?', 'Good. You repay with money worth less than what you borrowed.'],
    ['Why do menu prices lag inflation?', 'Changing prices costs effort and annoys customers, so businesses wait and then move in a jump.'],
    ['Inflation is 6% and you give a 6% raise. What did the employee gain?', 'Nothing in real terms. It is a hold, not a raise.'],
  ],
  output: [
    ['A country produces the same goods but prices rose 5%. What happened to nominal and real GDP?', 'Nominal GDP rose 5%; real GDP is flat. Nothing more was actually produced.'],
    ['Your team ships the same output with two fewer people. What rose?', 'Productivity — output per hour. That is the only kind of growth that lasts.'],
    ['Why can a country grow GDP and see living standards fall?', 'If population grows faster than output, GDP per person falls. Totals hide the per-head picture.'],
    ['A factory rebuilds after a flood and GDP rises. Is the country better off?', 'No. Replacing what was destroyed counts as activity but restores nothing that was not already there.'],
    ['Which raises long-run output more: everyone working an extra hour, or a tool that makes each hour 10% more productive?', 'The tool. Hours are capped; productivity compounds.'],
  ],
  cycles: [
    ['Building permits fall for three straight months. What are you being told?', 'A slowdown is likely coming. Permits lead construction, employment, and spending.'],
    ['Unemployment is still low but new orders are falling. Where are you in the cycle?', 'Likely near a peak. Orders lead; employment lags.'],
    ['Why should a business hold more cash going into a downturn?', 'Credit tightens exactly when revenue dips. Cash buys survival and cheap assets.'],
    ['What kinds of business hold up best in a recession?', 'Those selling necessities, repairs, and things that save customers money.'],
    ['Your industry booms for four years straight. What should that make you consider?', 'That the cycle is not repealed. Plan the downturn while the good times pay for it.'],
  ],
  policy: [
    ['The Fed raises rates 2 points. Trace it to your mortgage and your job.', 'Borrowing costs rise, housing and investment slow, hiring cools. Rates reach the real economy through credit.'],
    ['Rates rise. What happens to startup valuations, and why?', 'They fall. Safe assets pay more, so investors demand higher returns and pay less for risky future cash flows.'],
    ['Government spends heavily while the economy is already at full employment. Likely result?', 'Inflation rather than extra output. There is no spare capacity to absorb the demand.'],
    ['Why can a central bank cut rates and see nothing happen?', 'If nobody wants to borrow, cheaper credit changes little. Policy pushes on a string in a slump.'],
    ['Cutting rates helps borrowers. Who does it hurt?', 'Savers, retirees on fixed income, and anyone holding cash. Every policy has a losing side.'],
  ],
  trade: [
    ['You are better than your assistant at everything, including admin. Should you still delegate admin?', 'Yes. Comparative advantage — your hour is worth more on the work only you can do.'],
    ['The dollar strengthens 10%. What happens to a US exporter?', 'Their goods cost foreigners 10% more, so volume falls or margin does.'],
    ['A 25% tariff on imported steel. Who ultimately pays?', 'Domestic buyers, through higher prices — including manufacturers who use steel.'],
    ['Your supplier is overseas and your currency weakens. What happens to your margin?', 'It falls. Your inputs cost more in your own currency while your selling price has not moved.'],
    ['Why is a trade deficit not automatically bad?', 'It means you bought more than you sold, financed by capital coming the other way. The question is what you did with it.'],
  ],

  /* ── Phase 3 ── */
  statements: [
    ['Revenue $1M, COGS $300k, operating expenses $500k. What is gross margin and operating profit?', 'Gross margin 70%. Operating profit $200k.'],
    ['A company books a $200k sale in March and gets paid in June. When does it show up on each statement?', 'Income statement in March. Cash flow statement in June. That gap is working capital.'],
    ['Profit is $100k and cash fell $50k. Name two things that could explain it.', 'Receivables grew, or you bought inventory or equipment. Profit and cash move on different clocks.'],
    ['Which statement tells you if a business can pay salaries next month?', 'The cash flow statement, plus the cash on the balance sheet. Profit does not pay wages.'],
    ['A company capitalises a cost instead of expensing it. What happens to this year\'s profit?', 'It rises — the cost moves to the balance sheet and is spread over future years.'],
    ['Assets $800k, liabilities $500k. What is equity, and what does it mean?', '$300k. That is what owners would have left if everything sold at book value and debts were paid.'],
    ['Why can a growing, profitable company still go bankrupt?', 'It runs out of cash before the profit arrives. Insolvency is a cash event.'],
  ],
  margins: [
    ['You sell at $100, variable cost $60, fixed costs $20k/month. How many units to break even?', '500 units. $20,000 ÷ $40 contribution.'],
    ['Same business. What is profit at 800 units?', '$12,000. 800 × $40 = $32,000 contribution, minus $20,000 fixed.'],
    ['You cut price from $100 to $90 with $60 variable cost. How much more volume do you need to stand still?', 'A third more. Contribution drops from $40 to $30, so 4 units now do the work of 3.'],
    ['A 10% price rise with no volume loss, at 40% gross margin. What happens to gross profit?', 'It rises 25%. The extra price is pure margin.'],
    ['A restaurant and a software company both make $1M. Which is more fragile to a 15% revenue drop, and why?', 'The restaurant. High fixed costs mean profit falls much faster than revenue.'],
    ['Your gross margin fell from 55% to 48% while revenue grew. What are the two suspects?', 'Discounting to get the growth, or delivery costs rising. Both mean the growth cost more than it looks.'],
  ],
  'unit-economics': [
    ['You charge $50/month at 80% gross margin. CAC is $600. What is the payback period?', '15 months. $40 of monthly gross profit into $600.'],
    ['Monthly churn is 4%. What is the average customer lifetime?', '25 months. 1 ÷ 0.04.'],
    ['Same customer: $40/month margin, 25-month life, $600 CAC. What is LTV and the ratio?', 'LTV $1,000, so 1.67:1. Below the 3:1 benchmark — it works, barely.'],
    ['You spent $30k on marketing and won 60 customers. What is CAC?', '$500.'],
    ['Churn improves from 5% to 3% monthly. What happens to LTV?', 'It rises about 67%. Lifetime goes from 20 to 33 months on the same margin.'],
    ['Blended CAC is $400. Paid ads are $900 and referrals are $50. What should you do?', 'Grow referrals and fix or cut paid. The blend was hiding a channel that loses money.'],
    ['Why can a business with great LTV:CAC still be a bad business?', 'If payback takes three years, growth eats cash faster than the customers return it.'],
    ['Your CAC is fine but only for the first 100 customers. What should you expect next?', 'Rising CAC. The cheapest, most motivated buyers always come first.'],
  ],
  cash: [
    ['$400k in the bank, burning $50k/month, then you raise $600k. What is the runway?', '20 months. $1M ÷ $50k.'],
    ['Same company wants 24 months of runway. How much must burn fall to?', 'About $42k/month. $1M ÷ 24.'],
    ['You collect in 60 days and pay suppliers in 30. What does growth do to your cash?', 'Drains it. You fund a month of every sale, so faster growth digs a deeper hole.'],
    ['Which extends runway more: a 10% revenue rise or a 10% cost cut, at $100k revenue and $150k costs?', 'The cost cut — $15k against $10k. Cuts act on the bigger number and act immediately.'],
    ['You are offered 2% off for paying in 10 days instead of 30. Is it worth it?', 'Only if that cash is not doing more elsewhere — 2% for 20 days is a very high annualised return, so usually yes.'],
    ['Why do founders raise when they do not need money?', 'Terms are best when you have leverage. Raising with three months of runway left is negotiating from weakness.'],
  ],

  /* ── Phase 4 ── */
  pain: [
    ['A customer built a 12-tab spreadsheet to manage something. What have you found?', 'A validated problem and a specification. The spreadsheet shows exactly what to replace.'],
    ['"Everyone has this problem." Why is that a warning?', 'If everyone has it and nobody paid to solve it, it does not hurt enough. Narrow pain beats broad annoyance.'],
    ['How do you tell a vitamin from a painkiller in one question?', 'Ask what they do about it today. Painkillers already have a budget line or a workaround.'],
    ['5,000 clinics spend $400/month on a workaround. What is your realistic market?', '$24M a year of demonstrated spend — a bottom-up number you can defend.'],
    ['A prospect loves it but says "next quarter." What did you learn?', 'The pain is real but not urgent. No deadline means no deal.'],
  ],
  discovery: [
    ['Rewrite "Do you think people would pay for this?" into a question worth asking.', '"What have you paid for to solve this, and what did it cost you?"'],
    ['Ten interviews, everyone was positive, nobody has bought. What went wrong?', 'You asked about the idea, not their behaviour. Enthusiasm is free.'],
    ['A customer says "I would definitely use that." How do you test it in the same conversation?', 'Ask for something costly — a deposit, a pilot date, an intro to their boss.'],
    ['Why interview within one narrow segment before widening?', 'Patterns only appear when the people share a problem. Mixed segments give you noise.'],
    ['What does it mean when interviews stop surprising you?', 'You have found the pattern. Stop interviewing and start testing whether they will pay.'],
  ],
  demand: [
    ['Rank these: 200 email signups, 5 paid pre-orders, 40 survey yeses.', 'Pre-orders first by a distance, then signups, then the survey. Rank by what it cost them.'],
    ['Write a falsifiable version of "the landing page will do well."', '"At least 5% of 500 visitors click Buy within two weeks." A number, a threshold, a deadline.'],
    ['Your smoke test converts 0.4%. What have you learned?', 'Either the demand is not there or the message is wrong. Change one thing and rerun before concluding.'],
    ['Why does a concierge MVP beat building the product first?', 'You prove people want the outcome before paying to automate it — and you learn what to automate.'],
    ['A pilot customer wants it free "to test." How should you read that?', 'As a weak signal. Free pilots measure curiosity; a paid one measures need.'],
  ],
  pmf: [
    ['Cohort retention flattens at 40% after month three. Good or bad?', 'Good — a flattening curve means a core that keeps using it. The level matters less than the flattening.'],
    ['Retention decays to near zero by month six. What does that mean for growth spend?', 'Stop. You are filling a leaking bucket and paying for the water.'],
    ['Every deal closes only after the founder joins the call. What does that tell you?', 'No fit yet — you have founder-market fit, not product-market fit. It will not scale.'],
    ['Sales grow 20% a month and churn is 8% a month. What happens eventually?', 'Growth stalls. Churn compounds against a bigger base until it cancels new sales.'],
    ['You have fit in one segment and not another. What should you do?', 'Go deeper in the one that works. Fit is per-segment, and diluting focus loses the segment you had.'],
    ['Name the cheapest signal that you are losing fit.', 'Support tickets and cancellations telling the same story twice. Listen before the metrics move.'],
  ],

  /* ── Phase 5 ── */
  'revenue-model': [
    ['Same product sold once for $1,200 or monthly at $60. Which builds a more valuable company, and why?', 'The subscription. $720/year that recurs compounds and is valued at a higher multiple than one-off sales.'],
    ['A marketplace takes 15% and sellers start transacting off-platform. What is the fix?', 'Give them a reason to stay in it — payments, protection, discovery — or lower the take rate.'],
    ['Your free tier is 95% of usage and 2% convert. When is that fine, and when is it fatal?', 'Fine if serving free users costs almost nothing. Fatal if they consume real support or infrastructure.'],
    ['Why does usage-based pricing align you with the customer better than a flat fee?', 'You only get more when they get more. It also means your revenue falls when they have a bad quarter.'],
    ['You sell to consumers at $10/month and to businesses at $500/month. Which needs a salesperson?', 'Only the business one. A $10 product must sell itself.'],
  ],
  pricing: [
    ['Your software saves a customer $50k a year. What is wrong with pricing it at $200/month?', 'You are capturing 5% of the value you create. The customer pockets the rest.'],
    ['Costs are $40 and you price at $60 for a 50% markup. What is the flaw?', 'It ignores what the buyer would pay. Cost-plus caps you at your own inefficiency.'],
    ['At 30% net margin, which raises profit more: 5% more customers or a 5% price rise?', 'The price rise. Extra customers bring extra costs; extra price does not.'],
    ['Everyone accepts your quote immediately. What should you change?', 'Raise the price. Zero friction means you are under the market.'],
    ['Two segments value your product very differently. How do you capture both without one price?', 'Tiers, usage bands, or a version with fewer features. Let each self-select.'],
    ['You raise prices for new customers only. What is the trade-off?', 'You protect goodwill and revenue today, but you carry a legacy base at old economics forever.'],
  ],
  moats: [
    ['Two food delivery apps, same city, same prices. Where does the moat actually come from?', 'Density. More restaurants attract more diners, which attracts more restaurants — a local network effect.'],
    ['Your product stores three years of a customer\'s data. What moat is that?', 'Switching costs. Leaving means losing history and retraining the team.'],
    ['A competitor copies your feature in a month. What did you actually have?', 'A feature, not a moat. Ask what compounds instead — data, scale, network, or brand.'],
    ['Why can a big incumbent fail to copy a cheaper model?', 'Counter-positioning — copying it would cannibalise the profitable business they already have.'],
    ['You have the lowest costs in the industry. When does that stop being a moat?', 'When the advantage comes from effort rather than structure. Scale and process persist; hustle does not.'],
  ],
  frameworks: [
    ['One customer is 60% of your revenue. Which of the five forces should worry you?', 'Buyer power. They can set your price and your roadmap, and losing them ends you.'],
    ['An industry with no entry barriers and identical products. What happens to profits?', 'They get competed to near zero. Rivalry plus easy entry is the worst combination to enter.'],
    ['Apply jobs-to-be-done to a milkshake bought at 7am.', 'It is hired to make a boring commute bearable and to last. Its competitors are bananas and bagels, not other milkshakes.'],
    ['Where in a value chain does the profit usually sit?', 'At the step with the least competition and the most customer lock-in — often distribution or the brand, rarely manufacturing.'],
    ['Write a positioning statement in one sentence for a product you would sell.', 'For [specific customer] who [problem], we are the [category] that [single differentiator].'],
  ],
  gtm: [
    ['A $30/month product and a salesperson costing $8k/month. How many customers must they close monthly just to pay for themselves?', 'About 267 — and they must keep closing them. That price cannot fund human selling.'],
    ['Same salesperson selling a $20k contract. How many deals to justify the cost?', 'Roughly one every two months at full margin. This is what human selling is for.'],
    ['Facebook ads at $300 CAC, referrals at $40, conferences at $1,200. Where do you put the next dollar?', 'Referrals — but check whether they scale. The cheapest channel is often the smallest.'],
    ['Your CAC rose 60% in two quarters with the same spend. What is the likely cause?', 'Channel saturation or rising auction prices. The cheap audience is used up.'],
    ['Describe a growth loop for a document tool.', 'Users share documents with non-users, who must sign up to view, and some of them create their own.'],
    ['Why win one narrow segment completely before expanding?', 'References, word of mouth, and a product that fits deeply. Diluted focus wins nobody.'],
  ],

  /* ── Phase 6 ── */
  valuation: [
    ['A company with $2M ARR trades in a market paying 6x revenue. What is the implied value?', '$12M.'],
    ['Same company, but growing 15% a month rather than 15% a year. What changes?', 'The multiple. Growth rate drives it more than the revenue does.'],
    ['You raise $1M at a $4M pre-money. What percentage did you sell?', '20%. $1M of a $5M post-money.'],
    ['You need $1M and want to give up no more than 15%. What pre-money must you hold?', 'At least $5.67M. $1M ÷ 0.15 = $6.67M post.'],
    ['Why is a higher valuation not automatically the better deal?', 'It sets a bar the next round has to clear, and the terms attached may cost more than the dilution saved.'],
    ['A profitable business earns $500k a year and similar businesses sell at 4x earnings. What is it worth?', 'About $2M — and unlike a startup, that number comes from cash it actually produces.'],
  ],
  venture: [
    ['A $100M fund needs a 3x return. What must the portfolio produce?', '$300M — and with most investments failing, a couple of companies have to return the whole fund alone.'],
    ['Why will a VC pass on a business that will reliably be worth $30M?', 'It cannot return their fund. Good business, wrong instrument.'],
    ['You want to keep the company and take home profit. Which capital fits?', 'Revenue, a bank loan, or revenue-based financing. Venture requires an exit.'],
    ['A VC asks "how does this become a billion-dollar company?" What are they really asking?', 'Whether the market is big enough that their bet can pay for all the others.'],
    ['What does a seed investor buy that a Series A investor does not?', 'Belief. Seed buys the team and the insight; Series A buys evidence it repeats.'],
  ],
  terms: [
    ['You raise on a SAFE with a $8M cap. The next round prices at $20M. What happens?', 'You convert at the $8M cap, so you get a much better price than the new investors.'],
    ['A 2x participating preference on $10M invested, company sells for $40M. What do investors take?', '$20M first, then their share of the remaining $20M. Founders split what is left.'],
    ['Which is worse for a founder: a lower valuation with clean terms, or a higher one with a 2x participating preference?', 'Usually the high one. Preference stacks can eat the entire founder outcome in a modest exit.'],
    ['An investor asks for a 15% option pool created pre-money. What does that actually cost you?', 'The full 15% comes out of the existing shareholders — mostly you — before the investor buys in.'],
    ['Why do board seats matter more than a point of valuation?', 'The board can fire you, block a sale, and approve financings. Price is one moment; control is every moment after.'],
    ['A term sheet is signed. Is the deal done?', 'No. It is non-binding except for exclusivity — diligence still has to clear.'],
  ],
  scale: [
    ['One salesperson closes reliably; you hire five and results collapse. What was missing?', 'A repeatable process. You scaled a person, not a motion.'],
    ['Revenue doubles and support costs triple. What does that say about scaling?', 'You are growing, not scaling. Cost is rising faster than revenue.'],
    ['At what team size does informal coordination usually break?', 'Around 30 to 50. Past that, what everybody knew has to be written down.'],
    ['You add 12 people in a quarter and output falls. Why?', 'Onboarding consumes your best people, and communication paths grow faster than headcount.'],
    ['Sales add 100 customers a month, churn takes 100. What is the growth ceiling and how do you raise it?', 'You are at it. Only lowering churn moves it — more sales just cycles faster.'],
  ],
  org: [
    ['You are the bottleneck on every decision. What is the first fix?', 'Hand over decisions, not tasks. Delegating work while keeping approval changes nothing.'],
    ['A manager has 15 direct reports. What breaks first?', 'Coaching and quality of attention. Past about seven, people get managed by exception only.'],
    ['You say quality matters but ship on the date regardless. What is your actual culture?', 'Dates over quality. Culture is what gets rewarded, not what gets said.'],
    ['The same mistake happens twice in two teams. What does that call for?', 'Process — a checklist or a norm. One mistake is bad luck; two is a system.'],
  ],
};

/* Flat card list: base cards then applied ones, in phase order. */
export const CURRICULUM_CARDS = PRINCIPLES.flatMap((p) => {
  const phase = PHASES.find((x) => x.id === p.phase);
  const base = p.cards.map(([front, back]) => ({ front, back, category: phase.name, principle: p.id }));
  const applied = (APPLIED[p.id] || []).map(([front, back]) => ({ front, back, category: phase.name, principle: p.id }));
  return [...base, ...applied];
});
