/* Core Human Knowledge — the things that repay knowing.
   The test every card had to pass: would not knowing this make you
   misunderstand something you will actually meet? Trivia fails it. */

export const PHASES = [
  { id: 'k1', name: 'How to Know Things', blurb: 'Evidence, numbers and the traps. Put this first and every phase after it is worth more.' },
  { id: 'k2', name: 'The Physical World', blurb: 'Matter, energy, the Earth and the sky. What everyone half-knows and half gets wrong.' },
  { id: 'k3', name: 'Life and the Body', blurb: 'Cells, evolution, illness, and what to do when someone drops.' },
  { id: 'k4', name: 'How We Got Here', blurb: 'Turning points, not dates. Why the world is shaped the way it is.' },
  { id: 'k5', name: 'How People Organise', blurb: 'States, laws, rights, and the paperwork that runs an adult life.' },
  { id: 'k6', name: 'The Great Ideas', blurb: 'The handful of thoughts everything since has been arguing with.' },
  { id: 'k7', name: 'Belief and Meaning', blurb: 'What the major traditions hold, and what they built. Described, not judged.' },
  { id: 'k8', name: 'The Shared References', blurb: 'The metaphors everyone uses. Miss these and you miss half of what is said.' },
];

export const PRINCIPLES = [

  /* ══════════ 1 · How to Know Things ══════════ */
  {
    id: 'evidence', phase: 'k1', builds: [], title: 'What counts as evidence',
    idea: 'A claim is worth as much as the thing that would prove it wrong.',
    cards: [
      ["Falsifiability", "A claim that nothing could disprove is not a scientific claim."],
      ["Controlled experiment", "Change one thing, hold the rest still, compare against a group you did not change."],
      ["Control group", "The group that gets nothing, so you can tell what your treatment actually did."],
      ["Placebo effect", "People improve from believing they are treated. Real, measurable, and why controls exist."],
      ["Double-blind", "Neither subject nor researcher knows who got the real thing. Stops both fooling themselves."],
      ["Replication", "One result is a rumour. A result others reproduce is a finding."],
      ["Peer review", "Other experts check the work before publication. A filter, not a guarantee."],
      ["Anecdote vs data", "One vivid story outweighs a thousand rows in your head. That is the bug, not the feature."],
      ["Burden of proof", "It sits with whoever makes the claim, not with whoever doubts it."],
      ["Occam's razor", "Prefer the explanation needing the fewest new assumptions. A tiebreaker, not a proof."],
    ],
  },
  {
    id: 'cause', phase: 'k1', builds: ['evidence'], title: 'Correlation and cause',
    idea: 'Two things moving together is the beginning of a question, not the end of one.',
    cards: [
      ["Correlation vs causation", "Two things moving together does not mean one caused the other."],
      ["Confounding variable", "A hidden third thing driving both. Ice cream sales and drownings share summer."],
      ["Reverse causation", "You assumed A caused B. Check whether B caused A."],
      ["Why randomisation matters", "Assigning by coin flip breaks every hidden link between groups at once."],
      ["Natural experiment", "Chance splits people into groups for you — a policy change, a lottery, a border."],
      ["Regression to the mean", "Extremes drift back to average on their own. Whatever you did in between gets the credit."],
      ["Selection effect", "Who ended up in your sample decides your answer before you measure anything."],
      ["Survivorship bias", "Judging by the winners you can see, ignoring the losers you cannot."],
      ["Necessary vs sufficient", "Necessary: it cannot happen without it. Sufficient: it alone makes it happen."],
      ["Dose-response", "If more of the cause gives more of the effect, causation is likelier."],
    ],
  },
  {
    id: 'base', phase: 'k1', builds: ['cause'], title: 'Chance and base rates',
    idea: 'How common a thing was before you looked decides what your evidence means.',
    cards: [
      ["Base rate", "How common a thing is before you saw any evidence."],
      ["Base rate neglect", "Judging by how well a case fits the story while ignoring how rare it is."],
      ["Why a 99% accurate test can still be usually wrong", "If the disease is rare, most positives are false ones."],
      ["False positive", "The test says yes when the answer is no."],
      ["Independent events", "A coin has no memory. Past flips do not change the next one."],
      ["Gambler's fallacy", "Believing a run of losses makes a win due. It does not."],
      ["Law of large numbers", "More trials pull results towards the true rate. Few trials swing wildly."],
      ["Expected value", "Each outcome's value weighted by its chance. How to compare bets."],
      ["Tail risk", "Rare, enormous outcomes. Averages hide them; they decide the story."],
      ["Coincidences are expected", "In a big enough world, unlikely things happen constantly. To someone."],
    ],
  },
  {
    id: 'scale', phase: 'k1', builds: ['base'], title: 'Scale and orders of magnitude',
    idea: 'Most bad reasoning about the world is a failure to feel how big a number is.',
    cards: [
      ["A million vs a billion, in seconds", "A million seconds is 12 days. A billion is 32 years."],
      ["Order of magnitude", "A factor of ten. The unit that matters when quantities get large."],
      ["Why averages mislead", "One billionaire in a room makes everyone's average income enormous."],
      ["Median vs mean", "Median is the middle person. Mean is the total split evenly. They differ when a few are extreme."],
      ["Per capita", "Total divided by population. The only way to compare countries of different sizes."],
      ["Exponential growth", "Growth proportional to size. Slow-looking, then abruptly overwhelming."],
      ["Rule of 72", "Divide 72 by the growth rate to get the years to double. 6% doubles in twelve."],
      ["Compounding", "Growth on top of previous growth. The reason small rates over long times get absurd."],
      ["Fermi estimate", "Guess a big number by chaining rough guesses. Usually right to an order of magnitude."],
      ["Denominator blindness", "\"200 deaths\" means nothing until you ask: out of how many?"],
    ],
  },
  {
    id: 'numbers', phase: 'k1', builds: ['scale'], title: 'How numbers mislead',
    idea: 'The same true number can be arranged to argue either side.',
    cards: [
      ["Percent vs percentage point", "4% to 5% is one point — and a 25% increase. Headlines swap these constantly."],
      ["Relative vs absolute risk", "\"Doubles your risk\" is meaningless until you know it went from 1 in a million to 2."],
      ["Cherry-picked baseline", "Start the chart at the year that flatters you and any trend can be produced."],
      ["Truncated axis", "A y-axis that does not start at zero makes a small change look like a cliff."],
      ["Sample size", "Small samples produce extreme results by chance alone."],
      ["Margin of error", "The range the true answer probably sits in. A 2-point lead with a 3-point margin is a tie."],
      ["Statistical significance", "Unlikely to be chance alone. Says nothing about whether the effect is large or matters."],
      ["p-hacking", "Testing many things and reporting the one that came out. Guarantees a false finding."],
      ["Goodhart's law", "When a measure becomes a target, it stops being a good measure."],
      ["Survey wording", "How a question is phrased moves the answer more than most people believe."],
    ],
  },
  {
    id: 'traps', phase: 'k1', builds: ['numbers'], title: 'The reasoning traps',
    idea: 'These are not stupidity. They are the standard settings, and they run in you too.',
    cards: [
      ["Confirmation bias", "Seeking and believing what fits what you already think."],
      ["Availability heuristic", "Judging how likely something is by how easily an example comes to mind."],
      ["Anchoring", "The first number you hear drags every later estimate towards it."],
      ["Sunk cost fallacy", "Continuing because of what you already spent. Spent is spent."],
      ["Hindsight bias", "Once you know the outcome, it feels like it was always obvious."],
      ["Dunning-Kruger effect", "The less you know about a field, the less equipped you are to see it."],
      ["Fundamental attribution error", "Their failure is character. Yours was circumstances."],
      ["In-group bias", "Judging your own side's actions more generously. Universal, and invisible from inside."],
      ["Loss aversion", "Losing £100 hurts more than gaining £100 pleases. Roughly twice as much."],
      ["Motivated reasoning", "Deciding first, then recruiting the argument. It feels identical to thinking."],
      ["Halo effect", "Being good at one visible thing makes people assume you are good at others."],
      ["Status quo bias", "Whatever is already happening gets treated as the safe choice."],
    ],
  },
  {
    id: 'fallacy', phase: 'k1', builds: ['traps'], title: 'Bad arguments, named',
    idea: 'Naming a move is most of what it takes to stop falling for it.',
    cards: [
      ["Straw man", "Attacking a weaker version of the argument than the one that was made."],
      ["Ad hominem", "Attacking the person instead of the claim."],
      ["False dilemma", "Presenting two options when more exist."],
      ["Slippery slope", "Claiming one step must lead to a distant extreme, without showing the steps."],
      ["Appeal to authority", "An expert's say-so is evidence, not proof. Outside their field, barely that."],
      ["Appeal to nature", "Natural means occurring in nature. It does not mean safe or good."],
      ["Circular reasoning", "The conclusion is smuggled into the premise."],
      ["Whataboutism", "Answering a charge by pointing at someone else's. Changes the subject, settles nothing."],
      ["Motte and bailey", "Argue something bold, retreat to something obvious when challenged, then return."],
      ["Unfalsifiable claim", "Any evidence gets absorbed as further proof. That is the tell."],
    ],
  },
  {
    id: 'source', phase: 'k1', builds: ['fallacy'], title: 'Judging a source',
    idea: 'You cannot check everything yourself. Checking who is telling you is the next best thing.',
    cards: [
      ["Primary vs secondary source", "Primary: made at the time by someone there. Secondary: someone describing it later."],
      ["Conflict of interest", "Who funded it, and what would they have preferred to find?"],
      ["The single-study problem", "One study is a data point. Look for the review of all of them."],
      ["Systematic review", "A study of every study on a question. The strongest ordinary evidence there is."],
      ["Consensus", "Not a vote. It means the ways of being wrong have been tried and failed."],
      ["Expert vs pundit", "One is accountable to a field that can prove them wrong. The other is not."],
      ["Preprint", "Published before peer review. Faster, and not yet checked."],
      ["Why a correction matters", "A source that issues corrections is more trustworthy, not less."],
    ],
  },

  /* ══════════ 2 · The Physical World ══════════ */
  {
    id: 'matter', phase: 'k2', builds: ['source'], title: 'What things are made of',
    idea: 'Everything you have ever touched is a hundred-odd kinds of atom, arranged.',
    cards: [
      ["Atom", "The smallest piece of an element that is still that element."],
      ["What an atom is made of", "A nucleus of protons and neutrons, with electrons around it."],
      ["What makes an element", "The number of protons. Change it and you have a different element."],
      ["Isotope", "Same element, different number of neutrons. Some are radioactive."],
      ["Molecule", "Two or more atoms bonded together. Water is two hydrogen and one oxygen."],
      ["Why atoms bond", "They are chasing a stable arrangement of electrons."],
      ["The periodic table's logic", "Columns share chemical behaviour, because they share outer electrons."],
      ["Why matter feels solid", "Atoms are mostly empty space. What stops your hand is electrons repelling electrons."],
      ["States of matter", "Solid, liquid, gas, plasma — the same particles with more energy each time."],
      ["Radioactivity", "An unstable nucleus shedding particles or energy until it settles."],
      ["Half-life", "The time for half a radioactive sample to decay. Constant, whatever is left."],
    ],
  },
  {
    id: 'energy', phase: 'k2', builds: ['matter'], title: 'Energy and why it runs downhill',
    idea: 'Energy is never created or destroyed, and never quite as useful afterwards.',
    cards: [
      ["Energy", "The capacity to do work. It changes form; the total never changes."],
      ["First law of thermodynamics", "Energy cannot be created or destroyed, only converted."],
      ["Second law of thermodynamics", "Things spread out and even out. Order costs energy to maintain."],
      ["Entropy", "A measure of how spread out and disordered energy is. It only ever rises overall."],
      ["Why perpetual motion is impossible", "Every conversion loses usable energy as heat. There is no free loop."],
      ["Why time has a direction", "Entropy rising is the only physical law that tells past from future."],
      ["Heat vs temperature", "Temperature is how fast particles move. Heat is the energy that flows between things."],
      ["Conservation of momentum", "Mass times velocity is preserved in any collision. Why recoil exists."],
      ["E = mc²", "Mass is enormously concentrated energy. A little mass makes a great deal of it."],
      ["Power vs energy", "Energy is how much. Power is how fast you use it."],
      ["Why a fridge warms the room", "It moves heat out of the box and adds its own. Net, the kitchen gets hotter."],
    ],
  },
  {
    id: 'force', phase: 'k2', builds: ['energy'], title: 'Forces and motion',
    idea: 'Things keep doing what they were doing until something pushes them.',
    cards: [
      ["Newton's first law", "A thing keeps moving in a straight line unless a force acts on it."],
      ["Newton's second law", "Force equals mass times acceleration. Heavier things need more push."],
      ["Newton's third law", "Every force has an equal and opposite one. You push the ground; it pushes you."],
      ["Gravity", "Mass attracts mass. Weak, but it never cancels out, so at large scale it wins."],
      ["Why astronauts float", "Not absence of gravity — they are falling around the Earth continuously."],
      ["Orbit", "Falling towards something while moving sideways fast enough to keep missing it."],
      ["Friction", "The force resisting sliding. Without it you could neither walk nor stop."],
      ["Terminal velocity", "Falling speed where air resistance equals gravity. You stop accelerating."],
      ["Why a feather and a hammer fall together", "In a vacuum they do. Air resistance is the whole difference."],
      ["Centre of mass", "The single point a body behaves as if all its mass sits at."],
      ["Relativity, briefly", "Time and distance depend on how fast you are moving relative to what you measure."],
    ],
  },
  {
    id: 'waves', phase: 'k2', builds: ['force'], title: 'Light, sound and electricity',
    idea: 'Almost everything you sense arrives as a wave or a moving charge.',
    cards: [
      ["Electromagnetic spectrum", "Radio, microwave, infrared, visible, ultraviolet, X-ray, gamma. One phenomenon, different wavelengths."],
      ["Visible light", "The narrow band our eyes evolved to catch, because that is what the sun sends most of."],
      ["Why the sky is blue", "Air scatters short wavelengths most, and blue is short."],
      ["Why sunsets are red", "Low sun means more air to cross. The blue is scattered away before it reaches you."],
      ["Speed of light", "300,000 km a second, and the universe's speed limit for anything."],
      ["Light year", "A distance, not a time. How far light travels in a year."],
      ["Sound", "A pressure wave in a material. It cannot cross a vacuum."],
      ["Why you see lightning before hearing thunder", "Light arrives almost instantly. Sound takes about three seconds a kilometre."],
      ["Electric current", "A flow of charge, usually electrons, pushed by a voltage."],
      ["Voltage vs current", "Voltage is the push. Current is how much flows. Current is what harms you."],
      ["Why birds on power lines are fine", "Both feet are at the same voltage, so nothing flows through them."],
      ["Magnetism and electricity", "Each creates the other when it changes. That is motors, generators and radio."],
    ],
  },
  {
    id: 'earth', phase: 'k2', builds: ['waves'], title: 'The Earth underfoot',
    idea: 'The ground is not still. It is slabs, floating, colliding, on a timescale you cannot feel.',
    cards: [
      ["Plate tectonics", "Earth's crust is slabs drifting on hot rock. Their edges are where the drama is."],
      ["Why Africa and South America fit together", "They were joined. The Atlantic opened between them."],
      ["Earthquake", "Plates catch, strain builds, and the rock slips all at once."],
      ["Volcano", "Molten rock reaching the surface, usually where plates meet."],
      ["How mountains form", "Plates colliding and crumpling the crust upward."],
      ["Why the seasons happen", "Earth's tilt, not its distance from the sun."],
      ["Why the tilt matters", "Tilted towards the sun means longer days and a steeper angle. Both mean more heat."],
      ["Tides", "The moon's pull, stretching the oceans. Two bulges, so two high tides a day."],
      ["The water cycle", "Evaporate, condense, rain, run off, repeat. The same water, forever."],
      ["Earth's age", "About 4.5 billion years. Life for most of it, complex life only recently."],
      ["Fossil", "Remains turned to rock. Rare, so the record is a sample, not a census."],
      ["Deep time", "The idea that geological ages dwarf human ones. It is the hardest scale to feel."],
    ],
  },
  {
    id: 'climate', phase: 'k2', builds: ['earth'], title: 'Weather, climate and air',
    idea: 'Weather is what happens. Climate is what is likely to happen.',
    cards: [
      ["Weather vs climate", "Weather is today. Climate is the pattern over decades."],
      ["The greenhouse effect", "Some gases let sunlight in and trap the heat leaving. Without it Earth would freeze."],
      ["Why more carbon dioxide warms things", "It traps more of the outgoing heat. The mechanism has been understood since the 1850s."],
      ["The atmosphere's makeup", "Mostly nitrogen, about a fifth oxygen, traces of everything else."],
      ["Ozone layer", "High-altitude ozone absorbing ultraviolet. Damaged by CFCs, and recovering since they were banned."],
      ["Why wind blows", "Air moving from high pressure to low. Pressure differences come from uneven heating."],
      ["Jet stream", "A fast high-altitude river of air steering weather systems across continents."],
      ["Ocean currents", "Vast circulations moving heat around the planet. They set regional climate."],
      ["Why Britain is mild for its latitude", "Warm water carried north across the Atlantic."],
      ["Why deserts sit where they do", "Air that rose at the equator descends dry around 30 degrees north and south."],
    ],
  },
  {
    id: 'space', phase: 'k2', builds: ['climate'], title: 'The sky and its scale',
    idea: 'Almost every atom in you was made inside a star that died.',
    cards: [
      ["The solar system", "One star, eight planets, and a great deal of debris, nearly all in one plane."],
      ["Why the sun shines", "Hydrogen fusing into helium in the core, converting a little mass into a lot of energy."],
      ["Star lifecycle", "Collapse from gas, burn, swell, and either fade or explode. Big stars die fastest."],
      ["Supernova", "A massive star collapsing and exploding. It scatters the heavy elements it made."],
      ["Where your atoms came from", "Hydrogen from the Big Bang. Everything heavier was made in stars."],
      ["Black hole", "Mass packed so tight that nothing, not even light, escapes it."],
      ["Galaxy", "Hundreds of billions of stars bound by gravity. Ours is the Milky Way."],
      ["The Big Bang", "Everything expanded from an extremely hot dense state about 13.8 billion years ago."],
      ["Redshift", "Light stretched by things moving away. The evidence that the universe is expanding."],
      ["Why looking out is looking back", "Light takes time. Distant objects appear as they were, not as they are."],
    ],
  },
  {
    id: 'chem', phase: 'k2', builds: ['space'], title: 'The chemistry you meet',
    idea: 'A handful of reactions explains cooking, rust, batteries and breathing.',
    cards: [
      ["Chemical reaction", "Atoms rearranging into new molecules. The atoms themselves are unchanged."],
      ["Oxidation", "Losing electrons, usually to oxygen. Rust and fire are the same family."],
      ["Combustion", "Fuel plus oxygen, releasing heat and light. Fire is a fast oxidation."],
      ["Acid and base", "Acids give away hydrogen ions, bases accept them. They neutralise each other."],
      ["pH scale", "0 to 14, 7 is neutral. Each step is a factor of ten."],
      ["Catalyst", "Speeds a reaction without being consumed. Every enzyme in you is one."],
      ["Solution vs mixture", "In a solution one substance is evenly dissolved. A mixture keeps its parts."],
      ["Why oil and water separate", "Water molecules are polar and stick to each other. Oil is not invited."],
    ],
  },

  /* ══════════ 3 · Life and the Body ══════════ */
  {
    id: 'cell', phase: 'k3', builds: ['chem'], title: 'Cells and the code',
    idea: 'Every living thing is cells, and every cell runs on the same four-letter instruction set.',
    cards: [
      ["Cell", "The smallest unit that is alive. You are about thirty trillion of them."],
      ["DNA", "A molecule storing instructions in a four-letter code, copied every time a cell divides."],
      ["Gene", "A stretch of DNA that codes for something, usually a protein."],
      ["Protein", "The machines and structures of a cell. DNA is the instruction; protein does the work."],
      ["Chromosome", "DNA packaged for storage. Humans have 23 pairs."],
      ["Why offspring differ from parents", "Each parent gives half their DNA, shuffled, plus small copying errors."],
      ["Mutation", "A change in DNA. Mostly harmless, sometimes harmful, occasionally the raw material of evolution."],
      ["Why the same DNA makes different cells", "Different genes are switched on. A liver cell and a neuron read different pages."],
      ["Stem cell", "A cell that has not yet specialised, and can become several things."],
      ["Cancer, in one line", "Cells that have lost the instruction to stop dividing."],
    ],
  },
  {
    id: 'evo', phase: 'k3', builds: ['cell'], title: 'Evolution by natural selection',
    idea: 'What survives to reproduce becomes what is common. Nobody is steering.',
    cards: [
      ["Natural selection", "Traits that help survival and reproduction become more common. That is the whole mechanism."],
      ["What evolution is not", "It has no goal, no direction, and no plan for the future."],
      ["Fitness, in biology", "Not strength. How many surviving offspring you leave."],
      ["Why evolution needs deep time", "Tiny advantages compound over enormous numbers of generations."],
      ["Common descent", "All living things share ancestors. The evidence is written in shared DNA."],
      ["Vestigial structure", "A leftover from an ancestor with a use you no longer have."],
      ["Convergent evolution", "Unrelated species solving the same problem the same way. Eyes evolved many times."],
      ["Sexual selection", "Traits that win mates spread even when they cost survival. The peacock's tail."],
      ["Why antibiotic resistance happens", "Survivors of a treatment breed. You selected for them."],
      ["Why there is no 'higher' species", "Every living species is equally the product of the same length of evolution."],
    ],
  },
  {
    id: 'eco', phase: 'k3', builds: ['evo'], title: 'Living things together',
    idea: 'Nothing lives alone, and removing one part rarely removes only one thing.',
    cards: [
      ["Ecosystem", "Living things and their surroundings, treated as one interacting system."],
      ["Photosynthesis", "Plants turning sunlight, water and carbon dioxide into sugar and oxygen."],
      ["Food chain", "Energy passing up from plants to herbivores to predators, losing most of itself each step."],
      ["Why predators are rare", "Only about a tenth of the energy passes up each level. The top can only be thin."],
      ["Keystone species", "One whose removal collapses far more than its own share. Wolves, bees, sea otters."],
      ["Carbon cycle", "Carbon moving between air, life, ocean and rock. Burning fossil fuels shortcuts it."],
      ["Nitrogen fixing", "Turning air nitrogen into a form life can use. Bacteria did it before industry could."],
      ["Biodiversity", "Variety of life. It is what lets a system absorb a shock without collapsing."],
    ],
  },
  {
    id: 'body', phase: 'k3', builds: ['eco'], title: 'How your body runs',
    idea: 'A handful of systems, each with one job, and most illness is one of them failing at it.',
    cards: [
      ["What blood does", "Carries oxygen, fuel, heat, hormones and waste. The delivery and rubbish service."],
      ["What the heart does", "One pump, two circuits: one to the lungs for oxygen, one to everywhere else."],
      ["Blood pressure", "The force blood exerts on artery walls. Two numbers: heart squeezing, heart resting."],
      ["What lungs do", "Swap carbon dioxide out for oxygen in, across a surface the size of a tennis court."],
      ["What the liver does", "Processes everything absorbed from food, stores fuel and clears toxins."],
      ["What kidneys do", "Filter blood, keep water and salt in balance, and make urine from what is left."],
      ["What the brain runs on", "Glucose and oxygen, constantly. It is 2% of your weight and a fifth of your energy."],
      ["Nervous system", "Electrical signalling. The brain and spinal cord decide; nerves carry the message."],
      ["Hormone", "A chemical messenger in the blood, telling distant organs what to do."],
      ["Metabolism", "The total of the chemical reactions keeping you alive. Most of your energy goes on just existing."],
      ["Calorie", "A unit of energy, not a substance. It measures what food can give you."],
      ["Homeostasis", "Holding internal conditions steady — temperature, sugar, acidity — against the outside world."],
    ],
  },
  {
    id: 'germ', phase: 'k3', builds: ['body'], title: 'Germs and immunity',
    idea: 'The single idea that added most years to human life was that invisible organisms cause disease.',
    cards: [
      ["Germ theory", "Invisible organisms cause disease. The idea that made surgery survivable."],
      ["Why handwashing was revolutionary", "Doctors carried infection between patients. Washing halved deaths before anyone knew why."],
      ["Bacteria vs virus", "Bacteria are living cells. Viruses are instructions in a shell that hijack your cells."],
      ["Antibiotics vs viruses", "Antibiotics kill bacteria. They do nothing to a cold."],
      ["Why you must finish antibiotics", "Stopping early leaves the hardiest bacteria alive, and those are the ones that breed."],
      ["Immune system, in one line", "Learns what does not belong, remembers it, and kills it faster next time."],
      ["How a vaccine works", "Shows the immune system a harmless version, so the real thing meets a prepared defence."],
      ["Herd immunity", "Enough immune people that an outbreak cannot spread, protecting those who cannot be vaccinated."],
      ["Why a flu shot is annual", "The virus changes fast. Last year's memory no longer matches it."],
      ["Fever", "Deliberate. Raised temperature makes you a worse host."],
      ["Inflammation", "The immune response arriving — heat, swelling, pain. Useful acutely, damaging if permanent."],
      ["Allergy", "The immune system attacking something harmless with full force."],
    ],
  },
  {
    id: 'med', phase: 'k3', builds: ['germ'], title: 'What medicine actually knows',
    idea: 'The strength of a medical claim is the design of the study behind it.',
    cards: [
      ["Randomised controlled trial", "Assign treatment by chance and compare. The strongest test a treatment can face."],
      ["Why a trial has phases", "First is it safe, then does it work, then does it work better than what we have."],
      ["Number needed to treat", "How many people must take it for one to benefit. Often far more than you expect."],
      ["Side effect vs cause", "Common things happen to people on drugs too. Only a control group separates them."],
      ["Screening's hidden cost", "Finding harmless things and treating them anyway. More testing is not always better."],
      ["Antiseptic and anaesthesia", "The two nineteenth-century inventions that turned surgery from a last resort into medicine."],
      ["Why life expectancy rose so much", "Mostly clean water, sanitation and childhood survival. Not dramatic cures."],
      ["Painkiller types", "Paracetamol dulls the signal. Ibuprofen reduces inflammation. Opioids block the perception."],
      ["Placebo, properly", "Real improvement from expectation. Strongest on pain and mood, useless on tumours."],
      ["Why doctors say 'no evidence'", "It means it has not been shown, not that it has been disproved. Different claims."],
    ],
  },
  {
    id: 'health', phase: 'k3', builds: ['med'], title: 'Sleep, food and movement',
    idea: 'The unglamorous things have the best evidence behind them.',
    cards: [
      ["What sleep is for", "Clearing waste from the brain and consolidating memory. Not optional, and not recoverable at weekends."],
      ["Sleep debt", "Lost sleep accumulates and impairs you before you notice. Self-assessment fails first."],
      ["Circadian rhythm", "An internal daily clock set mainly by light. Fighting it costs performance and health."],
      ["Why exercise works", "It improves nearly every system measured. The single best-evidenced intervention there is."],
      ["Muscle and strength", "Muscle grows by being damaged slightly and repaired stronger during rest."],
      ["Macronutrients", "Protein builds, carbohydrate fuels, fat stores and signals. You need all three."],
      ["Why fad diets all 'work'", "Nearly any restriction cuts calories at first. Almost none survive the year."],
      ["Ultra-processed food", "Industrially formulated to be easy to overeat. The mechanism is more consumption, not poison."],
    ],
  },
  {
    id: 'aid', phase: 'k3', builds: ['health'], title: 'When someone drops',
    idea: 'A handful of actions, in the first minutes, decide most outcomes.',
    cards: [
      ["Someone collapses and is not breathing", "Call for help, then push hard and fast in the centre of the chest. Do not stop."],
      ["CPR rate", "100 to 120 compressions a minute, at least 5cm deep. Let the chest come back up fully."],
      ["Why hands-only CPR is fine", "For an adult who collapsed suddenly, compressions alone are nearly as good, and people actually do them."],
      ["Defibrillator", "It checks the rhythm and only shocks if shocking helps. You cannot use it wrongly."],
      ["Spotting a stroke", "Face drooping, arm weakness, speech trouble — time to call. Minutes cost brain tissue."],
      ["Spotting a heart attack", "Chest pressure, often with arm, jaw or back pain, sweating, breathlessness. It is often not dramatic."],
      ["Severe bleeding", "Press hard, directly on the wound, and keep pressing. Pressure beats everything else."],
      ["Choking, adult", "Encourage coughing. If they cannot, alternate back blows and abdominal thrusts."],
      ["Recovery position", "Unconscious but breathing: on their side, so the airway stays clear if they vomit."],
      ["Burns", "Cool running water for twenty minutes. No ice, no butter, no bursting blisters."],
    ],
  },

  /* ══════════ 4 · How We Got Here ══════════ */
  {
    id: 'early', phase: 'k4', builds: ['aid'], title: 'Before there was history',
    idea: 'Almost all of human existence happened before anyone could write it down.',
    cards: [
      ["How long humans have existed", "Anatomically modern humans about 300,000 years. Writing, about 5,000."],
      ["Out of Africa", "Modern humans arose in Africa and spread from there. Every population outside descends from that."],
      ["Why fire mattered", "Cooking unlocks far more energy from food, and shrinks the gut and jaw needed to get it."],
      ["Hunter-gatherer life", "Small mobile bands, broad diets, little property, and far more leisure than farming allowed."],
      ["Why language is the human trick", "It lets knowledge accumulate across generations instead of dying with each one."],
      ["Other human species", "Neanderthals and others lived alongside us. Most people outside Africa carry some of their DNA."],
      ["The last ice age", "Ended about 12,000 years ago. Farming appears almost immediately after, in several places at once."],
      ["Why prehistory is inferred", "No writing. Everything comes from bones, tools, rubbish and now DNA."],
    ],
  },
  {
    id: 'agri', phase: 'k4', builds: ['early'], title: 'Farming, and everything it caused',
    idea: 'Growing food made surplus possible, and surplus made everything else possible — including inequality.',
    cards: [
      ["The agricultural revolution", "Farming replaces foraging, about 12,000 years ago, independently in several regions."],
      ["Why farming changed everything", "Storable surplus means settlement, population growth, and people who do not farm."],
      ["The cost of farming", "Worse diets, more disease, harder labour and new hierarchies. It won on numbers, not quality of life."],
      ["Domestication", "Breeding plants and animals for traits we want. It changed them and us."],
      ["Why cities need writing", "Once you store and tax grain, you must record who owns what."],
      ["Where civilisation started", "River valleys: Mesopotamia, the Nile, the Indus, the Yellow River. Water plus silt."],
      ["Why disease exploded", "Dense settlement plus livestock. Most epidemic diseases came from our animals."],
      ["Why Eurasia spread fastest", "Its long east-west axis let crops and animals travel without changing climate."],
    ],
  },
  {
    id: 'write', phase: 'k4', builds: ['agri'], title: 'Writing, law and the first empires',
    idea: 'Writing put memory outside a human head, and that made states possible.',
    cards: [
      ["Why writing was invented", "Accounting. The earliest tablets are receipts, not poetry."],
      ["Cuneiform", "Wedge marks pressed into clay in Mesopotamia. The first writing system we know of."],
      ["Code of Hammurabi", "Babylonian laws carved in public, about 1750 BC. The point was that everyone could see them."],
      ["Why written law matters", "A rule you can point at binds the ruler too, at least in principle."],
      ["Ancient Egypt", "Three thousand years of continuity, built on the Nile's predictable flood."],
      ["The alphabet", "Phoenician traders reduced writing to a couple of dozen signs. Literacy stopped being a profession."],
      ["Bronze then iron", "Bronze needed rare tin and long trade routes. Iron was everywhere, so weapons and ploughs spread."],
      ["The first empires", "Assyria, Babylon, Persia. Roads, tribute, garrisons and a common administrative language."],
      ["Persian Empire", "The largest of the ancient world, run by tolerating local custom and taxing it."],
      ["Why empires collapse", "Overextension, succession fights, climate shocks and the cost of holding what they took."],
    ],
  },
  {
    id: 'classic', phase: 'k4', builds: ['write'], title: 'Greece and Rome',
    idea: 'Two societies whose vocabulary the West still argues in.',
    cards: [
      ["Athenian democracy", "Citizens voting directly, about 500 BC. Excluded women, slaves and foreigners — most of the population."],
      ["Why Greece punched above its size", "Competing city-states, sea trade, and an argumentative culture that wrote its arguments down."],
      ["Greek legacy", "Philosophy, drama, geometry, history as inquiry, and the word for almost every discipline."],
      ["The Roman Republic", "Elected officials, a senate, and deep suspicion of kings. It lasted about 500 years."],
      ["Why the Republic fell", "Generals with loyal armies and vast conquered wealth outgrew the institutions meant to check them."],
      ["Roman Empire", "One ruler, professional army, and two centuries of relative peace across the Mediterranean."],
      ["Roman law", "Contracts, property, evidence and precedent. Most European legal systems still descend from it."],
      ["Roman engineering", "Roads, aqueducts, concrete. Infrastructure as a tool of control."],
      ["Why Rome fell", "Slow: pressure on the frontiers, civil war, plague, economic strain and division into east and west."],
      ["Byzantium", "The eastern empire carried on from Constantinople for another thousand years."],
    ],
  },
  {
    id: 'medieval', phase: 'k4', builds: ['classic'], title: 'The world between',
    idea: 'The centuries Europe calls dark were a golden age somewhere else.',
    cards: [
      ["The Islamic golden age", "From the 8th century, Baghdad and Córdoba led the world in maths, medicine and astronomy."],
      ["What we owe Arabic scholarship", "Algebra, the numerals, optics, and the preservation and translation of Greek thought."],
      ["Feudalism", "Land granted in return for service and loyalty. Government without a working state."],
      ["The medieval church", "The only pan-European institution: literate, wealthy, and the arbiter of legitimacy."],
      ["The Black Death", "Plague killed perhaps a third of Europe in the 1340s."],
      ["Why the plague raised wages", "Far fewer workers, the same land. Labour could suddenly bargain."],
      ["Magna Carta", "1215. Barons forced the king to accept limits. The principle outlived the quarrel."],
      ["The Silk Road", "Overland routes moving goods, ideas, religions and disease between China and the Mediterranean."],
      ["Song China", "Paper money, gunpowder, printing, compass, and the largest cities on Earth."],
      ["Mongol Empire", "The largest contiguous empire ever. Brutal in conquest, then a connector of Eurasia."],
    ],
  },
  {
    id: 'print', phase: 'k4', builds: ['medieval'], title: 'Printing, Renaissance, Reformation',
    idea: 'When copying stopped needing permission, authority stopped being able to hold the line.',
    cards: [
      ["Why the printing press mattered", "Copying stopped needing permission. Ideas outran the people who wanted to stop them."],
      ["Gutenberg", "Movable metal type in Europe, about 1440. Books went from months to days."],
      ["The Renaissance", "A revival of classical learning and a shift towards the human as a subject worth studying."],
      ["Why Italy first", "Rich trading cities, competing patrons, and Roman ruins in the street."],
      ["The Reformation", "Luther, 1517. A challenge to church authority that printing made unstoppable."],
      ["Why the Reformation split Europe", "It made religion a matter of state, and states fought over it for a century."],
      ["Vernacular Bibles", "Scripture in everyday language meant ordinary people could read and argue it themselves."],
      ["The wars of religion", "Ended with the idea that states settle their own religion and stay out of each other's."],
    ],
  },
  {
    id: 'colony', phase: 'k4', builds: ['print'], title: 'Exploration, empire and slavery',
    idea: 'The modern map, and much of modern wealth, was drawn in this period at enormous human cost.',
    cards: [
      ["Age of exploration", "European ships reach the Americas and Asia from the 1490s, seeking trade routes and gold."],
      ["The Columbian exchange", "Crops, animals and diseases crossing the Atlantic in both directions. It reshaped every continent's diet."],
      ["Why the Americas fell so fast", "Disease. Smallpox and others killed the great majority before most Europeans arrived."],
      ["The transatlantic slave trade", "Over twelve million Africans shipped to the Americas across four centuries."],
      ["Why plantation slavery was different", "Hereditary, racialised and industrial in scale, organised for export commodities."],
      ["What abolition took", "Slave revolts, sustained campaigning and war. It was not granted quietly."],
      ["Haiti", "The only successful large slave revolt to found a state, in 1804. It was punished with debt for a century."],
      ["Colonialism's borders", "Straight lines drawn by outsiders. Many of today's conflicts follow them."],
      ["The scramble for Africa", "European powers partitioned almost the whole continent between 1880 and 1900."],
      ["Why this still matters economically", "Extraction built infrastructure aimed outward, and institutions designed to take rather than serve."],
    ],
  },
  {
    id: 'sci', phase: 'k4', builds: ['colony'], title: 'The scientific revolution',
    idea: 'The change was not any single discovery. It was agreeing on how to settle a disagreement.',
    cards: [
      ["What made it revolutionary", "Not new facts — a new method: measure, test, publish, and let others check."],
      ["Copernicus", "Put the sun at the centre. It displaced humans from the middle of creation."],
      ["Galileo", "Turned a telescope on the sky and insisted observation outranks authority. It cost him his freedom."],
      ["Newton", "One set of laws for falling apples and orbiting moons. The sky stopped being a separate realm."],
      ["The Royal Society motto", "'Take nobody's word for it.' The whole programme in four words."],
      ["The Enlightenment", "Applying that confidence to society: reason, rights, tolerance and progress."],
      ["Why it threatened rulers", "If authority must justify itself by reason, inherited authority has a problem."],
      ["The encyclopedia", "An attempt to gather all knowledge in one place, deliberately outside church control."],
    ],
  },
  {
    id: 'indust', phase: 'k4', builds: ['sci'], title: 'The industrial revolution',
    idea: 'Humanity stopped being limited by muscle, water and wind, and started burning buried sunlight.',
    cards: [
      ["What industrialisation was", "Machines and fossil energy replacing human and animal muscle in making things."],
      ["Why coal changed everything", "Concentrated energy that could be moved and burned anywhere, in any weather."],
      ["The steam engine", "Turned heat into motion. It unchained factories from rivers."],
      ["Why Britain first", "Coal, colonies, capital, patents and a big internal market, all at once."],
      ["The factory", "Work moved from home and workshop to a place with fixed hours and supervision."],
      ["What it did to cities", "Explosive growth, appalling sanitation, and death rates that took decades to fix."],
      ["The railway", "Collapsed travel time and forced the invention of standard time zones."],
      ["Why living standards eventually rose", "Productivity rose enough that organised labour and reform could claim a share."],
    ],
  },
  {
    id: 'rev', phase: 'k4', builds: ['indust'], title: 'The age of revolutions',
    idea: 'The idea that legitimacy comes from the governed, tested in blood, repeatedly.',
    cards: [
      ["American Revolution", "Colonies rejecting rule without representation, and founding a republic on written principles."],
      ["French Revolution", "1789. Overthrew monarchy and aristocracy in the name of liberty, equality, fraternity."],
      ["Why the French Revolution turned violent", "War abroad, counter-revolution at home, and no institution able to hold the centre."],
      ["Napoleon", "Ended the revolution and exported its legal code across Europe by conquest."],
      ["The Napoleonic Code", "Written, uniform civil law. Adopted or imitated across much of the world."],
      ["1848", "Revolutions across Europe demanding constitutions and national self-rule. Nearly all failed within a year."],
      ["Nationalism", "The idea that a people should have its own state. It made Germany and Italy, and unmade empires."],
      ["Russian Revolution", "1917. The first state founded on Marxism, and the model for a century of others."],
    ],
  },
  {
    id: 'wars', phase: 'k4', builds: ['rev'], title: 'The wars that made the century',
    idea: 'Almost every institution you deal with was designed by someone determined not to repeat these.',
    cards: [
      ["First World War", "1914-18. Industrial killing on a static front. Around 17 million dead."],
      ["Why it started so easily", "Alliance chains, mobilisation timetables and a widespread belief it would be short."],
      ["Why the peace failed", "Versailles humiliated Germany without disabling it, and the economy collapsed on top."],
      ["The Great Depression", "1929 onwards. Mass unemployment, and the conditions extremists needed."],
      ["Second World War", "1939-45. Roughly 70 to 85 million dead, most of them civilians."],
      ["The Holocaust", "The systematic murder of six million Jews, alongside Roma, disabled people and others."],
      ["Why the Holocaust is studied as a system", "It required bureaucracy, industry and ordinary compliance, not only fanatics."],
      ["What was built afterwards", "The UN, the Declaration of Human Rights, the Geneva Conventions and European integration."],
    ],
  },
  {
    id: 'modern', phase: 'k4', builds: ['wars'], title: 'The century since',
    idea: 'Empires ended, the world split in two, and then the cost of copying anything fell to nothing.',
    cards: [
      ["The Cold War", "Two nuclear-armed blocs competing everywhere without fighting each other directly."],
      ["Mutually assured destruction", "Both sides able to destroy the other after being attacked. Deterrence by guaranteeing catastrophe."],
      ["Decolonisation", "Dozens of new states between 1945 and 1975, often with borders and institutions they did not choose."],
      ["Civil rights movements", "Sustained, organised, largely nonviolent campaigns forcing legal equality where law denied it."],
      ["The green revolution", "New crop varieties and fertiliser multiplied yields and averted predicted famines."],
      ["Fall of the Soviet Union", "1991. The bloc dissolved, mostly without war, and fifteen states appeared."],
      ["Globalisation", "Containers, tariffs falling and supply chains crossing borders. Cheaper goods, relocated work."],
      ["The internet", "The cost of copying and sending information fell to almost nothing. Every industry built on scarcity of it was rearranged."],
    ],
  },

  /* ══════════ 5 · How People Organise ══════════ */
  {
    id: 'state', phase: 'k5', builds: ['modern'], title: 'What a state is',
    idea: 'Every government rests on a story about why it is allowed to tell you what to do.',
    cards: [
      ["State", "An organisation holding a monopoly on legitimate force over a territory."],
      ["Legitimacy", "Why people obey without being forced each time. No state can afford to coerce everyone."],
      ["Sovereignty", "The claim to be the final authority inside your borders, with no higher one above."],
      ["Nation vs state", "A nation is a people who feel common. A state is a government. They often do not match."],
      ["Why borders cause wars", "They were mostly drawn by conquest or outsiders, not by who lives where."],
      ["Failed state", "Where the government cannot deliver security or basic services across its territory."],
      ["Social contract, in practice", "You give up some freedom of action; in return the state protects you from everyone else's."],
      ["Taxation as the core function", "No state has ever existed that could not extract revenue. Everything else follows from it."],
    ],
  },
  {
    id: 'govern', phase: 'k5', builds: ['state'], title: 'Forms of government',
    idea: 'The real question is never the label. It is who can remove the person in charge.',
    cards: [
      ["Democracy", "Rule traced to the governed, usually through elections that can remove the government."],
      ["Republic", "A state with no monarch, where office is held on behalf of the public."],
      ["Constitutional monarchy", "A monarch as head of state with power exercised by elected government."],
      ["Authoritarianism", "Power concentrated and not accountable to a vote that could remove it."],
      ["Totalitarianism", "Authoritarian, plus an attempt to control private life, belief and truth itself."],
      ["Oligarchy", "Rule by a small group, usually the wealthy, whatever the formal system says."],
      ["Theocracy", "Religious law and authority as the basis of the state."],
      ["Federal vs unitary", "Federal splits power between national and regional governments. Unitary keeps it central."],
      ["Parliamentary vs presidential", "Parliamentary: the executive comes from and answers to the legislature. Presidential: elected separately."],
      ["The real test of a democracy", "Whether power actually changes hands when the vote says so."],
    ],
  },
  {
    id: 'law', phase: 'k5', builds: ['govern'], title: 'Law, rights and courts',
    idea: 'A right you cannot enforce in front of someone is a preference.',
    cards: [
      ["Rule of law", "Everyone, including the government, is bound by rules known in advance."],
      ["Separation of powers", "Making law, enforcing it and judging it kept in different hands, each able to check the others."],
      ["Constitution", "The rules for making rules. Usually harder to change than ordinary law, deliberately."],
      ["Judicial review", "Courts able to strike down laws that conflict with the constitution."],
      ["Civil vs criminal law", "Criminal: the state prosecutes a wrong against society. Civil: a dispute between parties."],
      ["Burden of proof in court", "Criminal: beyond reasonable doubt. Civil: more likely than not. A large gap."],
      ["Presumption of innocence", "The state must prove guilt. You never have to prove innocence."],
      ["Due process", "Fair procedure before the state takes your liberty or property. The part that protects everyone."],
      ["Precedent", "Past decisions bind later ones, so similar cases get similar answers."],
      ["Habeas corpus", "The right to be brought before a court so your detention must be justified."],
      ["Negative vs positive rights", "Negative: to be left alone. Positive: to be provided something. They cost differently."],
      ["Human rights", "Claims held simply by being human, not granted by a government and not theirs to withdraw."],
    ],
  },
  {
    id: 'civic', phase: 'k5', builds: ['law'], title: 'How decisions get made',
    idea: 'The mechanics decide the outcome as much as the opinions do.',
    cards: [
      ["How a law is made", "Proposed, debated and amended in a legislature, passed by both chambers if there are two, then signed."],
      ["Lobbying", "Organised persuasion of lawmakers. Legal, and unevenly available."],
      ["First past the post", "Most votes wins the seat. Simple, and it hands power to two large parties."],
      ["Proportional representation", "Seats in proportion to votes. More parties, more coalitions, more negotiation."],
      ["Why the voting system shapes politics", "It decides whether a third party is a real option or a wasted vote."],
      ["Gerrymandering", "Drawing district boundaries so your side wins more seats with the same votes."],
      ["Referendum", "A direct public vote on one question. Clear mandate, no room for nuance."],
      ["Civil service", "Permanent non-political staff who run the state between governments."],
      ["Checks and balances in practice", "Courts, press, opposition, civil service and federalism. Each can be captured separately."],
      ["Free press", "Not a courtesy. The mechanism by which voters find out what was done in their name."],
    ],
  },
  {
    id: 'world', phase: 'k5', builds: ['civic'], title: 'Between states',
    idea: 'There is no world government, so international order is agreement plus leverage.',
    cards: [
      ["United Nations", "Almost every state, founded in 1945 to prevent another world war. Its power is legitimacy, not force."],
      ["UN Security Council", "Five permanent members with a veto. It is why the UN can be paralysed."],
      ["Treaty", "A binding agreement between states. Binding is doing a lot of work in that sentence."],
      ["Geneva Conventions", "The laws of war: protection for civilians, prisoners and the wounded."],
      ["War crime", "A serious violation of the laws of war. Individuals, not just states, can be prosecuted."],
      ["Genocide", "Acts intended to destroy a national, ethnic, racial or religious group. Defined in law in 1948."],
      ["Sanctions", "Economic pressure instead of force. Slow, leaky, and hardest on ordinary people."],
      ["Nuclear deterrence", "Peace held by the certainty of retaliation. Stable until someone miscalculates."],
      ["Refugee vs migrant", "A refugee is fleeing danger and has legal protection. A migrant is moving by choice."],
      ["Soft power", "Getting what you want by being attractive rather than by threatening."],
    ],
  },
  {
    id: 'adult', phase: 'k5', builds: ['world'], title: 'The paperwork of a life',
    idea: 'The documents nobody teaches you to read are the ones that decide your money.',
    cards: [
      ["Contract", "A promise the law will enforce. Offer, acceptance, and something of value each way."],
      ["Why you read before signing", "Signing means you agreed to all of it, including the parts you did not read."],
      ["What insurance is really for", "Not saving money. Turning a rare catastrophe into a small predictable cost."],
      ["Deductible or excess", "What you pay before insurance pays. Higher excess, lower premium."],
      ["Liability", "Legal responsibility for harm. Most insurance you are required to hold covers this, not you."],
      ["Interest rate", "The price of money over time. It is what you pay for having it sooner."],
      ["Compound interest, both ways", "It builds savings and it builds debt. The same mechanism, aimed at or away from you."],
      ["Credit score", "A prediction of whether you repay. Built from history, and it changes what borrowing costs you."],
      ["Minimum payment trap", "Paying the minimum on a card can take decades and cost more than the original debt."],
      ["Gross vs net", "Gross is before deductions. Net is what actually arrives."],
      ["Progressive tax", "Higher rates apply only to the income above each threshold, not to all of it."],
      ["Emergency fund", "Cash covering a few months. It is what stops a bad month becoming expensive debt."],
    ],
  },

  /* ══════════ 6 · The Great Ideas ══════════ */
  {
    id: 'greek', phase: 'k6', builds: ['adult'], title: 'The Greeks who started it',
    idea: 'They did not settle the questions. They worked out how to ask them.',
    cards: [
      ["Socrates", "Claimed to know nothing and questioned everyone until their certainty collapsed. Executed for it."],
      ["Socratic method", "Answering a claim with questions until its contradictions surface."],
      ["Plato", "Argued the world we see is a shadow of perfect unchanging forms behind it."],
      ["Plato's cave", "Prisoners mistaking shadows for reality. What education feels like from inside."],
      ["Aristotle", "Observed and classified everything, and put logic and empirical study at the centre."],
      ["Aristotle on virtue", "Excellence is a habit, formed by practice, sitting between two extremes."],
      ["The golden mean", "Courage sits between cowardice and recklessness. Most virtues work this way."],
      ["Stoicism", "Distinguish what you control from what you do not, and spend yourself only on the first."],
      ["Epicureanism", "Pleasure as the good, meaning friendship, moderation and freedom from fear. Not indulgence."],
      ["Why Greek philosophy survived", "Preserved and translated in the Islamic world, then returned to Europe centuries later."],
    ],
  },
  {
    id: 'ethics', phase: 'k6', builds: ['greek'], title: 'Three ways to decide what is right',
    idea: 'Almost every moral argument you will hear is one of these three, in disguise.',
    cards: [
      ["Virtue ethics", "Ask what a good person would do. Character first, rules second."],
      ["Deontology", "Some acts are right or wrong in themselves, whatever the result."],
      ["Kant's categorical imperative", "Act only on a rule you could will everyone to follow."],
      ["Consequentialism", "The right act is the one with the best outcome."],
      ["Utilitarianism", "The greatest wellbeing for the greatest number."],
      ["The problem with utilitarianism", "It can justify sacrificing an individual for a majority, and that is hard to accept."],
      ["The problem with deontology", "Following a rule off a cliff. It can forbid a lie that would save a life."],
      ["The trolley problem", "Not a puzzle to solve. A tool for finding out which ethics you actually hold."],
      ["Moral luck", "Two identical choices judged differently because one happened to end badly."],
      ["Is-ought gap", "You cannot derive what should be purely from what is."],
    ],
  },
  {
    id: 'politics', phase: 'k6', builds: ['ethics'], title: 'Who should rule, and why',
    idea: 'The argument about legitimacy that every modern constitution is an answer to.',
    cards: [
      ["Hobbes", "Without a strong sovereign, life is 'nasty, brutish and short'. Order first."],
      ["Locke", "Government exists by consent to protect life, liberty and property. Break that and it may be replaced."],
      ["Rousseau", "Legitimate authority comes from the general will of the people, not from force or inheritance."],
      ["Machiavelli", "Described how power is actually kept rather than how rulers ought to behave."],
      ["Adam Smith", "Self-interest coordinated by markets can produce public benefit — with rules and moral sentiment behind it."],
      ["Marx", "History as struggle between classes over who owns the means of production."],
      ["What Marx got right and wrong", "Right that capital concentrates and labour is exploited. Wrong that revolution was inevitable and would liberate."],
      ["Mill on liberty", "Your freedom ends where it harms another. Everything else is your own business."],
      ["Rawls' veil of ignorance", "Design society without knowing who in it you will be. What would you accept?"],
      ["Liberalism, classically", "Individual rights, limited government, rule of law. Both modern 'left' and 'right' descend from it."],
    ],
  },
  {
    id: 'mind', phase: 'k6', builds: ['politics'], title: 'Making sense of the mind',
    idea: 'The study of thinking has been wrong loudly and often, which is itself instructive.',
    cards: [
      ["Descartes", "'I think, therefore I am.' Doubt everything, and find the one thing doubt cannot touch."],
      ["Mind-body problem", "How does physical matter produce experience? Still genuinely unsolved."],
      ["Freud's real contribution", "The idea that much of the mind is unconscious. Most of his specific theories did not hold up."],
      ["Behaviourism", "Study only observable behaviour. Productive, and it left out everything interesting."],
      ["Cognitive revolution", "Treating the mind as information processing brought thinking back as a subject."],
      ["System 1 and System 2", "Fast automatic judgement and slow deliberate reasoning. The first runs most of your life."],
      ["Neuroplasticity", "The brain physically changes with use. Learning is structural, not just storage."],
      ["Memory is reconstruction", "You rebuild a memory each time you recall it, and can rebuild it wrong."],
      ["Why eyewitnesses are unreliable", "Confidence and accuracy barely correlate, and questioning reshapes the memory."],
      ["Nature and nurture", "Not a contest. Genes set ranges; environment decides where in the range you land."],
    ],
  },
  {
    id: 'greats', phase: 'k6', builds: ['mind'], title: 'Ideas that reordered everything',
    idea: 'A handful of insights that each demoted humanity from the centre of something.',
    cards: [
      ["Newton's synthesis", "One set of laws governs heaven and earth. Nature became predictable."],
      ["Darwin's idea", "Design without a designer. It explains complexity without needing a plan."],
      ["Why Darwin was resisted", "It removed humans from a special creation and placed them inside the animal kingdom."],
      ["Einstein on relativity", "Space and time are not a fixed backdrop. They bend, and depend on the observer."],
      ["Quantum mechanics", "At small scales, outcomes are probabilities, not certainties. It is the best-tested theory we have."],
      ["Gödel's incompleteness", "In any sufficiently powerful system of maths, true statements exist that it cannot prove."],
      ["Information theory", "Shannon showed information can be measured in bits. It made all digital communication possible."],
      ["Game theory", "Studying decisions where the outcome depends on what others choose."],
      ["The prisoner's dilemma", "Both would do better cooperating; each does better defecting. Why trust is hard and valuable."],
      ["Tragedy of the commons", "A shared resource each has reason to overuse and none to protect."],
    ],
  },

  /* ══════════ 7 · Belief and Meaning ══════════ */
  {
    id: 'religion', phase: 'k7', builds: ['greats'], title: 'What religion does',
    idea: 'Whatever you believe, these systems shaped the law, art and calendar you live inside.',
    cards: [
      ["What religions have in common", "An account of what is sacred, a moral code, ritual, community, and an answer about death."],
      ["Why ritual persists", "It marks transitions and binds groups. It works socially whether or not the metaphysics is true."],
      ["Monotheism vs polytheism", "One god, or many. The shift towards one reshaped law and identity in the West and Middle East."],
      ["Sacred text", "A written authority a tradition treats as binding. Interpretation is where the disagreements live."],
      ["Orthodoxy vs orthopraxy", "Some traditions centre correct belief. Others centre correct practice."],
      ["Secularism", "Separating religious authority from state power. It is a political arrangement, not a belief."],
      ["Atheism and agnosticism", "Atheism is not believing there is a god. Agnosticism is holding it unknowable."],
    ],
  },
  {
    id: 'abrahamic', phase: 'k7', builds: ['religion'], title: 'The Abrahamic traditions',
    idea: 'Three traditions sharing a starting point and much of a moral vocabulary.',
    cards: [
      ["Judaism", "The covenant between God and the Jewish people, expressed through law, study and observance."],
      ["Torah", "The first five books of the Hebrew Bible, and the foundation of Jewish law."],
      ["Christianity", "Holds that Jesus of Nazareth was the son of God, whose death and resurrection offer salvation."],
      ["Why Christianity spread", "It was universal rather than ethnic, welcomed the poor, and eventually gained an empire."],
      ["The Reformation split", "Catholic, Orthodox and Protestant. The last centred scripture over church authority."],
      ["Islam", "Submission to one God, whose final revelation came through Muhammad in the Quran."],
      ["The five pillars", "Faith, prayer, charity, fasting in Ramadan, and pilgrimage to Mecca."],
      ["Sunni and Shia", "A split over who should have led after Muhammad. It became two distinct traditions."],
      ["What the three share", "One God, descent from Abraham, prophets, scripture, and a great deal of moral common ground."],
    ],
  },
  {
    id: 'eastern', phase: 'k7', builds: ['abrahamic'], title: 'The traditions of Asia',
    idea: 'Frameworks less about belief in a god and more about how to live and see.',
    cards: [
      ["Hinduism", "The oldest living tradition, enormously varied, built around dharma, karma and rebirth."],
      ["Dharma", "Duty and right conduct appropriate to your role and stage of life."],
      ["Karma", "Actions carry consequences that follow you, in this life and the next."],
      ["Buddhism", "Suffering comes from craving; there is a path out of it. Founded by the Buddha in India."],
      ["The four noble truths", "There is suffering; it has a cause; it can end; there is a path to ending it."],
      ["Meditation", "Trained attention. Its effects on stress and focus are among the better-evidenced in psychology."],
      ["Confucianism", "Order through relationships, respect and cultivated character rather than through law."],
      ["Daoism", "Live in accordance with the way things naturally are. Act by not forcing."],
      ["Sikhism", "One God, equality of all people, honest work and service. Founded in Punjab in the fifteenth century."],
      ["Shinto", "Japan's indigenous tradition, centred on spirits in nature, place and ancestry."],
    ],
  },

  /* ══════════ 8 · The Shared References ══════════ */
  {
    id: 'myth', phase: 'k8', builds: ['eastern'], title: 'Greek and Roman myth',
    idea: 'These stories supply the metaphors of English. Not knowing them means missing the point.',
    cards: [
      ["Achilles heel", "One fatal weakness in something otherwise invulnerable."],
      ["Pandora's box", "A small act that releases troubles you cannot put back."],
      ["Trojan horse", "A gift that carries the attack inside it."],
      ["Sisyphean", "Endless effort that achieves nothing, forever."],
      ["Herculean", "Requiring enormous strength or effort."],
      ["Midas touch", "Everything you handle turns to profit. In the story, it was a curse."],
      ["Icarus", "Destroyed by ignoring warnings and overreaching."],
      ["Narcissus", "Consumed by his own reflection. The root of narcissism."],
      ["Odyssey", "A long, difficult journey home, full of obstacles."],
      ["Siren song", "An attraction that lures you to destruction."],
      ["Cassandra", "Someone who is right and not believed."],
      ["Oedipus complex", "Freud's term for a child's rivalry with a parent, from the king who unknowingly killed his father."],
      ["Titan", "One of the older gods overthrown by the Olympians. Now: anyone enormous in their field."],
      ["Nemesis", "The agent of downfall you cannot escape."],
    ],
  },
  {
    id: 'bible', phase: 'k8', builds: ['myth'], title: 'Biblical allusion',
    idea: 'Referenced constantly in law, literature and speech, entirely independent of belief.',
    cards: [
      ["Good Samaritan", "Help from the person with the least obligation to give it."],
      ["David and Goliath", "A small challenger beating an overwhelming favourite."],
      ["Judas", "A betrayer, especially one who was trusted and close."],
      ["Prodigal son", "One who leaves, wastes everything, and is welcomed back anyway."],
      ["The writing on the wall", "An unmistakable sign that the end is coming."],
      ["Forbidden fruit", "The thing made desirable by being prohibited."],
      ["Job's patience", "Enduring undeserved suffering without abandoning your principles."],
      ["Exodus", "Escape from bondage to freedom. The template for liberation movements ever since."],
      ["Golden calf", "Worshipping the wrong thing, usually wealth, in place of what matters."],
      ["Tower of Babel", "Overreaching ambition ending in confusion and an inability to understand each other."],
      ["Doubting Thomas", "Someone who will not believe without direct proof."],
      ["Salt of the earth", "Fundamentally decent, unpretentious people."],
    ],
  },
  {
    id: 'letters', phase: 'k8', builds: ['bible'], title: 'Words that came from books',
    idea: 'Each of these compresses an entire novel into one adjective.',
    cards: [
      ["Orwellian", "State control of truth and language itself, from Nineteen Eighty-Four."],
      ["Big Brother", "Total surveillance presented as protection."],
      ["Kafkaesque", "Crushed by a system that is absurd, impersonal, and will not explain itself."],
      ["Catch-22", "A rule that traps you by its own logic: you can only get out by proving you cannot."],
      ["Machiavellian", "Cunning and unscrupulous in the pursuit and keeping of power."],
      ["Quixotic", "Nobly idealistic in a way that is hopeless and slightly absurd."],
      ["Draconian", "Punishment far harsher than the offence, from an Athenian lawmaker."],
      ["Pyrrhic victory", "A win that cost more than losing would have."],
      ["Faustian bargain", "Getting what you want by trading something you should not have traded."],
      ["Dystopia and utopia", "Utopia: an imagined perfect society. Dystopia: one that went wrong, usually while claiming to be the first."],
      ["Shakespeare's reach", "Star-crossed, wild goose chase, break the ice, in a pickle, all your own invention if you like."],
      ["Hamlet's question", "'To be or not to be' — whether to endure suffering or end it. The most quoted line in English."],
      ["Renaissance man", "Someone accomplished across many unrelated fields."],
      ["Cynic, originally", "A Greek school rejecting wealth and convention. Now: someone who assumes bad motives."],
    ],
  },
  {
    id: 'arts', phase: 'k8', builds: ['letters'], title: 'Art, music and architecture',
    idea: 'Enough to recognise what you are looking at and why it was a break from what came before.',
    cards: [
      ["Renaissance art", "Perspective, anatomy and classical subjects. Da Vinci, Michelangelo, Raphael."],
      ["Why perspective mattered", "It made flat paint look like space. Painting could suddenly show a world rather than symbols."],
      ["Baroque", "Drama, movement, deep shadow and grandeur. Built to overwhelm. Caravaggio, Bernini."],
      ["Impressionism", "Light and moment over detail, painted quickly and often outdoors. Monet, Degas."],
      ["Why Impressionism shocked", "It looked unfinished, and it abandoned the idea that a painting should hide its brushstrokes."],
      ["Modernism", "Abandoning representation and tradition on purpose. Picasso, cubism, abstraction."],
      ["What 'classical' music means", "Strictly a period, roughly 1750-1820: Mozart, Haydn. Loosely, all Western art music."],
      ["Baroque to Romantic music", "Bach's structure, then Mozart's clarity, then Beethoven and Romanticism's emotion and scale."],
      ["Why jazz mattered", "Improvisation and syncopation from Black American musicians. It reshaped nearly all popular music after it."],
      ["Gothic architecture", "Pointed arches, flying buttresses, huge windows. Engineering that let cathedrals fill with light."],
      ["Classical orders", "Doric, Ionic, Corinthian — the column styles Western public buildings still quote."],
      ["Modernist architecture", "Form follows function. Steel, glass, no ornament. It gave us the city you live in."],
    ],
  },
  {
    id: 'latin', phase: 'k8', builds: ['arts'], title: 'The phrases everyone uses',
    idea: 'Mostly Latin, mostly legal, and used constantly by people who never learned them.',
    cards: [
      ["Quid pro quo", "Something given for something received."],
      ["De facto vs de jure", "In fact, versus in law. They often differ."],
      ["Ad hoc", "Made for this one purpose, without a general plan."],
      ["Bona fide", "In good faith. Genuine."],
      ["Caveat emptor", "Let the buyer beware. The risk of checking is yours."],
      ["Status quo", "The way things currently are."],
      ["Per se", "In itself, intrinsically."],
      ["Prima facie", "On first appearance, before anyone has argued the other side."],
      ["Non sequitur", "A conclusion that does not follow from what came before."],
      ["Carpe diem", "Seize the day."],
      ["Et cetera, properly", "'And the rest.' It should never follow a list of people — that is et al."],
      ["Vice versa", "The other way round."],
    ],
  },
  {
    id: 'rhetoric', phase: 'k1', builds: ['source'], title: 'How you are persuaded',
    idea: 'Knowing the moves does not make you immune, but it makes them visible.',
    cards: [
      ["Ethos, pathos, logos", "Persuasion by character, by emotion, by argument. Aristotle's three, still the whole toolkit."],
      ["Framing", "The same fact stated two ways gets two answers. 90% survival and 10% mortality are identical."],
      ["Anchoring in negotiation", "Whoever names a number first sets the range the argument happens in."],
      ["Social proof", "Doing what others do. Efficient in a crowd, exploitable in a market."],
      ["Scarcity and urgency", "Limited time and limited stock work by shutting down deliberation."],
      ["Reciprocity", "A small free gift creates a felt debt. It is why samples exist."],
      ["Repetition and truth", "A claim heard repeatedly feels truer. Familiarity is mistaken for evidence."],
      ["Euphemism", "Swapping the plain word to soften what is being described. Watch for it in official language."],
      ["The Overton window", "The range of positions currently sayable in public. It moves, and it can be moved deliberately."],
      ["Steelmanning", "Arguing against the strongest version of the other case. The opposite of a straw man."],
    ],
  },
  {
    id: 'tech', phase: 'k2', builds: ['chem'], title: 'How the machines work',
    idea: 'You use these hourly. The basics are simpler than the mystique suggests.',
    cards: [
      ["What a computer actually does", "Follows a list of very simple instructions, extremely fast."],
      ["Binary", "Everything stored as ones and zeros, because a switch is either on or off."],
      ["Algorithm", "A set of steps for producing a result. A recipe is one."],
      ["How the internet works", "Data broken into packets, routed independently across many machines, reassembled at the other end."],
      ["Why packets matter", "No single path is required, so the network survives losing pieces of itself."],
      ["Server and client", "The client asks, the server answers. 'The cloud' is someone else's server."],
      ["What encryption does", "Scrambles a message so only the holder of a key can read it."],
      ["Why HTTPS matters", "It encrypts the traffic between you and the site, so what is between cannot read or alter it."],
      ["Why two-factor helps", "A stolen password alone stops being enough. Most account theft dies here."],
      ["Machine learning", "Finding patterns in examples rather than being given rules. It learns correlations, not understanding."],
      ["Why AI makes things up", "It predicts plausible continuations. Plausible and true are different targets."],
      ["Open source", "Code anyone can read, use and change. Most of the internet runs on it."],
    ],
  },
  {
    id: 'mindhealth', phase: 'k3', builds: ['health'], title: 'The mind as an organ',
    idea: 'Treated as illness rather than character, most of it responds to treatment.',
    cards: [
      ["Depression, clinically", "Persistent low mood and loss of interest, lasting weeks, impairing function. Not sadness."],
      ["Anxiety disorder", "Fear out of proportion to the threat, persistent enough to shape behaviour."],
      ["Why 'just cheer up' fails", "It is a disorder of the machinery producing mood, not a choice about attitude."],
      ["What actually treats depression", "Talking therapies and medication, roughly comparably, and better together than either alone."],
      ["Addiction", "Compulsive use despite harm. The brain's reward learning captured by a shortcut."],
      ["Tolerance and withdrawal", "The body adapts, so more is needed, and stopping hurts. That is the trap, not weakness."],
      ["Stress response", "Useful in bursts, corrosive when permanent. Chronic stress damages nearly every system."],
      ["Why loneliness is a health risk", "Its measured effect on mortality is comparable to smoking. Humans are not optional social animals."],
      ["Placebo and the mind", "Expectation changes reported pain and mood measurably. It is real, and it is limited."],
      ["Why sleep and mood are linked", "Poor sleep worsens mood and mood worsens sleep. Breaking either helps the other."],
    ],
  },
  {
    id: 'language', phase: 'k6', builds: ['mind'], title: 'Language and meaning',
    idea: 'The words available to you shape what you can easily think.',
    cards: [
      ["Why language is not just labels", "Words carve the world into categories. Different languages carve differently."],
      ["Wittgenstein's turn", "Meaning is use. A word means what it does in the way people actually play the game."],
      ["Connotation vs denotation", "What a word literally names, and everything it drags along with it."],
      ["Ambiguity", "Most misunderstanding is one word doing two jobs, not disagreement about facts."],
      ["Metaphor is not decoration", "We think in metaphors — argument as war, time as money — and they constrain the conclusions."],
      ["Jargon", "Precision inside a field, exclusion outside it. Both effects are real."],
      ["Why definitions end arguments", "A great many disputes dissolve the moment both sides state what they mean."],
      ["Descriptive vs prescriptive", "Describing how language is used, versus ruling how it should be. Dictionaries do the first."],
      ["Etymology", "A word's history. Interesting, and not binding on what it means now."],
      ["The map is not the territory", "Your model of a thing is never the thing. Confusing them is a standing hazard."],
    ],
  },
  {
    id: 'practice', phase: 'k7', builds: ['eastern'], title: 'Religion as it is lived',
    idea: 'The calendar, the food, the buildings and the holidays around you all came from somewhere.',
    cards: [
      ["Why the week has seven days", "Babylonian astronomy, carried into Jewish observance and then across the world."],
      ["Sabbath", "A commanded day of rest. Arguably the origin of the idea that time off is owed to you."],
      ["Pilgrimage", "Travel to a sacred place as devotion. The Hajj, the Camino, the Ganges, Jerusalem."],
      ["Fasting", "Going without as discipline and solidarity. Ramadan, Lent, Yom Kippur."],
      ["Dietary law", "Rules about what may be eaten — kosher, halal, vegetarian traditions. Identity as much as diet."],
      ["Monasticism", "Withdrawal into disciplined community. It preserved literacy and learning through European upheaval."],
      ["Why religion funded the art", "Institutions with wealth and a reason to commission awe. Most pre-modern Western art was ordered by it."],
      ["Christmas and Easter", "Birth and resurrection of Jesus, both attached to older seasonal festivals."],
      ["Passover", "The Jewish remembrance of the exodus from Egypt."],
      ["Diwali", "The festival of lights, celebrated across Hindu, Sikh and Jain traditions."],
      ["Missionary religions", "Traditions that actively seek converts spread furthest. Christianity and Islam are the clearest cases."],
      ["Syncretism", "Traditions blending where they meet. Most living religion contains layers of what came before it."],
    ],
  },
  {
    id: 'stories', phase: 'k8', builds: ['latin'], title: 'The stories everyone knows',
    idea: 'Referenced without explanation, because everyone is assumed to have them.',
    cards: [
      ["Aesop's fables", "Short animal tales with a moral. The tortoise and the hare, the boy who cried wolf."],
      ["The boy who cried wolf", "Lie often enough and you will not be believed when it matters."],
      ["Sour grapes", "Deciding you never wanted the thing you failed to get."],
      ["Trojan war", "Ten years of siege over Helen, ended by the horse. The source of the Iliad and the Odyssey."],
      ["King Arthur", "Round table, Excalibur, Camelot. The shorthand for chivalry and its inevitable loss."],
      ["Don Quixote", "An old man who reads too many romances and sets out to live one. Often called the first novel."],
      ["Tilting at windmills", "Fighting imaginary enemies with great seriousness. From Quixote."],
      ["Robinson Crusoe", "Shipwrecked and self-sufficient. The template for every survival story since."],
      ["Frankenstein", "Not the monster — the maker. A creation escaping the responsibility of whoever made it."],
      ["Moby Dick", "Obsessive pursuit that destroys the pursuer. Any consuming, ruinous quest is a white whale."],
      ["A Christmas Carol", "Miser shown his past, present and future, and changes. Scrooge became a common noun."],
      ["1984 and Brave New World", "Two warnings: controlled by pain, or controlled by pleasure. Both are quoted constantly."],
    ],
  },
];

/* Cards in curriculum order: phase by phase, principle by principle. Each
   carries its principle as its group, so a session mixes them rather than
   marching through one idea's cards back to back. */
export const KNOWLEDGE_CARDS = PHASES.flatMap((phase) =>
  PRINCIPLES.filter((p) => p.phase === phase.id).flatMap((p) =>
    p.cards.map(([front, back]) => ({ front, back, category: phase.name, principle: p.id, group: p.id }))
  )
);
