/* UVU Need to Know — the tour-guide exam material, verbatim from the study
   guide so what you rehearse is what you are asked. Sections are kept as
   categories, so Topics lets you drill one college at a time. */

const S1 = 'General Facts & History';
const S2 = 'Woodbury School of Business';
const S3 = 'Humanities & Social Sciences';
const S4 = 'School of the Arts';
const S5 = 'Health & Public Service';
const S6 = 'School of Education';
const S7 = 'Engineering & Technology';
const S8 = 'College of Science';

export const UVU_SECTIONS = [S1, S2, S3, S4, S5, S6, S7, S8];

const CARDS = [
  /* ── 1 · Quick general facts and history ────────────────── */
  [S1, 'In what year was UVU founded?', '1941.'],
  [S1, 'When was the Orem Campus dedicated?', '1977.'],
  [S1, "What architectural style features bold design and dramatic use of concrete on UVU's main campus?", 'Brutalist architecture.'],
  [S1, 'In what year did UVU become an official university?', '2008.'],
  [S1, "What are UVU's official university colors?", 'Green and White.'],
  [S1, "What is the name of UVU's mascot?", 'Willy (Wilson) the Wolverine.'],
  [S1, "What is UVU's institution size ranking in Utah?", 'Largest institution in Utah.'],
  [S1, "What was UVU's student population in Fall 2025?", '48,670.'],
  [S1, 'What is the average class size at UVU?', '25.'],
  [S1, 'Roughly how many countries are represented in the UVU student body?', 'Roughly 74 countries.'],
  [S1, 'What are the six former institution names of UVU, in order?',
    'Central Utah Vocational School (1941) · Utah Trade Technical Institute (1963) · Utah Technical College (1967) · Utah Valley Community College (1987) · UVSC (1993) · Utah Valley University (2008).'],
  [S1, 'Who served as president from 1941 to 1946?', 'Hyrum E. Johnson.'],
  [S1, 'Who served as president from 1946 to 1982?', 'Wilson W. Sorensen.'],
  [S1, 'Who served as president from 1982 to 1987?', 'J. Marvin Higbee.'],
  [S1, 'Who served as president from 1988 to 2002?', 'Kerry D. Romesburg.'],
  [S1, 'Who served as president from 2003 to 2009?', 'William A. Sederburg.'],
  [S1, 'Who served as president from 2008 to 2018?', 'Matthew S. Holland.'],
  [S1, 'Who served as president from 2018 to 2026?', 'Astrid S. Tuminez.'],
  [S1, 'Who was named president in 2026?', 'John Andersen.'],
  [S1, 'Who was the first female acting president of an institution in Utah, and when did she serve?',
    'Lucille T. Stoddard (1987–1988 and 2002–2003).'],
  [S1, 'Who served as interim president in 2008–2009?', 'Elizabeth T. Hitch.'],
  [S1, 'Who served as interim president in 2026?', 'Wayne Vaught.'],
  [S1, "What is UVU's primary focus, and what three pillars support it?",
    'Student Success, supported by Inclusion, Engagement and Achievement.'],
  [S1, 'What three exceptional outcomes define the Core Value on Care and Accountability?',
    'Exceptional care, exceptional accountability, and exceptional results.'],
  [S1, 'How is UVU funded?', '49% by tuition, 51% by the state (taxes, donors and so on).'],
  [S1, 'What is undergraduate tuition per semester, in-state and out-of-state?',
    'In-state roughly $3,135. Out-of-state roughly $8,915.'],
  [S1, 'How many programs does UVU offer in each category?',
    '109 certificates, 65 associate, 110 bachelor, 20 master, 60 online programs, 180 active clubs.'],
  [S1, 'Which institution educates the most undergraduates in Utah?', 'UVU.'],
  [S1, 'What does it mean that UVU is a "hybrid institution"?',
    'It offers programs common to community colleges as well as the longer programs of a university.'],
  [S1, 'What is the official motto of UVU?', '"A Place For You At UVU".'],
  [S1, 'What does the Yellow student parking pass cost and cover?',
    '$115 a calendar year or $80 a semester. Covers all student lots on main campus.'],
  [S1, 'Where is Purple student parking, what does it cost, and how do students reach main campus?',
    'Free. On West Campus across I-15, with students shuttling in on UVX buses.'],
  [S1, 'What are the rules for motorcycle and moped parking?',
    'Free, as long as you park in the designated motorcycle areas.'],
  [S1, 'What are the key details of the campus parking structure?',
    'Six levels. $1/hour or a $10 day pass, two-hour minimum. Visitor parking for the Roots of Knowledge exhibit.'],
  [S1, 'What does the free UTA transit pass include, and how is it activated?',
    'All UTA buses, TRAX, FrontRunner and UVX. Activated with your student or employee ID card.'],
  [S1, 'Where does the UVX route run, and how often do buses come?',
    'Throughout Provo and Orem, every 5 minutes — 10 to 15 in rush hour.'],

  /* ── 2 · Woodbury School of Business ─────────────────────── */
  [S2, 'What accreditation does the Woodbury School of Business hold, and how rare is it?',
    'AACSB International Accreditation — a commitment to rigorous, innovative business education, held by only the top 5% of business colleges worldwide.'],
  [S2, 'What is "Direct Admission" in the Woodbury School of Business?',
    'Students enter business majors directly, without a lengthy secondary application.'],
  [S2, 'What business resources are provided at the Fulton Library?',
    'Dedicated business librarians, group study rooms, and extensive databases.'],
  [S2, 'What leads to high rates of paid internships for business students?',
    'Strong local business connections and experiential learning.'],
  [S2, 'What is housed inside the Keller Building?',
    'The Bloomberg Lab, SMART Lab for marketing research, the Entrepreneurship Institute, flexible classrooms, group study areas, corporate presentation spaces, and the Business Advising and Career Center staff.'],
  [S2, 'How does personalised advising support business students?',
    'Dedicated academic advisors guide students through course scheduling and graduation plans.'],
  [S2, 'What core values do Woodbury programs emphasise?',
    'Ethical leadership, corporate responsibility, and global perspectives.'],
  [S2, 'What five student organisations are highlighted for business students?',
    'DECA, AMA (American Marketing Association), Women in Business, Finance Club, and the Entrepreneurship Club.'],
  [S2, 'Why are Business Career Fairs hosted regularly on campus?',
    'To connect students with regional and national employers.'],

  /* ── 3 · Humanities and Social Sciences ──────────────────── */
  [S3, 'What are the seven departments within CHSS?',
    'Communication · History · Behavioral Science · Languages and Cultures · Humanities and Philosophy · English and Literature · Integrated Studies.'],
  [S3, 'What activities make up "Engaged Learning" in CHSS?',
    'Internships, community research, study abroad, and writing labs.'],
  [S3, 'Which CHSS degree offers flexible, interdisciplinary paths?', 'Integrated Studies.'],
  [S3, 'What careers does CHSS real-world experience prepare students for?',
    'Law, public policy, counselling, editing, translation, and media.'],
  [S3, 'Which library support centres enhance CHSS research and critical writing?',
    'The Fulton Library and the Writing Center.'],
  [S3, 'What soft skills and ethical values does CHSS emphasise?',
    'Critical thinking, cultural awareness, ethical decision-making, ethics, and civil discourse.'],

  /* ── 4 · School of the Arts ──────────────────────────────── */
  [S4, 'How many degrees does the School of the Arts offer?',
    '24 bachelor degrees, 10 associate degrees, and 3 degree minors.'],
  [S4, 'What two professional-level facilities are home to the School of the Arts?',
    'The Noorda Center for the Performing Arts and the UVU Museum of Art.'],
  [S4, 'What hands-on creative experiences are available to arts students?',
    'Performances, exhibitions, masterclasses, workshops, and guest residencies.'],
  [S4, 'Who mentors students in the School of the Arts?',
    'Industry-experienced faculty — active artists, performers, directors and scholars.'],
  [S4, 'How many internship and professional engagement partners support the School of the Arts?',
    'More than 180.'],
  [S4, 'What cross-disciplinary fields does the School of the Arts collaborate with?',
    'Tech, healthcare, and education.'],
  [S4, 'What does award-winning student success in the arts prepare students for?',
    'Graduate programs, professional placements, and competitions.'],
  [S4, 'Why is the School of the Arts considered a cultural hub?',
    'It brings hundreds of performances and exhibitions to campus each year.'],

  /* ── 5 · Health and Public Service ───────────────────────── */
  [S5, 'Where are CHPS programs located across the four campuses?',
    'Provo Airport: Fire and EMS · West Campus: Nursing and Physician Assistant · Lehi: Dental Hygiene, Respiratory Therapy, OTA and PTA · Main Campus: everything else, plus the Dean\'s office and advising.'],
  [S5, 'What nickname is given to CHPS, and who does it prepare?',
    'The "College of Heroes" — healthcare professionals, first responders, and public servants.'],
  [S5, 'Where is the centralised Student Support Hub for CHPS?',
    'On main campus, housing advising and faculty offices.'],
  [S5, 'What practical training method is used across CHPS programs?',
    'Hands-on simulation in state-of-the-art simulation labs.'],
  [S5, 'What flexible learning pathways are available in CHPS?',
    'Both cohort-based programs and flexible learning paths.'],
  [S5, "What makes CHPS's Emergency Services bachelor's degree nationally innovative?",
    "It is one of the nation's first 60-credit bachelor's degrees in Emergency Services."],

  /* ── 6 · School of Education ─────────────────────────────── */
  [S6, 'In what three buildings or centres can you find the School of Education?',
    'The McKay Education Building, the Melisa Nellesen Center for Autism, and the Losee Center.'],
  [S6, 'What mission drives the School of Education?',
    '"Teaching Makes a Difference" — preparing impactful K-12 educators.'],
  [S6, 'When do Education students start gaining classroom experience?',
    'From day one, alongside experienced teachers.'],
  [S6, 'How are UVU teaching graduates regarded across Utah?',
    'Highly sought after as top-quality teaching candidates.'],
  [S6, 'What specialties and certificates does the School of Education offer?',
    'Early childhood, elementary, special education and secondary specialties, plus Autism Studies certificates and minors.'],
  [S6, 'Why does the School of Education keep close ties with local districts?',
    'For clinical experiences and strong school district partnerships.'],
  [S6, 'What background do School of Education faculty bring?',
    'Instructors are former K-12 teachers, bringing real practical skills.'],
  [S6, 'What student organisations represent the School of Education?',
    'Future Educators of UVU, with national recognition through Educators Rising.'],
  [S6, 'What environment is the McKay Building modelled on, and what was added in 2025?',
    'An authentic elementary school environment, with a 2025 annex extension.'],
  [S6, 'What is the Creative Learning Studio?',
    'A tech-centred lab for innovative teaching practice.'],

  /* ── 7 · Engineering and Technology ──────────────────────── */
  [S7, 'Where are SCET programs located on campus?',
    'The Smith Engineering Building and the Culinary Arts Institute.'],
  [S7, "What are SCET's key numbers?",
    '6,500+ students, 453 faculty and staff, 8 technology departments, 121 degrees.'],
  [S7, 'When did the new SCET building open?', 'January.'],
  [S7, 'How did SCET students do at the SkillsUSA National Championships in Atlanta?',
    'They earned 11 medals — more than any other school in the nation.'],
  [S7, 'What instructional methodology does SCET emphasise?',
    'Hands-on, project-based learning (PBL).'],
  [S7, 'What signature spring event, formerly Capstone Day, is held in the Sorensen Center Ballroom?',
    'SCET Expo Day.'],
  [S7, 'Who is the Dean of SCET, and what does he bring?',
    'Dr. Spencer Magleby — decades of industry and higher education experience, with strong ties to Utah County.'],
  [S7, 'What student support services are provided for SCET students?',
    'A dedicated advising team, plus the Career and Internship Center for resumes, interview practice, job searches and tutoring.'],

  /* ── 8 · College of Science ──────────────────────────────── */
  [S8, 'What six locations house the College of Science?',
    'Pope Science Building · Science Building · Capitol Reef Field Station · Greenhouse · Grit Garden · Herbarium · UVU Planetarium.'],
  [S8, "Which two College of Science majors are among UVU's largest academic programs?",
    'Biology and Exercise Science.'],
  [S8, 'How do students engage in research in the College of Science?',
    'Student-driven undergraduate research — leading projects, presenting at national conferences, and receiving grant funding.'],
  [S8, 'What hands-on learning facilities does the College of Science feature?',
    'Cadaver anatomy labs, microbiology and biotechnology labs, GIS technology, greenhouses, and human performance facilities.'],
  [S8, 'What is inside the Pope Science Building?',
    'Advanced research labs, a 40-seat digital planetarium, and rooftop greenhouses.'],
  [S8, 'How does faculty mentorship work in Science programs?',
    'Small classes where faculty mentor students directly on research projects.'],
  [S8, 'What future fields does Science preparation focus on?',
    'Pre-health and STEM — medical school, graduate degrees, education, and tech industries.'],
  [S8, 'What annual community science event takes place every October?', 'Science Week.'],
  [S8, 'What unique experiential opportunities does the College of Science offer?',
    'Advanced chemistry equipment, planetarium shows, live animal and plant collections, and field research at Capitol Reef Field Station.'],
];

export const UVU_CARDS = CARDS.map(([category, front, back], i) => ({
  front, back, category, group: 'uvu-' + i, seq: i,
}));
